/* ============================================================
   deutschoderwas club · Aussprachetraining
   16 Lauteinheiten von A1 bis C1.
   Jede: Erklärung, Mundstellung, Minimalpaare, Wörter, Sätze,
   ein Zungenbrecher und die Regel zum Mitnehmen.
   ============================================================ */
window.AUSSPRACHE = [

/* ---------- A1 ---------- */
{ id:'vokale-lang-kurz', lvl:'A1', t:'Lange und kurze Vokale', kurz:'Ofen oder offen — die Länge entscheidet',
  problem:'Für fast alle. Im Deutschen ändert die Vokallänge die Bedeutung, in vielen Sprachen nicht.',
  erklaerung:'Ein Vokal ist lang, wenn ein einzelner Konsonant folgt (Ofen), wenn ein h dahintersteht (Ohr) oder wenn er doppelt geschrieben wird (Boot). Er ist kurz, wenn zwei oder mehr Konsonanten folgen (offen, Kunst).',
  mund:'Beim langen Vokal bleibt der Mund gespannt und die Stellung ändert sich nicht. Beim kurzen Vokal ist der Mund lockerer und du gehst schnell zum Konsonanten weiter.',
  paare:[['Ofen','offen','ein f = lang, zwei f = kurz'],['Staat','Stadt','aa = lang, dt = kurz'],['Beet','Bett','ee = lang, tt = kurz'],['Rate','Ratte','ein t = lang, zwei t = kurz'],['ihn','in','h dehnt den Vokal']],
  woerter:['der Ofen','die Sahne','das Boot','der Zahn','offen','die Sonne','der Himmel','die Mutter'],
  saetze:['Der Ofen ist offen.','In der Stadt gibt es einen Staat im Staate.','Ich rate dir: Diese Ratte ist schnell.'],
  zunge:'Zehn Ziegen ziehen zehn Zentner Zucker zum Zoo.',
  regel:'Ein Konsonant nach dem Vokal → lang. Zwei Konsonanten → kurz. Ein h nach dem Vokal → immer lang.' },

{ id:'r', lvl:'A1', t:'Das deutsche R', kurz:'Hinten im Hals, nicht vorn auf der Zunge',
  problem:'Für Spanisch-, Italienisch-, Russisch-, Türkisch- und Arabischsprechende — dort rollt das R vorn.',
  erklaerung:'Das deutsche R wird hinten gebildet, am Zäpfchen. Am Wortanfang und vor Vokal klingt es wie ein leises Gurgeln (Rot, Frage). Am Wortende und nach langem Vokal wird es zu einem dunklen a-Laut (Uhr klingt wie „Uha", Vater wie „Fata").',
  mund:'Sag ein langes „aaa" und zieh dabei die Zunge hinten hoch, als würdest du gurgeln. Die Zungenspitze bleibt unten hinter den Zähnen — sie bewegt sich nicht.',
  paare:[['Rose','Dose','R hinten, D vorn'],['rot','tot','das R gurgelt'],['der Bruder','das Butter','R nach Konsonant'],['Uhr','Uh-a','R am Ende wird zu a'],['Vater','Fata','-er klingt wie -a']],
  woerter:['rot','die Reise','fragen','der Bruder','die Uhr','der Vater','warten','die Tür'],
  saetze:['Der rote Rock riecht nach Regen.','Mein Bruder repariert die Uhr.','Vater fährt mit dem Fahrrad zur Arbeit.'],
  zunge:'Rote Rosen riechen richtig romantisch.',
  regel:'R am Anfang = gurgeln. R am Ende oder nach langem Vokal = ein dunkles a. Die Zungenspitze bleibt immer unten.' },

{ id:'wortakzent', lvl:'A1', t:'Wortakzent', kurz:'Welche Silbe bekommt den Schlag',
  problem:'Für Französisch-, Türkisch- und Polnischsprechende — dort liegt die Betonung fest.',
  erklaerung:'Im Deutschen liegt die Betonung bei den meisten Wörtern auf der ersten Silbe: ARbeit, FENster, LEHrerin. Bei trennbaren Verben liegt sie auf der Vorsilbe: AUFstehen, EINkaufen. Bei untrennbaren Vorsilben (be-, ver-, ent-, er-, ge-) liegt sie dagegen auf dem Stamm: verSTEHen, beZAHlen.',
  mund:'Die betonte Silbe ist lauter, länger und höher. Klopf beim Sprechen mit dem Finger mit — auf der betonten Silbe klopfst du fester.',
  paare:[['UMfahren (drüberfahren)','umFAHRen (drum herum)','die Betonung ändert die Bedeutung'],['ÜBERsetzen (ans Ufer)','überSETZen (in eine Sprache)','trennbar oder nicht'],['AUFstehen','verSTEHen','auf- ist trennbar, ver- nicht'],['EINkaufen','beZAHLen','ein- trennbar, be- nicht']],
  woerter:['die ARbeit','das FENster','AUFstehen','EINkaufen','verSTEHen','beZAHLen','entSCHULdigung','erKLÄren'],
  saetze:['Ich stehe jeden Morgen um sechs Uhr auf.','Verstehst du, was ich erkläre?','Wir kaufen ein und bezahlen bar.'],
  zunge:'Er erklärt, sie versteht, wir bezahlen, ihr steht auf.',
  regel:'Meistens erste Silbe. Trennbare Vorsilben (auf-, ein-, mit-, an-) werden betont. Untrennbare (be-, ver-, ent-, er-, ge-) nie.' },

{ id:'alphabet', lvl:'A1', t:'Buchstabieren', kurz:'Wenn am Telefon der Name kommt',
  problem:'Für alle — am Telefon, beim Amt, beim Arzt wird ständig buchstabiert.',
  erklaerung:'Die deutschen Buchstabennamen weichen stark vom Englischen ab. Besonders wichtig: E [eː] und I [iː] sind vertauscht im Vergleich zum Englischen, G klingt wie [geː], J wie [jɔt], V wie [faʊ], W wie [veː], Y wie [ʏpsilɔn], Z wie [tsɛt].',
  mund:'Sprich beim Buchstabieren langsam und mach nach jedem Buchstaben eine winzige Pause. Bei ähnlichen Buchstaben hilft ein Wort: „M wie Martha", „N wie Nordpol".',
  paare:[['E [eː]','I [iː]','im Englischen genau andersherum'],['G [geː]','J [jɔt]','G nicht wie im Englischen'],['V [faʊ]','W [veː]','V klingt wie f, W wie englisches v'],['Y [ʏpsilɔn]','Z [tsɛt]','Z ist immer ts']],
  woerter:['A wie Anton','B wie Berta','F wie Friedrich','K wie Kaufmann','P wie Paula','V wie Viktor','W wie Wilhelm','Z wie Zeppelin'],
  saetze:['Mein Name ist Yilmaz: Y wie Ypsilon, I wie Ida, L wie Ludwig, M wie Martha, A wie Anton, Z wie Zeppelin.','Können Sie das bitte buchstabieren?','Das schreibt man mit Doppel-s.'],
  zunge:'Zwölf zerknitterte Zettel zieren Zettelkästen.',
  regel:'Bei Unsicherheit immer mit Wort buchstabieren: „D wie Dora" — das macht in Deutschland jeder, auch Muttersprachler.' },

/* ---------- A2 ---------- */
{ id:'umlaute', lvl:'A2', t:'Die Umlaute ä, ö, ü', kurz:'Der Laut, den es in deiner Sprache nicht gibt',
  problem:'Für fast alle außer Französisch- und Ungarischsprechende.',
  erklaerung:'Ä ist einfach: wie ein offenes e (Bär, Käse). Ö und Ü sind Mischungen. Für ö sagst du „e" und rundest gleichzeitig die Lippen. Für ü sagst du „i" und rundest die Lippen. Die Zunge bleibt vorn, nur die Lippen ändern sich.',
  mund:'Sag ein langes „iiii". Jetzt schieb die Lippen zu einem Kuss nach vorn, ohne die Zunge zu bewegen — das ist ü. Dasselbe mit „eeee" ergibt ö.',
  paare:[['Mutter','Mütter','einer oder mehrere'],['Bruder','Brüder','Umlaut im Plural'],['schon','schön','o oder ö'],['Kuchen','Küchen','Gebäck oder Räume'],['lesen','lösen','e oder ö']],
  woerter:['der Bär','der Käse','schön','hören','die Tür','müde','über','die Bücher'],
  saetze:['Die Mütter hören schöne Musik.','Ich bin müde und möchte über die Brücke gehen.','In den Küchen steht der Kuchen.'],
  zunge:'Müde Mütter müssen über müde Brücken.',
  regel:'ü = i-Zunge plus runde Lippen. ö = e-Zunge plus runde Lippen. Die Zunge bewegt sich nicht mit.' },

{ id:'ch', lvl:'A2', t:'Die zwei ch-Laute', kurz:'ich und ach sind nicht dasselbe',
  problem:'Für Englisch-, Spanisch-, Italienisch- und Türkischsprechende.',
  erklaerung:'Nach den hellen Vokalen e, i, ä, ö, ü und nach l, n, r sowie in -chen kommt das weiche ich-ch: ich, Milch, Mädchen. Nach den dunklen Vokalen a, o, u, au kommt das kratzige ach-ch: Nacht, Koch, Buch, auch.',
  mund:'Für das ich-ch: Sag „ja" und halte den j-Laut, dann flüstere ihn — das ist der Laut. Für das ach-ch: Sag „k" und lass die Luft weiterströmen statt zu stoppen.',
  paare:[['ich','ach','hell und dunkel'],['Kirche','Kirsche','ch oder sch'],['dich','Dach','i macht es weich, a hart'],['Mädchen','machen','-chen ist immer weich'],['Nächte','Nacht','ä hell, a dunkel']],
  woerter:['ich','nicht','die Milch','das Mädchen','die Nacht','der Koch','das Buch','auch'],
  saetze:['Ich möchte nicht mehr Milch.','In der Nacht kocht der Koch ein Buch voll Rezepte.','Das Mädchen macht die Küche sauber.'],
  zunge:'Echt nicht schlecht, sprach der Specht in der Nacht.',
  regel:'Heller Vokal davor (e, i, ä, ö, ü) → weiches ch. Dunkler Vokal davor (a, o, u, au) → kratziges ch. -chen ist immer weich.' },

{ id:'s-z-ss', lvl:'A2', t:'s, z, ß und sch', kurz:'Vier Zischlaute, vier Regeln',
  problem:'Für Englisch-, Spanisch-, Französisch- und Arabischsprechende.',
  erklaerung:'Am Wortanfang vor einem Vokal ist s stimmhaft, es summt: Sonne, sagen. In der Mitte zwischen Vokalen auch: lesen, Rose. Am Wortende und bei ss und ß ist es stimmlos: Haus, Wasser, Fuß. Z ist immer ts: Zeit, zwei, Katze. Sch ist ein einziger Laut wie im englischen „sh".',
  mund:'Leg die Hand an den Hals. Beim stimmhaften s spürst du die Vibration, beim stimmlosen nicht. Für z sprich zuerst ein t und schiebe dann sofort das s hinterher.',
  paare:[['Sonne','Zone','summendes s oder ts'],['reisen','reißen','stimmhaft oder ß'],['weiß','Weise','ß oder stimmhaftes s'],['Zeit','seit','ts oder s'],['Tasse','Tasche','ss oder sch']],
  woerter:['die Sonne','lesen','die Rose','das Haus','das Wasser','der Fuß','die Zeit','die Katze'],
  saetze:['Die Sonne scheint seit sieben Uhr.','Zwei Katzen sitzen auf dem Sofa.','Wir reisen im September zusammen.'],
  zunge:'Zwischen zwei Zwetschgenzweigen zwitschern zwei Schwalben.',
  regel:'s vor Vokal = summen. ss, ß und s am Wortende = zischen. z = immer ts. sch = ein Laut.' },

{ id:'v-w-f', lvl:'A2', t:'v, w und f', kurz:'Das deutsche w ist kein englisches w',
  problem:'Für Englisch-, Spanisch-, Arabisch- und Chinesischsprechende.',
  erklaerung:'Das deutsche w klingt wie das englische v: Wasser, wo, wir. Das deutsche v klingt in deutschen Wörtern wie f: Vater, viel, vier. In Fremdwörtern klingt v dagegen wie w: Vase, Villa, Klavier.',
  mund:'Für w und v legst du die oberen Schneidezähne auf die Unterlippe. Beim w summt es dabei, beim f nicht. Runde niemals die Lippen — das ergibt das englische w.',
  paare:[['Wein','fein','w summt, f nicht'],['Wasser','Fasser','w oder f am Anfang'],['Vater [f]','Vase [w]','deutsches Wort oder Fremdwort'],['wir','vier','w summt, v hier wie f'],['wo','vor','beide mit Zahn an Lippe']],
  woerter:['das Wasser','wir','wohnen','der Vater','viel','vier','die Vase','das Klavier'],
  saetze:['Wir wohnen weit weg von Wien.','Vater hat vier Vasen voll Wasser.','Viele Vögel fliegen von Ort zu Ort.'],
  zunge:'Wer weiß, wo wilde Wölfe wohnen?',
  regel:'w = summendes v. v in deutschen Wörtern = f. v in Fremdwörtern = w. Immer Zähne auf die Unterlippe, nie Lippen runden.' },

{ id:'diphthonge', lvl:'A2', t:'ei, au, eu und äu', kurz:'Zwei Vokale, eine Bewegung',
  problem:'Für alle, die ei mit ie verwechseln.',
  erklaerung:'Ein Diphthong ist eine Gleitbewegung von einem Vokal zum anderen. ei klingt wie „ai" (nein, Bein), au wie in „Haus", eu und äu klingen beide wie „oi" (neu, Häuser). Achtung: ie ist kein Diphthong, sondern ein langes i (Liebe, Bier).',
  mund:'Fang beim ersten Vokal an und gleite ohne Pause zum zweiten. Es ist eine einzige durchgehende Bewegung, keine zwei getrennten Laute.',
  paare:[['Bein','Bien','ei ist ai, ie ist langes i'],['nein','nie','ei oder ie'],['Häuser','Hauser','äu ist oi'],['neu','nie','eu ist oi, ie ist ii'],['Leute','Lüte','eu ist nicht ü']],
  woerter:['nein','das Bein','die Zeit','das Haus','die Frau','neu','die Leute','die Häuser'],
  saetze:['Nein, heute bleibe ich zu Hause.','Neun neue Leute kaufen ein Haus.','Die Häuser der Frau sind heute leer.'],
  zunge:'Neun neue Nähmaschinen nähen neun neue Nähte.',
  regel:'ei = ai. eu und äu = oi. au = au. ie = langes i, niemals ein Diphthong.' },

{ id:'satzmelodie', lvl:'A2', t:'Satzmelodie', kurz:'Runter, rauf oder gleich bleiben',
  problem:'Für alle. Falsche Melodie klingt unhöflich, auch wenn die Wörter stimmen.',
  erklaerung:'Aussagesätze gehen am Ende nach unten: „Ich komme morgen." Ja-Nein-Fragen gehen nach oben: „Kommst du morgen?" W-Fragen gehen dagegen nach unten: „Wann kommst du?" Bei Aufzählungen bleibt die Stimme oben und fällt erst beim letzten Element.',
  mund:'Sprich den Satz und fahr mit der Hand mit — nach unten, nach oben. Die Hand hilft der Stimme.',
  paare:[['Du kommst mit. ↘','Du kommst mit? ↗','dieselben Wörter, andere Aussage'],['Wann kommst du? ↘','Kommst du? ↗','W-Frage runter, Ja-Nein-Frage rauf'],['Das ist gut. ↘','Das ist gut? ↗','Feststellung oder Zweifel']],
  woerter:['Ich komme. ↘','Kommst du? ↗','Wann? ↘','Wirklich? ↗','Alles klar. ↘','Bitte? ↗'],
  saetze:['Ich komme morgen um acht. ↘','Kommst du morgen auch? ↗','Wann genau fängt das an? ↘','Wir brauchen Brot, Milch ↗ und Käse. ↘'],
  zunge:'Kommst du morgen? Morgen komme ich. Wann denn genau?',
  regel:'Aussage ↘ · Ja-Nein-Frage ↗ · W-Frage ↘ · Aufzählung ↗ ↗ ↘' },

/* ---------- B1 ---------- */
{ id:'auslaut', lvl:'B1', t:'Auslautverhärtung', kurz:'Am Wortende wird b zu p, d zu t, g zu k',
  problem:'Für Englisch-, Französisch-, Arabisch- und Russischsprechende.',
  erklaerung:'Am Ende einer Silbe oder eines Wortes werden b, d und g hart gesprochen: Dieb klingt wie „Diep", Kind wie „Kint", Tag wie „Tak". Kommt danach eine Endung mit Vokal, wird es wieder weich: die Diebe, die Kinder, die Tage.',
  mund:'Am Wortende stoppt die Stimme. Leg die Hand an den Hals: Bei „Diebe" vibriert es beim b, bei „Dieb" nicht.',
  paare:[['Dieb [p]','Diebe [b]','Endung macht es weich'],['Kind [t]','Kinder [d]','Singular hart, Plural weich'],['Tag [k]','Tage [g]','dasselbe Muster'],['Rad [t]','Rat [t]','klingt gleich, anders geschrieben'],['Bund [t]','bunt [t]','identisch im Klang']],
  woerter:['der Dieb','das Kind','der Tag','das Rad','der Berg','der Abend','gesund','das Lied'],
  saetze:['Der Tag war lang, die Tage werden kürzer.','Das Kind und die Kinder sind gesund.','Am Abend fahre ich mit dem Rad den Berg hinauf.'],
  zunge:'Der Tag ist lang, die Tage sind lang, am langen Tag lag Lang.',
  regel:'b, d, g am Silbenende → p, t, k. Folgt ein Vokal, bleiben sie weich.' },

{ id:'sp-st', lvl:'B1', t:'sp und st am Wortanfang', kurz:'Am Anfang klingt es schp und scht',
  problem:'Für alle, die es buchstabengetreu lesen.',
  erklaerung:'Am Wortanfang und am Anfang eines Wortteils wird sp zu „schp" und st zu „scht": Sport klingt wie „Schport", Straße wie „Schtraße", verstehen wie „ferschtehen". In der Wortmitte und am Ende bleibt es s+p und s+t: Wespe, Fenster, ist, Wurst.',
  mund:'Denk das sch mit, bevor du das p oder t sprichst. Es ist ein Laut, keine Pause dazwischen.',
  paare:[['Stadt [scht]','ist [st]','Anfang oder Ende'],['Sport [schp]','Wespe [sp]','Anfang oder Mitte'],['stehen [scht]','Fenster [st]','Anfang oder Mitte'],['Straße [schtr]','Wurst [st]','Anfang oder Ende']],
  woerter:['der Sport','die Straße','die Stadt','stehen','verstehen','das Fenster','die Wurst','ist'],
  saetze:['In der Stadt steht ein Sportstudio an der Straße.','Verstehst du, warum das Fenster offen steht?','Die Wurst ist auf dem Tisch — sie ist noch frisch.'],
  zunge:'Sportstudenten stehen still am Stadtstrand.',
  regel:'sp und st am Wortanfang oder Wortteilanfang = schp und scht. Sonst normal s+p, s+t.' },

{ id:'ng-nk', lvl:'B1', t:'ng und nk', kurz:'Kein g am Ende von Ding',
  problem:'Für Italienisch-, Spanisch-, Polnisch- und Türkischsprechende.',
  erklaerung:'Das ng ist ein einziger Nasallaut, hinten am Gaumen gebildet. In „Ding", „lang", „singen" hörst du kein separates g. Beim nk kommt dagegen sehr wohl ein k dazu: danke, trinken, Bank.',
  mund:'Sag „ang" und halte den Laut. Die Zunge liegt hinten am Gaumen und die Luft geht durch die Nase. Lass die Zunge dort — sobald du sie löst, hörst du das falsche g.',
  paare:[['singen','sinken','ng ohne g, nk mit k'],['lang','Lank','ng ist ein Laut'],['Ding','dünn','ng oder n'],['danke','Dange','nk hat ein echtes k'],['Enge','Ecke','ng oder k']],
  woerter:['das Ding','lang','singen','die Zeitung','danke','trinken','die Bank','denken'],
  saetze:['Wir singen ein langes Lied.','Danke, ich trinke gern einen Tee an der Bank.','Die Zeitung liegt schon lange auf dem Tisch.'],
  zunge:'Lange Schlangen singen langsam Lieder.',
  regel:'ng = ein Nasallaut, nie ein hörbares g. nk = Nasallaut plus deutliches k.' },

{ id:'reduktion', lvl:'B1', t:'Endungen verschlucken', kurz:'-en, -er und -e im echten Sprechtempo',
  problem:'Für alle, die zu deutlich sprechen und dadurch fremd klingen.',
  erklaerung:'Im normalen Sprechtempo verschwindet das e in der Endung -en fast völlig: „haben" klingt wie „habm", „machen" wie „machn", „reden" wie „redn". Die Endung -er klingt wie ein dunkles a: „Vater" wie „Fata", „besser" wie „bessa". Auch -e am Ende wird sehr schwach: „Tasche" endet auf einem gehauchten Rest.',
  mund:'Sprich die Endung nicht mit, sondern lass den Konsonanten die Silbe tragen. Bei „habm" schließen die Lippen einfach und die Luft geht durch die Nase.',
  paare:[['haben [habm]','habe [habə]','-en verschluckt, -e schwach'],['machen [machn]','mache [machə]','n trägt die Silbe'],['Vater [fata]','Vati [fati]','-er wird zu a'],['besser [bessa]','Besen [besn]','-er zu a, -en zu n']],
  woerter:['haben','machen','reden','laufen','der Vater','besser','die Lehrer','die Kinder'],
  saetze:['Wir haben lange geredet und viel gemacht.','Die Lehrer sagen, die Kinder werden besser.','Am Wasser laufen wir jeden Abend.'],
  zunge:'Wir haben Hafen, Häfen haben Wasser.',
  regel:'-en → der Konsonant trägt die Silbe. -er → dunkles a. Nicht deutlicher sprechen als nötig — das klingt sonst gestelzt.' },

/* ---------- B2 · C1 ---------- */
{ id:'satzakzent', lvl:'B2', t:'Satzakzent', kurz:'Ein Wort im Satz trägt die Botschaft',
  problem:'Für alle, die grammatisch richtig, aber missverständlich klingen.',
  erklaerung:'In jedem Satz gibt es ein Wort, das die eigentliche Information trägt — es wird lauter, länger und höher gesprochen. Welches das ist, entscheidet die Situation. „ICH habe das gesagt" heißt: nicht jemand anderes. „Ich habe das GESAGT" heißt: nicht geschrieben.',
  mund:'Entscheide vor dem Sprechen, welches Wort die Neuigkeit trägt. Alles andere sprichst du bewusst leiser und schneller.',
  paare:[['ICH habe angerufen.','Ich habe ANGERUFEN.','wer oder was'],['MORGEN fahren wir.','Morgen FAHREN wir.','wann oder was'],['Das ist MEIN Buch.','Das ist mein BUCH.','wessen oder welches Ding']],
  woerter:['ICH','DU','HEUTE','NICHT','SELBST','SCHON'],
  saetze:['ICH habe das nicht gesagt — jemand anderes.','Ich habe das NICHT gesagt — das ist eine Unterstellung.','Ich habe das nicht GESAGT — ich habe es geschrieben.'],
  zunge:'Das habe ICH gesagt, nicht DU, und zwar HEUTE, nicht MORGEN.',
  regel:'Ein Hauptakzent pro Sinneinheit. Er liegt auf der neuen Information, nicht automatisch am Satzende.' },

{ id:'rhythmus', lvl:'C1', t:'Rhythmus und Pausen', kurz:'Wo du atmest, entscheidet, ob man dir folgt',
  problem:'Für Fortgeschrittene, die alles richtig sagen, aber trotzdem anstrengend klingen.',
  erklaerung:'Deutsch ist eine akzentzählende Sprache: Zwischen zwei betonten Silben liegt ungefähr gleich viel Zeit, egal wie viele unbetonte dazwischen stehen. Die unbetonten Silben werden also gequetscht. Pausen setzt du nicht dort, wo du Luft brauchst, sondern an den Sinngrenzen — nach dem Subjektblock, vor dem Nebensatz, vor der Pointe.',
  mund:'Markier dir in einem Text die betonten Silben und klopf sie im gleichmäßigen Takt. Der Rest passt sich von selbst an.',
  paare:[['Ich KOMme MORgen.','Ich bin geKOMmen am MORgen.','gleicher Takt, mehr Silben'],['Er sagt, | dass er kommt.','Er sagt dass er kommt.','mit und ohne Sinnpause']],
  woerter:['nämlich','allerdings','tatsächlich','im Übrigen','offen gestanden','wohlgemerkt'],
  saetze:['Was mich daran stört, | ist nicht die Entscheidung selbst, | sondern die Art, | wie sie kommuniziert wurde.','Er hat, | soweit ich weiß, | nie etwas anderes behauptet.','Und genau das | ist der Punkt.'],
  zunge:'Wer wagt, gewinnt — wer zögert, verliert, und wer schweigt, wird überhört.',
  regel:'Gleicher Abstand zwischen betonten Silben. Pausen an Sinngrenzen, nicht an Atemgrenzen. Vor der Pointe eine kurze Pause — das wirkt.' },

{ id:'fremdwoerter', lvl:'C1', t:'Fremdwörter betonen', kurz:'Restaurant, Balkon, Ingenieur',
  problem:'Für Fortgeschrittene — hier verraten sich auch sehr gute Sprecher.',
  erklaerung:'Fremdwörter behalten oft die Betonung der Herkunftssprache und liegen damit am Wortende statt am Anfang: RestauRANT, BalKON, IngeniEUR, StuDENT, UniversiTÄT, TeleFON. Wörter auf -ie, -ion, -tät, -ent, -ant, -eur werden fast immer hinten betont.',
  mund:'Bei Endungen auf -ion, -tät, -ie, -ent, -eur: Betonung auf die letzte Silbe. Das ist eine verlässliche Regel.',
  paare:[['StuDENT','STUdium','Endung entscheidet'],['TeleFON','TELEfonisch','Betonung wandert'],['MuSIK','MUsiker','-ik hinten, -iker vorn'],['DemokraTIE','demoKRAtisch','-ie hinten, -isch davor']],
  woerter:['das RestauRANT','der BalKON','der IngeniEUR','die UniversiTÄT','die SituaTION','die DemokraTIE','der ProfesSOR','das ExemPLAR'],
  saetze:['Der Ingenieur studiert an der Universität.','Die Situation im Restaurant war kompliziert.','Diese Diskussion über Demokratie ist typisch.'],
  zunge:'Der Professor der Universität diskutiert die Situation im Restaurant.',
  regel:'-ion, -tät, -ie, -ent, -ant, -eur, -ik → Betonung auf der letzten Silbe. Bei Ableitungen wandert sie oft nach vorn.' }
];
