/* ============================================================
   dialoge-neu.js — Dialoge fuer die fuenf Bereiche ohne einen

   Kochen, Medizin, Reinigung, Technik/Planung und Landwirtschaft
   hatten Wortschatz und Hoertexte, aber keine einzige Situation
   zum Mitreden.

   Wird NACH dialoge.js geladen und haengt seine Situationen an.
   dialoge.js bleibt unangetastet; nimmt man die Zeile in
   konto.html heraus, ist alles wie vorher.

   Aufbau je Schritt wie in dialoge.js:
     amanda · hinweis · beispiel · redemittel
   ============================================================ */
(function () {
  if (!window.DIALOGE || !window.DIALOGE.push) return;

  var NEU = [
 {
  "id": "einkaufszettel",
  "modus": "alltag", "em": "🥕", "titel": "Was kochen wir heute?", "lvl": "A2",
  "dauer": "3 Min", "kat": "essen",
  "ort": "Ihr steht in der Küche und überlegt, was es heute zu essen gibt.",
  "schritte": [
   { "amanda": "Ich habe Hunger. Was kochen wir denn heute?",
     "hinweis": "Mach einen Vorschlag und sag, warum.",
     "beispiel": "Wie wäre es mit Suppe? Es ist kalt draußen.",
     "redemittel": ["Wie wäre es mit …?", "Ich hätte Lust auf …", "Wir könnten … machen."] },
   { "amanda": "Suppe klingt gut. Haben wir alles da?",
     "hinweis": "Sag, was da ist und was fehlt.",
     "beispiel": "Kartoffeln und Zwiebeln haben wir. Möhren fehlen noch.",
     "redemittel": ["Wir haben noch …", "Es fehlt nur …", "… ist alle."] },
   { "amanda": "Dann gehe ich einkaufen. Wie viel brauchen wir?",
     "hinweis": "Nenn eine Menge.",
     "beispiel": "Ein Kilo Möhren reicht, wir sind ja zu dritt.",
     "redemittel": ["Ein Kilo …", "Eine Packung …", "Das reicht für …"] },
   { "amanda": "Soll ich noch etwas mitbringen?",
     "hinweis": "Nenn noch zwei Sachen — und sei höflich.",
     "beispiel": "Wenn du magst, noch Brot und Sahne. Danke dir!",
     "redemittel": ["Wenn du magst, noch …", "Bring bitte auch …", "Das wäre lieb."] },
   { "amanda": "Und wer kocht?",
     "hinweis": "Teilt die Arbeit auf.",
     "beispiel": "Ich schneide das Gemüse, du kochst — einverstanden?",
     "redemittel": ["Ich mache …, du machst …", "Einverstanden?", "Ich übernehme …"] }
  ]
 },
 {
  "id": "rezept-erklaeren",
  "modus": "alltag", "em": "🍲", "titel": "Ein Rezept erklären", "lvl": "B1",
  "dauer": "3 Min", "kat": "essen",
  "ort": "Eine Freundin will wissen, wie du dein Lieblingsgericht kochst.",
  "schritte": [
   { "amanda": "Das schmeckt so gut! Wie machst du das?",
     "hinweis": "Nenn zuerst die wichtigsten Zutaten.",
     "beispiel": "Es sind nur vier Sachen: Reis, Zwiebeln, Tomaten und Öl.",
     "redemittel": ["Man braucht …", "Es sind nur …", "Das Wichtigste ist …"] },
   { "amanda": "Und wie fängst du an?",
     "hinweis": "Beschreibe den ersten Schritt.",
     "beispiel": "Zuerst schneide ich die Zwiebeln und brate sie kurz an.",
     "redemittel": ["Zuerst …", "Als Erstes …", "Ich fange mit … an."] },
   { "amanda": "Und dann?",
     "hinweis": "Zwei weitere Schritte, in der richtigen Reihenfolge.",
     "beispiel": "Dann kommen die Tomaten dazu, und zum Schluss der Reis.",
     "redemittel": ["Dann …", "Danach …", "Zum Schluss …"] },
   { "amanda": "Wie lange muss das kochen?",
     "hinweis": "Nenn eine Zeit und woran man das Ende erkennt.",
     "beispiel": "Etwa zwanzig Minuten — bis der Reis weich ist.",
     "redemittel": ["Etwa … Minuten.", "So lange, bis …", "Man merkt es daran, dass …"] },
   { "amanda": "Kann man auch etwas weglassen?",
     "hinweis": "Sag, was man tauschen kann.",
     "beispiel": "Statt Reis geht auch Nudeln. Ohne Zwiebeln schmeckt es weniger.",
     "redemittel": ["Statt … kann man …", "Ohne … schmeckt es …", "Das geht auch mit …"] }
  ]
 },
 {
  "id": "anamnese-kurz",
  "modus": "business", "em": "🩺", "titel": "Beschwerden erfragen", "lvl": "B2",
  "dauer": "4 Min", "kat": "gesundheit",
  "ort": "Du bist in der Praxis. Eine Patientin sitzt vor dir und klagt über Bauchschmerzen.",
  "schritte": [
   { "amanda": "Guten Tag. Ich habe seit ein paar Tagen Bauchschmerzen.",
     "hinweis": "Begrüße sie und frag nach dem Beginn.",
     "beispiel": "Guten Tag. Seit wann genau haben Sie die Schmerzen?",
     "redemittel": ["Seit wann genau …?", "Wann hat das angefangen?", "Erzählen Sie mir bitte …"] },
   { "amanda": "Seit Montag, glaube ich. Mal mehr, mal weniger.",
     "hinweis": "Frag nach Ort und Stärke.",
     "beispiel": "Können Sie mir zeigen, wo genau? Und wie stark ist es von eins bis zehn?",
     "redemittel": ["Können Sie mir zeigen, wo …?", "Wie stark sind die Schmerzen?", "Strahlt es irgendwohin aus?"] },
   { "amanda": "Hier unten rechts. Vielleicht eine Sechs.",
     "hinweis": "Frag nach Begleitsymptomen.",
     "beispiel": "Hatten Sie Fieber, Übelkeit oder Durchfall dazu?",
     "redemittel": ["Hatten Sie auch …?", "Ist Ihnen übel?", "Haben Sie Fieber gemessen?"] },
   { "amanda": "Übel war mir gestern, ja. Fieber habe ich nicht gemessen.",
     "hinweis": "Erklär, was du jetzt machst — ohne Fachwörter.",
     "beispiel": "Ich taste den Bauch ab und nehme Blut ab. Das dauert ein paar Minuten.",
     "redemittel": ["Ich schaue mir … an.", "Wir machen zuerst …", "Das dauert etwa …"] },
   { "amanda": "Ist das etwas Schlimmes?",
     "hinweis": "Antworte ehrlich und ruhig, ohne ein Ergebnis zu versprechen.",
     "beispiel": "Das kann ich erst nach der Untersuchung sagen. Wir klären das heute.",
     "redemittel": ["Das kann ich erst sagen, wenn …", "Im Moment sieht es … aus.", "Wir klären das heute."] }
  ]
 },
 {
  "id": "befund-erklaeren",
  "modus": "business", "em": "📋", "titel": "Einen Befund erklären", "lvl": "B2",
  "dauer": "3 Min", "kat": "gesundheit",
  "ort": "Der Blutwert ist auffällig. Der Patient versteht die Zahlen nicht.",
  "schritte": [
   { "amanda": "Auf dem Zettel stehen so viele Zahlen. Was heißt das denn?",
     "hinweis": "Nenn zuerst das Wichtigste in einem Satz.",
     "beispiel": "Das Wichtigste zuerst: Ein Wert ist zu niedrig, alles andere ist in Ordnung.",
     "redemittel": ["Das Wichtigste zuerst: …", "Kurz gesagt: …", "Ein Wert fällt auf: …"] },
   { "amanda": "Welcher denn?",
     "hinweis": "Erklär den Wert in einfachen Worten.",
     "beispiel": "Ihr Eisenwert. Eisen braucht der Körper, um Blut zu bilden.",
     "redemittel": ["Das ist der Wert für …", "Der Körper braucht das, um …", "Man kann sich das so vorstellen: …"] },
   { "amanda": "Und deshalb bin ich so müde?",
     "hinweis": "Bestätige vorsichtig und ohne zu übertreiben.",
     "beispiel": "Das passt gut zusammen, ja. Sicher sind wir nach der nächsten Kontrolle.",
     "redemittel": ["Das passt zusammen.", "Möglich ist es.", "Sicher wissen wir es, wenn …"] },
   { "amanda": "Was mache ich jetzt?",
     "hinweis": "Nenn zwei klare Schritte.",
     "beispiel": "Sie nehmen vier Wochen Tabletten, dann messen wir noch einmal.",
     "redemittel": ["Zuerst …, danach …", "Sie nehmen … für …", "Wir sehen uns in … wieder."] },
   { "amanda": "Und wenn es nicht besser wird?",
     "hinweis": "Sag, wann er sich melden soll.",
     "beispiel": "Wenn Sie nach zwei Wochen keine Besserung merken, rufen Sie an.",
     "redemittel": ["Melden Sie sich, wenn …", "Sollte … nicht besser werden, dann …", "Rufen Sie ruhig an."] }
  ]
 },
 {
  "id": "reinigung-uebergabe",
  "modus": "business", "em": "🧽", "titel": "Schicht übergeben", "lvl": "A2",
  "dauer": "3 Min", "kat": "team",
  "ort": "Deine Schicht ist zu Ende. Die Kollegin von der Spätschicht kommt.",
  "schritte": [
   { "amanda": "Hallo! Wie war es heute — alles geschafft?",
     "hinweis": "Sag, was fertig ist.",
     "beispiel": "Hallo! Die Büros und der Flur sind fertig, alles gewischt.",
     "redemittel": ["… ist fertig.", "Ich habe schon …", "Alles erledigt bis auf …"] },
   { "amanda": "Und was ist noch offen?",
     "hinweis": "Nenn, was liegen geblieben ist, und warum.",
     "beispiel": "Der Besprechungsraum fehlt noch. Da war bis eben ein Termin.",
     "redemittel": ["Offen ist noch …", "Ich bin nicht dazu gekommen, weil …", "Bitte mach du noch …"] },
   { "amanda": "Ist mit dem Material alles in Ordnung?",
     "hinweis": "Sag, was fehlt oder kaputt ist.",
     "beispiel": "Das Reinigungsmittel für die Böden ist fast leer, bitte nachbestellen.",
     "redemittel": ["… ist fast leer.", "… ist kaputt.", "Wir brauchen neue …"] },
   { "amanda": "Gab es sonst etwas?",
     "hinweis": "Erwähne eine Beschwerde oder Besonderheit.",
     "beispiel": "Im dritten Stock hat sich jemand über den Flur beschwert. Ich habe ihn noch einmal gemacht.",
     "redemittel": ["Es gab eine Beschwerde über …", "Achte bitte auf …", "Aufgefallen ist mir …"] },
   { "amanda": "Alles klar. Schönen Feierabend!",
     "hinweis": "Verabschiede dich und sag, wann du wieder da bist.",
     "beispiel": "Danke dir! Ich bin morgen wieder in der Frühschicht.",
     "redemittel": ["Danke, dir auch!", "Morgen bin ich wieder …", "Bis morgen!"] }
  ]
 },
 {
  "id": "reinigung-beschwerde",
  "modus": "business", "em": "📢", "titel": "Eine Beschwerde annehmen", "lvl": "B1",
  "dauer": "3 Min", "kat": "kunden",
  "ort": "Eine Mitarbeiterin sagt dir, dass ihr Büro gestern nicht sauber war.",
  "schritte": [
   { "amanda": "Entschuldigung — mein Büro war gestern überhaupt nicht gemacht.",
     "hinweis": "Hör zu und zeig, dass du es ernst nimmst.",
     "beispiel": "Das tut mir leid, das sollte nicht passieren. Welches Zimmer ist es?",
     "redemittel": ["Das tut mir leid.", "Danke, dass Sie es sagen.", "Um welchen Raum geht es?"] },
   { "amanda": "Zimmer 212. Der Papierkorb war voll und der Boden staubig.",
     "hinweis": "Frag genau nach, ohne dich zu verteidigen.",
     "beispiel": "Verstanden — Papierkorb und Boden. War das nur gestern so?",
     "redemittel": ["Verstanden: …", "War das nur gestern?", "Ist Ihnen noch mehr aufgefallen?"] },
   { "amanda": "Vorgestern war es auch schon nicht besonders.",
     "hinweis": "Sag, was du jetzt tust.",
     "beispiel": "Ich mache das Zimmer heute selbst und schaue mir den Plan an.",
     "redemittel": ["Ich kümmere mich darum.", "Ich mache heute …", "Ich schaue nach, woran es lag."] },
   { "amanda": "Danke. Kann ich mich darauf verlassen?",
     "hinweis": "Gib eine Zusage, die du auch halten kannst.",
     "beispiel": "Ja. Bis heute Abend ist es gemacht, ich sage Ihnen morgen Bescheid.",
     "redemittel": ["Bis … ist es erledigt.", "Ich gebe Ihnen Bescheid.", "Sie können sich darauf verlassen."] },
   { "amanda": "Gut, danke Ihnen.",
     "hinweis": "Bedanke dich für den Hinweis.",
     "beispiel": "Gern. Und sagen Sie mir gern gleich Bescheid, wenn wieder etwas ist.",
     "redemittel": ["Gern.", "Sagen Sie mir ruhig Bescheid.", "Danke für den Hinweis."] }
  ]
 },
 {
  "id": "abnahme-begleiten",
  "modus": "business", "em": "📐", "titel": "Eine Abnahme begleiten", "lvl": "B2",
  "dauer": "4 Min", "kat": "kunden",
  "ort": "Der Kunde steht vor der neuen Anlage. Zwei Punkte sind noch offen.",
  "schritte": [
   { "amanda": "Wir würden heute gern abnehmen. Ist alles fertig?",
     "hinweis": "Sag ehrlich, was steht und was nicht.",
     "beispiel": "Die Anlage läuft. Zwei Punkte sind noch offen, die zeige ich Ihnen gleich.",
     "redemittel": ["Die Anlage läuft.", "Offen sind noch …", "Ich zeige Ihnen …"] },
   { "amanda": "Welche Punkte sind das?",
     "hinweis": "Nenn beide sachlich, ohne Ausreden.",
     "beispiel": "Die Abdeckung fehlt noch, und ein Sensor wird nächste Woche getauscht.",
     "redemittel": ["Erstens …, zweitens …", "Es fehlt noch …", "… wird ausgetauscht."] },
   { "amanda": "Und warum ist das nicht fertig?",
     "hinweis": "Begründe kurz und nenn einen Termin.",
     "beispiel": "Das Teil kam verspätet vom Lieferanten. Am Donnerstag ist es montiert.",
     "redemittel": ["Der Grund ist …", "Am … ist es erledigt.", "Wir haben es schon bestellt."] },
   { "amanda": "Können wir trotzdem abnehmen?",
     "hinweis": "Schlag eine Abnahme mit Restpunkten vor.",
     "beispiel": "Ja — wir nehmen mit diesen beiden Restpunkten ab und halten sie schriftlich fest.",
     "redemittel": ["Wir können … mit Restpunkten abnehmen.", "Wir halten schriftlich fest, dass …", "Das würde ich so vorschlagen."] },
   { "amanda": "Einverstanden. Wer schreibt das auf?",
     "hinweis": "Sag, wer was macht und bis wann.",
     "beispiel": "Ich schicke Ihnen das Protokoll heute Abend zum Gegenlesen.",
     "redemittel": ["Ich schicke Ihnen …", "Bitte lesen Sie gegen.", "Bis … haben Sie es."] }
  ]
 },
 {
  "id": "aenderung-begruenden",
  "modus": "business", "em": "🔧", "titel": "Eine Änderung begründen", "lvl": "B2",
  "dauer": "3 Min", "kat": "buero",
  "ort": "In der Fertigung passt ein Maß nicht. Du musst die Zeichnung ändern lassen.",
  "schritte": [
   { "amanda": "Du willst die Zeichnung ändern? Wir sind mitten in der Fertigung.",
     "hinweis": "Sag klar, worum es geht.",
     "beispiel": "Ja. Die Bohrung muss zwei Millimeter weiter nach innen.",
     "redemittel": ["Es geht um …", "Wir müssen … ändern.", "Konkret: …"] },
   { "amanda": "Warum? Bisher lief es doch.",
     "hinweis": "Nenn den Grund, kurz und nachvollziehbar.",
     "beispiel": "An der Schnittstelle stößt die Schraube an. Das haben wir erst beim Einbau gesehen.",
     "redemittel": ["Der Grund ist …", "Aufgefallen ist das beim …", "Sonst passiert Folgendes: …"] },
   { "amanda": "Was kostet uns das?",
     "hinweis": "Nenn Aufwand und Folgen ehrlich.",
     "beispiel": "Zwei Tage und zehn Teile in die Nacharbeit. Ohne Änderung wären es mehr.",
     "redemittel": ["Der Aufwand ist …", "Das kostet uns …", "Ohne die Änderung wäre …"] },
   { "amanda": "Geht es nicht anders?",
     "hinweis": "Zeig, dass du Alternativen geprüft hast.",
     "beispiel": "Ich habe zwei Wege geprüft. Der andere wäre billiger, hält aber nicht dauerhaft.",
     "redemittel": ["Ich habe … geprüft.", "Die Alternative wäre …, aber …", "Dauerhaft hält nur …"] },
   { "amanda": "Gut. Was brauchst du von mir?",
     "hinweis": "Bitte um die Freigabe und nenn den nächsten Schritt.",
     "beispiel": "Deine Freigabe bis morgen früh, dann geht die neue Zeichnung raus.",
     "redemittel": ["Ich brauche deine Freigabe bis …", "Danach …", "Ich melde mich, sobald …"] }
  ]
 },
 {
  "id": "hof-einweisung",
  "modus": "business", "em": "🚜", "titel": "Einen Helfer einweisen", "lvl": "B1",
  "dauer": "3 Min", "kat": "handwerk",
  "ort": "Ein neuer Saisonhelfer steht vor dir. Heute wird geerntet.",
  "schritte": [
   { "amanda": "Guten Morgen! Ich bin neu — was soll ich machen?",
     "hinweis": "Begrüße ihn und sag, was heute ansteht.",
     "beispiel": "Guten Morgen! Heute ernten wir das Feld hinter der Scheune.",
     "redemittel": ["Heute machen wir …", "Deine Aufgabe ist …", "Wir fangen mit … an."] },
   { "amanda": "Und wie genau?",
     "hinweis": "Erklär die Arbeit in drei Schritten.",
     "beispiel": "Erst die Kiste holen, dann Reihe für Reihe pflücken, volle Kisten an den Weg stellen.",
     "redemittel": ["Erst …, dann …, danach …", "Wichtig ist, dass …", "Immer der Reihe nach."] },
   { "amanda": "Woran erkenne ich, was reif ist?",
     "hinweis": "Gib ein einfaches Erkennungszeichen.",
     "beispiel": "Nimm nur die dunklen. Die hellen bleiben noch zwei Tage hängen.",
     "redemittel": ["Nimm nur …", "Alles, was … ist, bleibt hängen.", "Du erkennst es an …"] },
   { "amanda": "Wann ist Pause?",
     "hinweis": "Sag Zeiten und wo.",
     "beispiel": "Um neun eine Viertelstunde, um zwölf eine halbe. Vorn am Schuppen.",
     "redemittel": ["Um … ist Pause.", "Wir treffen uns bei …", "Feierabend ist um …"] },
   { "amanda": "Und wenn ich etwas nicht weiß?",
     "hinweis": "Sag, an wen er sich wendet.",
     "beispiel": "Dann frag mich oder Petra. Lieber einmal fragen als eine Reihe falsch machen.",
     "redemittel": ["Dann frag einfach …", "Lieber fragen als …", "Ich bin auf dem Feld."] }
  ]
 },
 {
  "id": "wetter-arbeit",
  "modus": "business", "em": "🌧️", "titel": "Wetter ändert den Plan", "lvl": "B1",
  "dauer": "3 Min", "kat": "handwerk",
  "ort": "Es regnet seit dem Morgen. Die geplante Arbeit auf dem Feld geht nicht.",
  "schritte": [
   { "amanda": "Bei dem Regen können wir doch nicht raus, oder?",
     "hinweis": "Sag, was heute nicht geht — und warum.",
     "beispiel": "Nein. Der Boden ist zu nass, der Traktor bleibt stecken.",
     "redemittel": ["Heute geht … nicht.", "Der Grund ist …", "Bei dem Wetter …"] },
   { "amanda": "Und was machen wir stattdessen?",
     "hinweis": "Schlag zwei andere Arbeiten vor.",
     "beispiel": "Wir könnten die Halle aufräumen und die Maschinen prüfen.",
     "redemittel": ["Wir könnten …", "Stattdessen machen wir …", "Das wäre auch mal dran."] },
   { "amanda": "Wie lange dauert das?",
     "hinweis": "Nenn eine Zeit.",
     "beispiel": "Bis Mittag sind wir durch, denke ich.",
     "redemittel": ["Bis … sind wir fertig.", "Das dauert etwa …", "Höchstens …"] },
   { "amanda": "Und wann holen wir das Feld nach?",
     "hinweis": "Nenn einen neuen Termin — mit Vorbehalt.",
     "beispiel": "Wenn es morgen trocken bleibt, fangen wir früh um sechs an.",
     "redemittel": ["Wenn … bleibt, dann …", "Sonst verschieben wir auf …", "Wir schauen morgen früh."] },
   { "amanda": "Sag ich das den anderen?",
     "hinweis": "Klärt, wer wen informiert.",
     "beispiel": "Ja, sag du es den Helfern. Ich rufe beim Nachbarn wegen der Maschine an.",
     "redemittel": ["Sag du bitte …", "Ich kümmere mich um …", "Dann weiß es jeder."] }
  ]
 }
 ,
 {
  "id": "telefon-praxis",
  "modus": "alltag", "em": "☎️", "titel": "Beim Arzt anrufen", "lvl": "A2",
  "dauer": "3 Min", "kat": "gesundheit",
  "ort": "Du rufst in einer Praxis an und willst einen Termin. Am Telefon geht alles schneller als im Kurs.",
  "schritte": [
   { "amanda": "Praxis Dr. Sommer, Sie sprechen mit Frau Yildiz, guten Tag.",
     "hinweis": "Melde dich mit deinem Namen und sag, warum du anrufst.",
     "beispiel": "Guten Tag, mein Name ist Ana Silva. Ich hätte gern einen Termin.",
     "redemittel": ["Mein Name ist …", "Ich hätte gern …", "Ich rufe an, weil …"] },
   { "amanda": "Wie war Ihr Name? Können Sie den buchstabieren?",
     "hinweis": "Buchstabiere deinen Namen — ruhig und langsam.",
     "beispiel": "Gern: S wie Samuel, I wie Ida, L wie Ludwig, V wie Viktor, A wie Anton.",
     "redemittel": ["Gern: … wie …", "Ich buchstabiere: …", "Soll ich es wiederholen?"] },
   { "amanda": "Danke. Am Dienstag um 8:15 wäre etwas frei.",
     "hinweis": "Du hast nicht alles verstanden. Frag höflich nach.",
     "beispiel": "Entschuldigung, könnten Sie das bitte wiederholen? Um wie viel Uhr?",
     "redemittel": ["Könnten Sie das bitte wiederholen?", "Etwas langsamer, bitte.", "Habe ich richtig verstanden: …?"] },
   { "amanda": "Dienstag, acht Uhr fünfzehn. Passt das?",
     "hinweis": "Sag zu — oder schlag etwas anderes vor.",
     "beispiel": "Dienstag passt leider nicht. Geht auch Mittwochnachmittag?",
     "redemittel": ["Das passt gut.", "Da kann ich leider nicht.", "Ginge auch …?"] },
   { "amanda": "Mittwoch um 15:30 hätte ich noch etwas.",
     "hinweis": "Bestätige den Termin und verabschiede dich.",
     "beispiel": "Mittwoch halb vier, das notiere ich mir. Vielen Dank, auf Wiederhören.",
     "redemittel": ["Das notiere ich mir.", "Vielen Dank für Ihre Hilfe.", "Auf Wiederhören."] }
  ]
 },
 {
  "id": "telefon-ausrichten",
  "modus": "business", "em": "📞", "titel": "Der Kollege ist nicht da", "lvl": "B1",
  "dauer": "3 Min", "kat": "buero",
  "ort": "Du gehst ans Telefon. Die Person, die gesucht wird, ist im Urlaub.",
  "schritte": [
   { "amanda": "Guten Tag, Berger hier. Könnte ich bitte Herrn Kaya sprechen?",
     "hinweis": "Sag, dass er nicht da ist — und wann er wieder da ist.",
     "beispiel": "Guten Tag, Frau Berger. Herr Kaya ist bis Montag im Urlaub.",
     "redemittel": ["… ist heute nicht im Haus.", "… ist bis … im Urlaub.", "Er ist gerade in einem Termin."] },
   { "amanda": "Oh. Und wer kann mir sonst weiterhelfen?",
     "hinweis": "Biete an, etwas auszurichten oder zu verbinden.",
     "beispiel": "Ich kann ihm etwas ausrichten — oder ich verbinde Sie mit seiner Vertretung.",
     "redemittel": ["Kann ich etwas ausrichten?", "Ich verbinde Sie mit …", "Soll er Sie zurückrufen?"] },
   { "amanda": "Richten Sie ihm bitte aus, dass die Lieferung nicht angekommen ist.",
     "hinweis": "Wiederhole die Nachricht, damit nichts verloren geht.",
     "beispiel": "Ich notiere: die Lieferung ist nicht angekommen. Habe ich das richtig?",
     "redemittel": ["Ich notiere: …", "Habe ich das richtig verstanden?", "Ich wiederhole kurz: …"] },
   { "amanda": "Genau. Er hat meine Nummer.",
     "hinweis": "Frag trotzdem nach Nummer und Erreichbarkeit.",
     "beispiel": "Zur Sicherheit: unter welcher Nummer erreicht er Sie, und wann am besten?",
     "redemittel": ["Zur Sicherheit: …", "Unter welcher Nummer …?", "Wann sind Sie am besten erreichbar?"] },
   { "amanda": "Ab neun bin ich immer am Platz. Vielen Dank!",
     "hinweis": "Beende das Gespräch mit einer klaren Zusage.",
     "beispiel": "Danke, ich gebe es ihm gleich Montag früh weiter. Auf Wiederhören.",
     "redemittel": ["Ich gebe es weiter.", "Er meldet sich bei Ihnen.", "Auf Wiederhören."] }
  ]
 },
 {
  "id": "anmeldung-buergeramt",
  "modus": "alltag", "em": "🏠", "titel": "Anmeldung beim Bürgeramt", "lvl": "A2",
  "dauer": "3 Min", "kat": "amt",
  "ort": "Du bist neu in der Stadt und meldest deine Wohnung an. Vor dir sitzt die Sachbearbeiterin.",
  "schritte": [
   { "amanda": "Guten Tag. Was kann ich für Sie tun?",
     "hinweis": "Sag, was du willst — in einem Satz.",
     "beispiel": "Guten Tag. Ich möchte mich anmelden, ich bin neu in die Stadt gezogen.",
     "redemittel": ["Ich möchte mich anmelden.", "Ich bin neu hier.", "Ich komme wegen …"] },
   { "amanda": "Haben Sie den Ausweis und die Wohnungsgeberbestätigung dabei?",
     "hinweis": "Antworte — und sag ehrlich, wenn etwas fehlt.",
     "beispiel": "Den Ausweis habe ich. Die Wohnungsgeberbestätigung schickt mein Vermieter morgen.",
     "redemittel": ["Das habe ich dabei.", "Das fehlt mir leider noch.", "Kann ich das nachreichen?"] },
   { "amanda": "Ohne die Bestätigung kann ich Sie nicht anmelden.",
     "hinweis": "Frag nach, wie es weitergeht.",
     "beispiel": "Verstehe. Muss ich dann einen neuen Termin machen, oder reicht die E-Mail?",
     "redemittel": ["Was heißt das für mich?", "Muss ich neu buchen?", "Reicht auch eine Kopie?"] },
   { "amanda": "Sie können sie per E-Mail nachreichen, dann geht es ohne Termin.",
     "hinweis": "Wiederhole, was du tun musst.",
     "beispiel": "Also: Bestätigung per Mail an Sie, dann kommt die Anmeldung mit der Post?",
     "redemittel": ["Also noch einmal: …", "Ich fasse zusammen: …", "Und danach …?"] },
   { "amanda": "Genau so. Die Meldebescheinigung kommt dann per Post.",
     "hinweis": "Bedanke dich und frag nach der Frist.",
     "beispiel": "Vielen Dank. Bis wann muss die Anmeldung fertig sein?",
     "redemittel": ["Bis wann habe ich Zeit?", "Vielen Dank für Ihre Geduld.", "Gibt es eine Frist?"] }
  ]
 },
 {
  "id": "beratungsstelle",
  "modus": "alltag", "em": "🤝", "titel": "In der Beratungsstelle", "lvl": "B1",
  "dauer": "3 Min", "kat": "amt",
  "ort": "Du hast einen Brief vom Amt bekommen und verstehst ihn nicht. In der Beratungsstelle sitzt jemand, der hilft.",
  "schritte": [
   { "amanda": "Kommen Sie herein. Worum geht es denn?",
     "hinweis": "Beschreibe dein Problem in zwei Sätzen.",
     "beispiel": "Ich habe diesen Brief bekommen und verstehe nicht, was ich tun soll.",
     "redemittel": ["Ich habe einen Brief bekommen von …", "Ich verstehe nicht, was …", "Können Sie mir helfen bei …?"] },
   { "amanda": "Darf ich den Brief sehen? … Hier steht, dass Unterlagen fehlen.",
     "hinweis": "Frag genau nach, welche Unterlagen gemeint sind.",
     "beispiel": "Welche Unterlagen genau? Steht das irgendwo im Brief?",
     "redemittel": ["Welche genau?", "Wo steht das?", "Was bedeutet dieses Wort hier?"] },
   { "amanda": "Ihre Gehaltsabrechnungen der letzten drei Monate.",
     "hinweis": "Sag, was du davon schon hast.",
     "beispiel": "Zwei habe ich zu Hause. Die dritte muss ich beim Arbeitgeber holen.",
     "redemittel": ["Das habe ich schon.", "Das muss ich noch besorgen.", "Wo bekomme ich …?"] },
   { "amanda": "Wichtig ist die Frist: bis zum Fünfzehnten.",
     "hinweis": "Frag, was passiert, wenn es knapp wird.",
     "beispiel": "Und wenn ich das bis dahin nicht schaffe — kann ich die Frist verlängern?",
     "redemittel": ["Was passiert, wenn …?", "Kann man die Frist verlängern?", "An wen wende ich mich dann?"] },
   { "amanda": "Rufen Sie vorher an, das geht meistens.",
     "hinweis": "Fasse zusammen, was du jetzt tust.",
     "beispiel": "Gut: Abrechnungen holen, alles bis zum Fünfzehnten schicken, sonst anrufen. Danke!",
     "redemittel": ["Ich fasse zusammen: …", "Dann mache ich Folgendes: …", "Vielen Dank für Ihre Hilfe."] }
  ]
 },
 {
  "id": "kurs-nachfragen",
  "modus": "alltag", "em": "🙋", "titel": "Im Kurs nachfragen", "lvl": "A2",
  "dauer": "2 Min", "kat": "bildung",
  "ort": "Im Deutschkurs. Die Lehrerin hat gerade etwas erklärt — du hast die Hälfte nicht verstanden.",
  "schritte": [
   { "amanda": "So, ist das für alle klar?",
     "hinweis": "Sag ehrlich, dass du eine Frage hast.",
     "beispiel": "Entschuldigung, ich habe eine Frage.",
     "redemittel": ["Ich habe eine Frage.", "Entschuldigung, …", "Darf ich etwas fragen?"] },
   { "amanda": "Natürlich, immer her damit.",
     "hinweis": "Sag genau, was unklar ist — nicht nur 'alles'.",
     "beispiel": "Den zweiten Satz habe ich nicht verstanden. Warum steht da 'dem'?",
     "redemittel": ["Ich habe … nicht verstanden.", "Warum steht hier …?", "Was ist der Unterschied zwischen … und …?"] },
   { "amanda": "Weil 'mit' immer den Dativ verlangt. Ist das klarer?",
     "hinweis": "Bitte um ein Beispiel.",
     "beispiel": "Fast. Können Sie noch ein Beispiel geben?",
     "redemittel": ["Können Sie ein Beispiel geben?", "Also zum Beispiel: …?", "Und wenn ich sage: …?"] },
   { "amanda": "Zum Beispiel: Ich fahre mit dem Bus.",
     "hinweis": "Wiederhole mit einem eigenen Satz.",
     "beispiel": "Also: Ich gehe mit meiner Schwester ins Kino.",
     "redemittel": ["Also: …", "Dann heißt es: …", "Stimmt das so?"] },
   { "amanda": "Genau richtig!",
     "hinweis": "Bedanke dich — und sag, was du zu Hause übst.",
     "beispiel": "Danke. Ich übe das heute Abend mit zehn eigenen Sätzen.",
     "redemittel": ["Danke, jetzt ist es klar.", "Das übe ich noch.", "Kann ich Ihnen die Sätze zeigen?"] }
  ]
 },
 {
  "id": "kurs-entschuldigung",
  "modus": "alltag", "em": "📧", "titel": "Sich im Kurs entschuldigen", "lvl": "A2",
  "dauer": "2 Min", "kat": "bildung",
  "ort": "Du warst zwei Tage krank. Am ersten Tag zurück sprichst du mit der Lehrerin.",
  "schritte": [
   { "amanda": "Schön, dass Sie wieder da sind! Alles wieder gut?",
     "hinweis": "Erklär kurz, warum du gefehlt hast.",
     "beispiel": "Danke, ja. Ich hatte Fieber und musste zwei Tage zu Hause bleiben.",
     "redemittel": ["Ich war krank.", "Ich musste zu Hause bleiben.", "Es geht wieder."] },
   { "amanda": "Kein Problem. Bringen Sie mir bitte eine kurze Entschuldigung mit.",
     "hinweis": "Frag, was hineingehört.",
     "beispiel": "Gern. Was muss darin stehen — nur die Tage, oder auch der Grund?",
     "redemittel": ["Was muss darin stehen?", "Reicht ein Satz?", "Brauchen Sie ein Attest?"] },
   { "amanda": "Datum, Tage und Ihre Unterschrift reichen.",
     "hinweis": "Frag nach dem verpassten Stoff.",
     "beispiel": "Alles klar. Und was haben wir am Montag und Dienstag gemacht?",
     "redemittel": ["Was habe ich verpasst?", "Welche Seiten waren dran?", "Gibt es Hausaufgaben dazu?"] },
   { "amanda": "Perfekt und Wechselpräpositionen, Seite 40 bis 44.",
     "hinweis": "Sag, wie du es nachholst.",
     "beispiel": "Dann arbeite ich die Seiten heute Abend nach und mache die Übungen.",
     "redemittel": ["Das hole ich nach.", "Ich mache die Übungen bis …", "Kann ich Sie fragen, wenn etwas unklar ist?"] },
   { "amanda": "Sehr gern. Fragen Sie einfach.",
     "hinweis": "Bedanke dich kurz.",
     "beispiel": "Danke, das hilft mir sehr.",
     "redemittel": ["Danke, das hilft mir.", "Sehr nett, danke.", "Bis morgen!"] }
  ]
 },
 {
  "id": "weiterbildung-beratung",
  "modus": "business", "em": "🎓", "titel": "Beratung zur Weiterbildung", "lvl": "B1",
  "dauer": "3 Min", "kat": "bildung",
  "ort": "Bei der Agentur für Arbeit. Du willst wissen, ob dein Abschluss hier zählt.",
  "schritte": [
   { "amanda": "Guten Tag. Sie wollten sich zur Weiterbildung beraten lassen?",
     "hinweis": "Sag, was du gelernt hast und was du willst.",
     "beispiel": "Ja. Ich bin Krankenschwester aus Georgien und möchte hier wieder in dem Beruf arbeiten.",
     "redemittel": ["Ich bin … von Beruf.", "Mein Abschluss ist aus …", "Ich möchte gern wieder …"] },
   { "amanda": "Dann brauchen Sie die Anerkennung Ihres Abschlusses. Haben Sie die schon beantragt?",
     "hinweis": "Antworte und frag nach dem Weg.",
     "beispiel": "Noch nicht. Wo stelle ich den Antrag, und wie lange dauert das?",
     "redemittel": ["Wo stelle ich den Antrag?", "Wie lange dauert das ungefähr?", "Was kostet das?"] },
   { "amanda": "Bei der zuständigen Stelle im Bundesland. Rechnen Sie mit einigen Monaten.",
     "hinweis": "Frag, was du in der Zwischenzeit tun kannst.",
     "beispiel": "Und bis dahin — kann ich schon arbeiten oder einen Kurs machen?",
     "redemittel": ["Und in der Zwischenzeit?", "Kann ich schon …?", "Was raten Sie mir?"] },
   { "amanda": "Ein Fachsprachkurs wäre sinnvoll. Den können wir fördern.",
     "hinweis": "Frag nach der Förderung.",
     "beispiel": "Was heißt fördern genau — übernehmen Sie die Kosten ganz?",
     "redemittel": ["Was heißt das genau?", "Wer zahlt was?", "Welche Voraussetzungen gibt es?"] },
   { "amanda": "Mit Bildungsgutschein ja. Voraussetzung ist B2.",
     "hinweis": "Fasse deinen nächsten Schritt zusammen.",
     "beispiel": "Gut: erst B2 nachweisen, dann Bildungsgutschein, dann der Fachsprachkurs. Danke!",
     "redemittel": ["Ich fasse zusammen: …", "Mein nächster Schritt ist …", "Vielen Dank für die Beratung."] }
  ]
 },
 {
  "id": "praktikum-fragen",
  "modus": "business", "em": "🛠️", "titel": "Nach einem Praktikum fragen", "lvl": "B1",
  "dauer": "3 Min", "kat": "bewerbung",
  "ort": "Du rufst in einem Betrieb an und fragst nach einem Praktikumsplatz.",
  "schritte": [
   { "amanda": "Elektro Haas, guten Tag.",
     "hinweis": "Melde dich und nenne dein Anliegen.",
     "beispiel": "Guten Tag, mein Name ist Omar Haddad. Ich suche einen Praktikumsplatz.",
     "redemittel": ["Mein Name ist …", "Ich suche …", "Ich rufe an, weil …"] },
   { "amanda": "Praktikum in welchem Bereich denn?",
     "hinweis": "Sag, was du kannst und was du lernen willst.",
     "beispiel": "In der Elektrotechnik. Ich habe in Syrien drei Jahre als Elektriker gearbeitet.",
     "redemittel": ["Im Bereich …", "Ich habe … Jahre als … gearbeitet.", "Ich möchte lernen, wie …"] },
   { "amanda": "Und wie lange soll das Praktikum gehen?",
     "hinweis": "Nenn Zeitraum und Umfang.",
     "beispiel": "Vier Wochen, gern ab Anfang nächsten Monats, Vollzeit.",
     "redemittel": ["Etwa … Wochen.", "Ab … wäre möglich.", "In Voll- oder Teilzeit."] },
   { "amanda": "Schicken Sie mir Ihre Unterlagen, dann sehen wir weiter.",
     "hinweis": "Frag, was genau du schicken sollst.",
     "beispiel": "Gern. Reicht der Lebenslauf, oder brauchen Sie auch die Zeugnisse?",
     "redemittel": ["Was soll ich schicken?", "Reicht …?", "An welche Adresse?"] },
   { "amanda": "Lebenslauf reicht erst mal. Meine Mail ist auf der Website.",
     "hinweis": "Bestätige und verabschiede dich freundlich.",
     "beispiel": "Alles klar, den Lebenslauf schicke ich heute noch. Vielen Dank, auf Wiederhören.",
     "redemittel": ["Das schicke ich heute.", "Vielen Dank für die Auskunft.", "Auf Wiederhören."] }
  ]
 },
 {
  "id": "abo-kuendigen",
  "modus": "alltag", "em": "✂️", "titel": "Ein Abo kündigen", "lvl": "B1",
  "dauer": "3 Min", "kat": "vertrag",
  "ort": "Du willst ein Abo beenden. Am Telefon versucht man, dich zu halten.",
  "schritte": [
   { "amanda": "Schön, dass Sie anrufen. Was kann ich für Sie tun?",
     "hinweis": "Sag klar, dass du kündigen willst.",
     "beispiel": "Guten Tag. Ich möchte mein Abo zum nächstmöglichen Termin kündigen.",
     "redemittel": ["Ich möchte kündigen.", "… zum nächstmöglichen Termin.", "Bitte bestätigen Sie mir das schriftlich."] },
   { "amanda": "Darf ich fragen, warum? Wir hätten da ein besseres Angebot …",
     "hinweis": "Bleib freundlich, aber bei deiner Entscheidung.",
     "beispiel": "Danke, aber ich brauche es einfach nicht mehr. Ich bleibe bei der Kündigung.",
     "redemittel": ["Danke, aber …", "Ich bleibe dabei.", "Das brauche ich nicht mehr."] },
   { "amanda": "Verstehe. Zum Monatsende geht es leider nicht mehr.",
     "hinweis": "Frag nach dem genauen Datum.",
     "beispiel": "Zu welchem Datum endet der Vertrag dann genau?",
     "redemittel": ["Zu welchem Datum genau?", "Wie lange läuft er noch?", "Wann wird zuletzt abgebucht?"] },
   { "amanda": "Zum dreißigsten September.",
     "hinweis": "Bitte um eine schriftliche Bestätigung.",
     "beispiel": "Gut. Schicken Sie mir das bitte schriftlich per E-Mail.",
     "redemittel": ["Bitte schriftlich.", "Per E-Mail an …", "Ich hätte das gern bestätigt."] },
   { "amanda": "Mache ich. Sonst noch etwas?",
     "hinweis": "Beende das Gespräch klar.",
     "beispiel": "Nein, danke. Damit ist alles geklärt. Auf Wiederhören.",
     "redemittel": ["Damit ist alles geklärt.", "Nein, danke.", "Auf Wiederhören."] }
  ]
 },
 {
  "id": "phishing-erkennen",
  "modus": "alltag", "em": "🎣", "titel": "Diese Mail ist komisch", "lvl": "B1",
  "dauer": "3 Min", "kat": "vertrag",
  "ort": "Eine Freundin zeigt dir eine E-Mail: angeblich von der Bank, mit einem Link.",
  "schritte": [
   { "amanda": "Schau mal, die Bank will mein Passwort. Soll ich das eingeben?",
     "hinweis": "Sag deutlich Nein — und warum.",
     "beispiel": "Nein, auf keinen Fall. Eine Bank fragt nie per Mail nach dem Passwort.",
     "redemittel": ["Auf keinen Fall.", "Eine Bank fragt nie nach …", "Das sieht nach Betrug aus."] },
   { "amanda": "Aber da steht mein Name drin!",
     "hinweis": "Erklär, woran man eine falsche Mail erkennt.",
     "beispiel": "Namen kann man kaufen. Schau auf die Absenderadresse und auf die Fehler im Text.",
     "redemittel": ["Schau auf …", "Woran man es erkennt: …", "Fahr mit der Maus über den Link."] },
   { "amanda": "Und wenn es doch echt ist? Sie schreiben, mein Konto wird gesperrt.",
     "hinweis": "Sag, wie sie es sicher prüft.",
     "beispiel": "Dann ruf die Bank direkt an — mit der Nummer von deiner Karte, nicht aus der Mail.",
     "redemittel": ["Ruf direkt an, aber …", "Nimm die Nummer von …", "Klick den Link nicht an."] },
   { "amanda": "Okay. Und was mache ich mit der Mail?",
     "hinweis": "Nenn zwei klare Schritte.",
     "beispiel": "Nicht antworten, nichts anklicken, löschen — und wenn du unsicher bist, melde sie.",
     "redemittel": ["Nicht antworten.", "Einfach löschen.", "Du kannst sie melden bei …"] },
   { "amanda": "Gut, dass ich gefragt habe.",
     "hinweis": "Gib ihr eine einfache Regel für die Zukunft mit.",
     "beispiel": "Merk dir: Wer dich drängt und Angst macht, will meistens etwas von dir.",
     "redemittel": ["Merk dir: …", "Im Zweifel: …", "Frag lieber einmal zu viel."] }
  ]
 }
  ];

  var da = {};
  window.DIALOGE.forEach(function (d) { da[d.id] = 1; });
  NEU.forEach(function (d) { if (!da[d.id]) window.DIALOGE.push(d); });
})();
