/* ============================================================
   grammatik-c1-plus.js — Grammatik auf C1 auffüllen

   Gezählt am 09.10.2026: Grammatik hatte auf A1 elf Themen, auf A2
   elf, auf B1 fünfzehn, auf B2 elf — und auf C1 sechs. Das war die
   deutlichste Unwucht im ganzen Üben-Bereich. Inhaltlich fehlten
   genau die Kapitel, an denen sich C1 von B2 unterscheidet.

   Fünf Themen kommen dazu:
     Funktionsverbgefüge          — die Sprache der Behörden und Berichte
     Der irreale Vergleich        — als ob, als wenn, als hätte
     Partikeln der Haltung        — wohl, durchaus, ohnehin, allerdings
     Partizipialattribute auflösen — der 2019 veröffentlichte Bericht
     Die feinen Konnektoren       — es sei denn, zumal, geschweige denn

   Damit hat C1 elf Themen wie B2. Aufgabentypen wie im Bestand:
   gap, choice, order. Grammatikthemen führen keine Wortkarten.
   ============================================================ */
(function () {
  var U = window.UEBUNGEN;
  if (!U || !U.skills) return;
  var sk = null;
  for (var i = 0; i < U.skills.length; i++) {
    if (U.skills[i].id === 'grammatik') sk = U.skills[i];
  }
  if (!sk || sk.__c1PlusGeladen) return;
  sk.__c1PlusGeladen = true;

  sk.themes = (sk.themes || []).concat([

  { id:'funktionsverbgefuege', title:'Funktionsverbgefüge — in Betracht ziehen, zur Verfügung stellen', level:'C1', emoji:'🏛️', words:[], exercises:[
    { type:'choice', q:'Was ist ein Funktionsverbgefüge?',
      options:['Ein Nomen trägt die Bedeutung, das Verb nur noch die Form.','Ein Verb mit zwei Vorsilben.','Ein Nebensatz ohne Konjunktion.','Ein Verb mit festem Kasus.'], answer:0,
      explain:'In „Anwendung finden" steckt die Bedeutung in Anwendung; finden ist fast leer. Deshalb heißt es Funktionsverb.' },
    { type:'choice', q:'Wo begegnet dir dieser Stil am häufigsten?',
      options:['In Behördentexten, Berichten und Fachartikeln.','In SMS unter Freunden.','In Kinderbüchern.','In Werbung.'], answer:0,
      explain:'Er wirkt sachlich und unpersönlich — genau das wollen Verwaltung und Wissenschaft.' },
    { type:'gap', text:'Die neue Regel kommt ab Januar zur ___.', answer:'Anwendung', alts:['anwendung'],
      explain:'zur Anwendung kommen = angewendet werden. Passivbedeutung ohne Passivform.' },
    { type:'gap', text:'Wir ziehen diese Möglichkeit ernsthaft in ___.', answer:'Betracht', alts:['betracht'],
      explain:'in Betracht ziehen = erwägen. Das Nomen steht ohne Artikel.' },
    { type:'gap', text:'Der Antrag wurde gestern zur Abstimmung ___.', answer:'gestellt', alts:[],
      explain:'zur Abstimmung stellen — das Funktionsverb ist stellen, nicht machen.' },
    { type:'gap', text:'Ich möchte auf Ihr Schreiben vom 2. Oktober Bezug ___.', answer:'nehmen', alts:[],
      explain:'Bezug nehmen auf + Akkusativ. „Beziehen auf" geht auch, ist aber weniger formell.' },
    { type:'gap', text:'Die Maßnahme ist am Montag in Kraft ___.', answer:'getreten', alts:[],
      explain:'in Kraft treten = gültig werden. Mit sein im Perfekt: ist in Kraft getreten.' },
    { type:'gap', text:'Diese Frage steht heute nicht zur ___.', answer:'Debatte', alts:['debatte','Diskussion','diskussion'],
      explain:'zur Debatte stehen = Gegenstand der Diskussion sein.' },
    { type:'gap', text:'Der Plan wurde schließlich in die Tat ___.', answer:'umgesetzt', alts:[],
      explain:'in die Tat umsetzen = verwirklichen. Hier trägt das Verb noch etwas Bedeutung mit.' },
    { type:'gap', text:'Wir ___ Ihnen gern Auskunft über den Stand des Verfahrens.', answer:'erteilen', alts:['geben'],
      explain:'Auskunft erteilen ist die amtliche Form; Auskunft geben ist der Alltag.' },
    { type:'gap', text:'Gegen den Bescheid wurde fristgerecht Widerspruch ___.', answer:'eingelegt', alts:[],
      explain:'Widerspruch einlegen — nicht „machen" und nicht „geben".' },
    { type:'gap', text:'Das Projekt wurde nach zwei Jahren zum ___ gebracht.', answer:'Abschluss', alts:['abschluss'],
      explain:'zum Abschluss bringen = abschließen. Beachte: bringen, nicht machen.' },
    { type:'choice', q:'Welche Verbindung ist richtig?',
      options:['eine Entscheidung treffen','eine Entscheidung machen','eine Entscheidung geben','eine Entscheidung legen'], answer:0,
      explain:'Funktionsverben sind feste Paare. Falsche Paarungen sind der häufigste Fehler auf C1.' },
    { type:'choice', q:'Welche Verbindung ist richtig?',
      options:['Kritik üben','Kritik machen','Kritik tun','Kritik setzen'], answer:0,
      explain:'Kritik übt man. Dasselbe Verb steckt in „Zurückhaltung üben".' },
    { type:'choice', q:'Welche Verbindung ist richtig?',
      options:['in Frage stellen','in Frage setzen','in Frage bringen','in Frage nehmen'], answer:0,
      explain:'etwas in Frage stellen = bezweifeln.' },
    { type:'choice', q:'„Die Regelung findet keine Anwendung." Was heißt das?',
      options:['Sie gilt hier nicht.','Sie wird gerade geschrieben.','Sie ist nicht zu finden.','Sie wird bald gelten.'], answer:0,
      explain:'Anwendung finden = angewendet werden; mit „keine" also: gilt nicht.' },
    { type:'choice', q:'Was ist der Vorteil dieses Stils in einem Bescheid?',
      options:['Er nennt keinen Handelnden.','Er ist kürzer.','Er ist leichter zu verstehen.','Er ist persönlicher.'], answer:0,
      explain:'„Der Antrag wurde zur Prüfung vorgelegt" sagt nicht, wer ihn vorgelegt hat. Das ist Absicht.' },
    { type:'choice', q:'Wie formulierst du „Wir haben entschieden" amtlich?',
      options:['Eine Entscheidung wurde getroffen.','Wir machten eine Entscheidung.','Die Entscheidung tat sich.','Man entschiedete.'], answer:0,
      explain:'Funktionsverbgefüge plus Passiv — die typische Verwaltungsform.' },
    { type:'order', answer:'Der Antrag kommt im nächsten Quartal zur Bearbeitung',
      hint:'Beginne mit „Der".',
      explain:'zur Bearbeitung kommen = bearbeitet werden. Das Gefüge steht am Satzende.' },
    { type:'order', answer:'Wir möchten diese Lösung ausdrücklich in Betracht ziehen',
      hint:'Beginne mit „Wir".',
      explain:'Bei Modalverb geht das ganze Gefüge ans Ende: in Betracht ziehen.' },
    { type:'order', answer:'Die Vereinbarung ist am ersten Januar in Kraft getreten',
      hint:'Beginne mit „Die".',
      explain:'Perfekt mit sein, weil treten eine Zustandsänderung ist.' },
    { type:'order', answer:'Ich nehme Bezug auf unser Gespräch vom Montag',
      hint:'Beginne mit „Ich".',
      explain:'Bezug nehmen auf + Akkusativ. In E-Mails der klassische erste Satz.' },
    { type:'choice', q:'Was unterscheidet „Er entschied" von „Er traf eine Entscheidung"?',
      options:['Nur der Stil — die zweite Form klingt formeller und schwerer.','Die Bedeutung ist völlig anders.','Die zweite Form ist falsch.','Die erste ist formeller.'], answer:0,
      explain:'Inhaltlich dasselbe. Auf C1 musst du beides verstehen und bewusst wählen können.' },
    { type:'choice', q:'Welcher Satz ist stilistisch unnötig schwer?',
      options:['Wir bringen Ihr Anliegen zur Kenntnisnahme.','Wir nehmen Ihr Anliegen zur Kenntnis.','Wir haben Ihr Anliegen gelesen.','Wir kennen Ihr Anliegen.'], answer:0,
      explain:'„zur Kenntnisnahme bringen" verdoppelt das Nomen. Gute Verwaltungssprache macht das nicht.' },
    { type:'gap', text:'Ihr Einwand wurde zur ___ genommen.', answer:'Kenntnis', alts:['kenntnis'],
      explain:'zur Kenntnis nehmen = zur Kenntnis bekommen, registrieren.' }
  ]},

  { id:'irreale-vergleiche', title:'als ob, als wenn — irreale Vergleiche', level:'C1', emoji:'🎭', words:[], exercises:[
    { type:'choice', q:'Was drückt „als ob" aus?',
      options:['Einen Vergleich mit etwas, das nicht der Fall ist.','Eine Bedingung.','Einen Grund.','Eine Zeit.'], answer:0,
      explain:'Der Vergleich ist irreal: Es sieht so aus, ist aber nicht so.' },
    { type:'choice', q:'Welcher Modus steht nach „als ob"?',
      options:['Konjunktiv II (manchmal auch I).','Immer Indikativ.','Immer Imperativ.','Immer Futur.'], answer:0,
      explain:'Weil es nicht wirklich so ist, steht der Konjunktiv. Indikativ wirkt umgangssprachlich.' },
    { type:'gap', text:'Er tut so, als ob er mich nicht ___.', answer:'kennen würde', alts:['kennte','kenne'],
      explain:'Beides geht: „kennen würde" (gesprochen) oder „kennte" (geschrieben).' },
    { type:'gap', text:'Sie sieht aus, als ___ sie die ganze Nacht gearbeitet.', answer:'hätte', alts:[],
      explain:'Ohne „ob" rückt das Verb direkt hinter „als": als hätte sie …' },
    { type:'gap', text:'Es klingt, als ___ er sich nicht ganz sicher.', answer:'wäre', alts:['sei'],
      explain:'als wäre: irrealer Vergleich. „als sei" ist die etwas förmlichere Variante.' },
    { type:'gap', text:'Er redet, als ob er alles besser ___.', answer:'wüsste', alts:['wisse'],
      explain:'Konjunktiv II von wissen: wüsste.' },
    { type:'gap', text:'Mir ist, als ___ ich das schon einmal gehört.', answer:'hätte', alts:[],
      explain:'„Mir ist, als hätte ich …" — feste Wendung für ein vages Gefühl.' },
    { type:'choice', q:'Welcher Satz ist richtig?',
      options:['Er tut, als wäre nichts passiert.','Er tut, als ob wäre nichts passiert.','Er tut, als nichts passiert wäre.','Er tut, als ob nichts passiert.'], answer:0,
      explain:'Ohne „ob" steht das Verb direkt nach „als". Mit „ob" geht es ans Ende.' },
    { type:'choice', q:'Welcher Satz ist richtig?',
      options:['Sie sah mich an, als ob sie mich prüfen wollte.','Sie sah mich an, als ob wollte sie mich prüfen.','Sie sah mich an, als sie mich prüfen wollte.','Sie sah mich an, ob sie mich prüfen wollte.'], answer:0,
      explain:'Mit „ob" ist es ein normaler Nebensatz: Verb ans Ende.' },
    { type:'choice', q:'Was bedeutet „Er tut nur so, als ob"?',
      options:['Er spielt etwas vor.','Er ist unsicher.','Er hat recht.','Er fragt nach.'], answer:0,
      explain:'Die elliptische Form „als ob" am Satzende ist umgangssprachlich sehr verbreitet.' },
    { type:'gap', text:'Du siehst aus, als ___ du einen Geist gesehen.', answer:'hättest', alts:[],
      explain:'Zweite Person: als hättest du …' },
    { type:'gap', text:'Es war, als ___ die Zeit stehen geblieben.', answer:'wäre', alts:[],
      explain:'bleiben bildet das Perfekt mit sein, also im Konjunktiv II: wäre … geblieben.' },
    { type:'choice', q:'Was ist der Unterschied zwischen „als ob" und „als wenn"?',
      options:['Praktisch keiner; „als wenn" ist etwas umgangssprachlicher.','„als wenn" ist falsch.','„als wenn" ist förmlicher.','„als wenn" braucht den Indikativ.'], answer:0,
      explain:'Beide sind korrekt. Im geschriebenen Deutsch überwiegt „als ob".' },
    { type:'choice', q:'„Es ist nicht so, als hätte ich ihn nicht gewarnt." Was heißt das?',
      options:['Ich habe ihn sehr wohl gewarnt.','Ich habe ihn nicht gewarnt.','Ich warne ihn gerade.','Ich werde ihn warnen.'], answer:0,
      explain:'Doppelte Verneinung mit irrealem Vergleich — auf C1 eine beliebte Stolperstelle.' },
    { type:'order', answer:'Er benimmt sich so als ob ihm der Laden gehören würde',
      hint:'Beginne mit „Er".',
      explain:'Mit „als ob" steht das Verb am Ende des Nebensatzes.' },
    { type:'order', answer:'Sie lächelte als hätte sie den Witz nicht verstanden',
      hint:'Beginne mit „Sie".',
      explain:'Ohne „ob" folgt das Verb direkt auf „als".' },
    { type:'order', answer:'Mir kam es vor als wäre die Besprechung endlos',
      hint:'Beginne mit „Mir".',
      explain:'„Mir kam es vor, als wäre …" — häufige Wendung für einen subjektiven Eindruck.' },
    { type:'gap', text:'Er sprach so leise, ___ ob er Angst hätte, gehört zu werden.', answer:'als', alts:[],
      explain:'Die Verbindung ist immer „als ob", nie „wie ob".' },
    { type:'choice', q:'Welche Form ist im geschriebenen Deutsch eleganter?',
      options:['als käme sie gerade von einer Reise','als ob sie gerade von einer Reise kommen würde','als wenn sie gerade kommt','wie wenn sie gerade kommen würde'], answer:0,
      explain:'Die Form ohne „ob" mit Konjunktiv II ist knapper und gilt als gehobener.' },
    { type:'gap', text:'Sie behandelt ihn, als ___ er ein Kind.', answer:'wäre', alts:['sei'],
      explain:'Ohne „ob", also Verb direkt nach „als".' },
    { type:'choice', q:'Welcher Satz ist umgangssprachlich, aber nicht standardsprachlich?',
      options:['Er tut so, als ob er nichts weiß.','Er tut so, als ob er nichts wüsste.','Er tut so, als wüsste er nichts.','Er tut so, als ob er nichts wissen würde.'], answer:0,
      explain:'Indikativ nach „als ob" hört man oft, in der Prüfung kostet er Punkte.' },
    { type:'gap', text:'Der Raum war so still, als ___ niemand da.', answer:'wäre', alts:[],
      explain:'als wäre niemand da — der irreale Vergleich beschreibt den Eindruck.' },
    { type:'order', answer:'Es sieht fast so aus als hätten wir uns geirrt',
      hint:'Beginne mit „Es".',
      explain:'„Es sieht so aus, als …" leitet eine vorsichtige Vermutung ein.' },
    { type:'choice', q:'Wann benutzt man diese Form im Alltag besonders oft?',
      options:['Wenn man höflich andeutet, dass jemand etwas vortäuscht.','Wenn man etwas befiehlt.','Wenn man etwas zählt.','Wenn man sich bedankt.'], answer:0,
      explain:'„Du tust ja gerade so, als ob …" ist ein höflicher, aber deutlicher Vorwurf.' }
  ]},

  { id:'partikeln-c1', title:'wohl, durchaus, ohnehin — die Haltung im Nebenwort', level:'C1', emoji:'🎚️', words:[], exercises:[
    { type:'choice', q:'Was leisten Partikeln wie „wohl" oder „durchaus"?',
      options:['Sie zeigen die Haltung des Sprechers zum Gesagten.','Sie ändern die Zeitform.','Sie verneinen den Satz.','Sie bilden Fragen.'], answer:0,
      explain:'Der Sachverhalt bleibt gleich; was sich ändert, ist die Färbung.' },
    { type:'choice', q:'„Er wird wohl zu Hause sein." Was drückt „wohl" aus?',
      options:['Eine begründete Vermutung.','Eine Gewissheit.','Einen Wunsch.','Eine Bitte.'], answer:0,
      explain:'„wohl" ist die höfliche Form der Vermutung — stärker als „vielleicht", schwächer als „bestimmt".' },
    { type:'choice', q:'„Das ist durchaus möglich." Was heißt „durchaus" hier?',
      options:['Sehr wohl, ohne Einschränkung.','Kaum.','Nur manchmal.','Gar nicht.'], answer:0,
      explain:'„durchaus" bekräftigt. In der Verneinung kehrt es sich um: „durchaus nicht" = keineswegs.' },
    { type:'choice', q:'„Das war ohnehin geplant." Was heißt „ohnehin"?',
      options:['So oder so, unabhängig davon.','Nur deshalb.','Leider.','Zum ersten Mal.'], answer:0,
      explain:'„ohnehin" (auch: sowieso) sagt, dass das Argument keine Rolle gespielt hat.' },
    { type:'choice', q:'„Ich habe allerdings Bedenken." Was tut „allerdings"?',
      options:['Es schränkt das vorher Gesagte ein.','Es stimmt uneingeschränkt zu.','Es fragt nach.','Es erklärt einen Grund.'], answer:0,
      explain:'„allerdings" ist das höfliche Scharnier zwischen Zustimmung und Einwand.' },
    { type:'choice', q:'„Das ist eben so." Was macht „eben"?',
      options:['Es stellt etwas als unabänderlich hin.','Es betont die Zeit.','Es fragt nach dem Grund.','Es drückt Freude aus.'], answer:0,
      explain:'„eben" und „halt" schließen die Diskussion — manchmal etwas zu schnell.' },
    { type:'choice', q:'„Er ist ja Arzt." Warum steht hier „ja"?',
      options:['Der Sprecher setzt die Information als bekannt voraus.','Er bejaht eine Frage.','Er ist überrascht.','Er widerspricht.'], answer:0,
      explain:'„ja" im Satzinneren heißt: Das weißt du doch längst.' },
    { type:'choice', q:'„Das war immerhin ein Anfang." Was leistet „immerhin"?',
      options:['Es wertet etwas Kleines positiv auf.','Es kritisiert scharf.','Es verneint.','Es fragt nach.'], answer:0,
      explain:'„immerhin" rettet den Rest: wenig, aber besser als nichts.' },
    { type:'choice', q:'„Er hat zwar zugesagt, kommt aber nicht." Welche Rolle hat „zwar"?',
      options:['Es kündigt eine Einschränkung an.','Es verstärkt.','Es verneint.','Es fragt.'], answer:0,
      explain:'„zwar" ist immer ein Versprechen auf ein „aber" im nächsten Teil.' },
    { type:'gap', text:'Er wird ___ im Stau stehen, anders kann ich mir die Verspätung nicht erklären.', answer:'wohl', alts:[],
      explain:'Begründete Vermutung — genau das Feld von „wohl".' },
    { type:'gap', text:'Dieser Einwand ist ___ berechtigt, nur ändert er am Ergebnis nichts.', answer:'durchaus', alts:['zwar'],
      explain:'„durchaus berechtigt" räumt ein, bevor der Einwand entkräftet wird.' },
    { type:'gap', text:'Wir hätten den Termin ___ verschieben müssen, der Raum war gar nicht frei.', answer:'ohnehin', alts:['sowieso'],
      explain:'„ohnehin" entwertet das vorherige Argument: Es wäre so oder so passiert.' },
    { type:'gap', text:'Die Zahlen stimmen. ___ bleibt die Frage, wie belastbar sie sind.', answer:'Allerdings', alts:['allerdings'],
      explain:'Am Satzanfang leitet „allerdings" den Einwand ein — Verb folgt direkt.' },
    { type:'gap', text:'Du kennst ihn ___, dann weißt du ja, wie er ist.', answer:'ja', alts:['doch'],
      explain:'„ja" und „doch" setzen gemeinsames Wissen voraus.' },
    { type:'gap', text:'Das Ergebnis ist ___ nicht zufriedenstellend.', answer:'keineswegs', alts:['durchaus'],
      explain:'Mit „durchaus nicht" oder „keineswegs" wird die Verneinung deutlich verstärkt.' },
    { type:'choice', q:'Wo steht die Partikel im Satz normalerweise?',
      options:['Im Mittelfeld, nach dem Verb und vor der neuen Information.','Immer am Satzanfang.','Immer am Satzende.','Direkt vor dem Subjekt.'], answer:0,
      explain:'„Er wird wohl zu Hause sein." Die Partikel sitzt im Mittelfeld — nicht vorn, nicht hinten.' },
    { type:'choice', q:'Welche Partikel passt in eine formelle E-Mail?',
      options:['allerdings','halt','eben','ja'], answer:0,
      explain:'halt, eben und ja sind gesprochene Sprache. „allerdings" steht auch im Schriftlichen.' },
    { type:'choice', q:'Was unterscheidet „Er kommt nicht" von „Er kommt wohl nicht"?',
      options:['Die zweite Aussage ist eine Vermutung, keine Feststellung.','Nichts.','Die zweite ist stärker.','Die zweite ist eine Frage.'], answer:0,
      explain:'Eine einzige Partikel verwandelt eine Behauptung in eine Annahme. Das ist der Grund, sie zu lernen.' },
    { type:'order', answer:'Der Zug hat ohnehin Verspätung also können wir in Ruhe einen Kaffee trinken',
      hint:'Beginne mit „Der".',
      explain:'„ohnehin" steht im Mittelfeld, direkt vor der eigentlichen Information.' },
    { type:'order', answer:'Ihr Vorschlag ist durchaus bedenkenswert erscheint mir aber zu teuer',
      hint:'Beginne mit „Ihr".',
      explain:'Zustimmung mit „durchaus", Einschränkung mit „aber" — die klassische C1-Bewegung.' },
    { type:'order', answer:'Sie wird wohl noch im Büro sein das Licht brennt ja',
      hint:'Beginne mit „Sie".',
      explain:'Zwei Partikeln in einem Zug: „wohl" vermutet, „ja" liefert den bekannten Beleg.' },
    { type:'choice', q:'„Das war ja klar!" Was schwingt mit?',
      options:['Der Sprecher hat es erwartet, oft mit Ärger.','Freude über eine Überraschung.','Eine höfliche Frage.','Eine Entschuldigung.'], answer:0,
      explain:'Betontes „ja" am Satzanfang drückt genau diese Resignation aus.' },
    { type:'choice', q:'Welche Partikel schwächt eine Bitte ab?',
      options:['mal — „Kannst du mal kurz helfen?"','durchaus','ohnehin','keineswegs'], answer:0,
      explain:'„mal" macht aus einer Aufforderung eine beiläufige Bitte.' },
    { type:'gap', text:'Ich habe ___ zugesagt, aber die Bedingungen kannte ich damals nicht.', answer:'zwar', alts:[],
      explain:'„zwar … aber" ist das feste Paar der Einräumung.' }
  ]},

  { id:'attribute-umformen-c1', title:'Attribute auflösen und zusammenziehen — hin und zurück', level:'C1', emoji:'📑', words:[], exercises:[
    { type:'choice', q:'Was ist ein erweitertes Partizipialattribut?',
      options:['Ein ganzer Nebensatz, zusammengezogen vor das Nomen.','Ein Nebensatz mit dass.','Ein Relativsatz nach dem Nomen.','Ein Adjektiv ohne Endung.'], answer:0,
      explain:'„der im Jahr 2019 veröffentlichte Bericht" steht für „der Bericht, der 2019 veröffentlicht wurde".' },
    { type:'choice', q:'Woran erkennst du es beim Lesen?',
      options:['Zwischen Artikel und Nomen steht mehr als ein Wort.','Am Komma.','Am Fragezeichen.','An der Vorsilbe.'], answer:0,
      explain:'Sobald nach „der" nicht gleich das Nomen kommt, ist ein Attribut im Weg.' },
    { type:'choice', q:'„die steigenden Kosten" — welches Partizip ist das?',
      options:['Partizip I, aktive Bedeutung: die Kosten steigen.','Partizip II, passive Bedeutung.','Infinitiv.','Konjunktiv.'], answer:0,
      explain:'Partizip I auf -end ist immer aktiv und gleichzeitig.' },
    { type:'choice', q:'„die gestiegenen Kosten" — was heißt das?',
      options:['Die Kosten sind gestiegen, es ist abgeschlossen.','Die Kosten steigen gerade.','Die Kosten werden steigen.','Die Kosten sollen steigen.'], answer:0,
      explain:'Partizip II ist abgeschlossen; bei sein-Verben bleibt die Bedeutung aktiv.' },
    { type:'choice', q:'„der zu prüfende Antrag" — was steckt dahinter?',
      options:['Der Antrag, der geprüft werden muss.','Der Antrag, der geprüft wurde.','Der Antrag, der prüft.','Der Antrag, der geprüft werden kann.'], answer:0,
      explain:'zu + Partizip I trägt die Bedeutung von müssen oder können im Passiv.' },
    { type:'gap', text:'Auflösen: der von der Kommission geprüfte Antrag → der Antrag, der von der Kommission geprüft ___ .', answer:'wurde', alts:['worden ist'],
      explain:'Partizip II ohne sein-Verb wird zum Vorgangspassiv.' },
    { type:'gap', text:'Auflösen: die wachsende Nachfrage → die Nachfrage, die ___ .', answer:'wächst', alts:['waechst'],
      explain:'Partizip I wird zum aktiven Verb in derselben Zeit.' },
    { type:'gap', text:'Auflösen: die zu erledigenden Aufgaben → die Aufgaben, die erledigt werden ___ .', answer:'müssen', alts:['sollen'],
      explain:'zu + Partizip I = Notwendigkeit, im Passiv.' },
    { type:'gap', text:'Auflösen: der seit Jahren leerstehende Bau → der Bau, der seit Jahren leer ___ .', answer:'steht', alts:[],
      explain:'leerstehen ist trennbar: der Bau steht leer.' },
    { type:'gap', text:'Zusammenziehen: die Studie, die im letzten Jahr erschienen ist → die im letzten Jahr ___ Studie.', answer:'erschienene', alts:[],
      explain:'erscheinen bildet das Perfekt mit sein — das Partizip bleibt aktiv.' },
    { type:'gap', text:'Zusammenziehen: die Zahlen, die vom Amt erhoben wurden → die vom Amt ___ Zahlen.', answer:'erhobenen', alts:[],
      explain:'Plural nach bestimmtem Artikel: Endung -en.' },
    { type:'choice', q:'Welche Auflösung ist richtig? „die in Berlin lebende Autorin"',
      options:['die Autorin, die in Berlin lebt','die Autorin, die in Berlin gelebt wird','die Autorin, die in Berlin gelebt hat','die Autorin, die Berlin lebt'], answer:0,
      explain:'Partizip I, aktiv und gleichzeitig.' },
    { type:'choice', q:'Welche Auflösung ist richtig? „das vom Vorstand beschlossene Vorgehen"',
      options:['das Vorgehen, das der Vorstand beschlossen hat','das Vorgehen, das der Vorstand beschließt','das Vorgehen, das beschließen wird','das Vorgehen, das der Vorstand beschließen will'], answer:0,
      explain:'Partizip II mit „von" zeigt den Handelnden; im Aktivsatz wird er zum Subjekt.' },
    { type:'choice', q:'Warum benutzt die Fachsprache diese Form so gern?',
      options:['Sie packt viel Information knapp vor das Nomen.','Sie klingt freundlicher.','Sie ist leichter zu lesen.','Sie vermeidet Fehler.'], answer:0,
      explain:'Knapp ja, leicht nein — deshalb ist das Auflösen eine eigene Fertigkeit.' },
    { type:'choice', q:'Welcher Satz ist korrekt gebildet?',
      options:['Die vom Ministerium im Mai vorgelegten Zahlen wurden korrigiert.','Die vom Ministerium im Mai vorlegenden Zahlen wurden korrigiert.','Die zu vorlegenden vom Ministerium Zahlen wurden korrigiert.','Die Zahlen vorgelegten wurden korrigiert.'], answer:0,
      explain:'Partizip II, weil die Zahlen vorgelegt wurden — nicht selbst vorlegen.' },
    { type:'order', answer:'Der im vergangenen Jahr eingereichte Antrag wurde inzwischen bewilligt',
      hint:'Beginne mit „Der".',
      explain:'Zwischen Artikel und Nomen steht das ganze Attribut: im vergangenen Jahr eingereichte.' },
    { type:'order', answer:'Die noch zu klärenden Fragen stehen in der Anlage',
      hint:'Beginne mit „Die".',
      explain:'zu + Partizip I mit Adverb davor: noch zu klärende.' },
    { type:'order', answer:'Wir beziehen uns auf die am Montag von Ihnen übersandten Unterlagen',
      hint:'Beginne mit „Wir".',
      explain:'Zeit, dann Handelnder, dann Partizip — in dieser Reihenfolge im Attribut.' },
    { type:'gap', text:'Auflösen: die im Protokoll festgehaltenen Beschlüsse → die Beschlüsse, die im Protokoll festgehalten ___ .', answer:'wurden', alts:['worden sind'],
      explain:'Vorgangspassiv in der Vergangenheit.' },
    { type:'gap', text:'Zusammenziehen: die Kinder, die auf dem Hof spielen → die auf dem Hof ___ Kinder.', answer:'spielenden', alts:[],
      explain:'Partizip I plus Pluralendung -en nach bestimmtem Artikel.' },
    { type:'choice', q:'Was ist beim Sprechen besser?',
      options:['Den Relativsatz, weil der Hörer sonst den Faden verliert.','Immer das Attribut.','Beides gleich gut.','Keines von beiden.'], answer:0,
      explain:'Beim Hören fehlt die Möglichkeit zurückzuspringen. Gute Redner lösen deshalb auf.' },
    { type:'choice', q:'„die zu erwartenden Folgen" — welche Bedeutung?',
      options:['Folgen, die man erwarten kann.','Folgen, die erwartet haben.','Folgen, die erwarten.','Folgen, die erwartet wurden.'], answer:0,
      explain:'Hier trägt zu + Partizip I die Bedeutung von können, nicht von müssen. Der Kontext entscheidet.' },
    { type:'gap', text:'Die ___ Daten stammen aus dem Jahr 2024. (erheben, Partizip II)', answer:'erhobenen', alts:[],
      explain:'erheben → erhoben, mit Pluralendung -en.' },
    { type:'choice', q:'Welcher Fehler ist hier: „die geprüfende Akte"?',
      options:['Es muss „zu prüfende" oder „geprüfte" heißen.','Es fehlt ein Komma.','Der Artikel ist falsch.','Es muss Plural sein.'], answer:0,
      explain:'„geprüfend" gibt es nicht — entweder Partizip II (geprüfte) oder zu + Partizip I (zu prüfende).' }
  ]},

  { id:'feine-konnektoren-c1', title:'es sei denn, zumal, geschweige denn', level:'C1', emoji:'🔗', words:[], exercises:[
    { type:'choice', q:'„Wir fahren morgen, es sei denn, es schneit." Was bedeutet „es sei denn"?',
      options:['Außer wenn — die einzige Ausnahme.','Weil.','Obwohl.','Sobald.'], answer:0,
      explain:'„es sei denn" nennt die eine Bedingung, unter der das Gesagte nicht gilt.' },
    { type:'choice', q:'Welche Satzstellung folgt nach „es sei denn"?',
      options:['Hauptsatzstellung: Verb an zweiter Stelle.','Verb am Ende.','Verb am Anfang.','Kein Verb.'], answer:0,
      explain:'„es sei denn, es schneit" — kein Nebensatz, deshalb keine Endstellung.' },
    { type:'choice', q:'„Er kommt nicht, zumal er ohnehin keine Zeit hat." Was tut „zumal"?',
      options:['Es liefert einen zusätzlichen, verstärkenden Grund.','Es nennt einen Gegensatz.','Es stellt eine Bedingung.','Es nennt eine Folge.'], answer:0,
      explain:'„zumal" heißt: und obendrein. Es verstärkt einen schon genannten Grund.' },
    { type:'choice', q:'Welche Satzstellung folgt auf „zumal"?',
      options:['Nebensatzstellung: Verb ans Ende.','Verb an zweiter Stelle.','Verb am Anfang.','Beliebig.'], answer:0,
      explain:'„zumal er keine Zeit hat" — Verb am Ende.' },
    { type:'choice', q:'„Er kann nicht lesen, geschweige denn schreiben." Was heißt das?',
      options:['Lesen kann er nicht, schreiben erst recht nicht.','Er kann beides.','Er kann nur schreiben.','Er lernt gerade beides.'], answer:0,
      explain:'„geschweige denn" steigert eine Verneinung. Es steht fast nur nach einer Negation.' },
    { type:'choice', q:'„Sofern keine Einwände bestehen, verfahren wir so." Was heißt „sofern"?',
      options:['Unter der Bedingung, dass.','Obwohl.','Nachdem.','Damit.'], answer:0,
      explain:'„sofern" ist das förmliche „wenn" und sehr häufig in Schreiben von Behörden.' },
    { type:'choice', q:'„Er hat zugesagt, insofern ist die Sache geklärt." Was leistet „insofern"?',
      options:['Es zieht eine Folgerung aus dem Vorangegangenen.','Es nennt eine Bedingung.','Es verneint.','Es fragt nach.'], answer:0,
      explain:'„insofern" = in dieser Hinsicht, also deshalb. Verb folgt direkt.' },
    { type:'gap', text:'Wir beginnen pünktlich, ___ sei denn, der Zug hat Verspätung.', answer:'es', alts:[],
      explain:'Die Wendung lautet immer „es sei denn" — unveränderlich.' },
    { type:'gap', text:'Der Vorschlag überzeugt, ___ er auch noch günstiger ist.', answer:'zumal', alts:[],
      explain:'Ein zweiter Grund, der den ersten verstärkt.' },
    { type:'gap', text:'Ich habe ihn nie getroffen, ___ denn gesprochen.', answer:'geschweige', alts:[],
      explain:'Steigerung nach einer Verneinung: treffen nein, sprechen erst recht nicht.' },
    { type:'gap', text:'___ Sie Fragen haben, melden Sie sich gern.', answer:'Sofern', alts:['sofern','Falls','falls'],
      explain:'„Sofern" und „falls" sind beide möglich; sofern klingt förmlicher.' },
    { type:'gap', text:'Die Frist ist abgelaufen, ___ ist der Antrag abzulehnen.', answer:'insofern', alts:['folglich','mithin'],
      explain:'Folgerung aus dem eben Gesagten.' },
    { type:'choice', q:'Welcher Satz ist richtig?',
      options:['Wir kommen, es sei denn, wir hören etwas anderes.','Wir kommen, es sei denn, wir etwas anderes hören.','Wir kommen, es sei denn, hören wir etwas anderes.','Wir kommen, es sei denn, dass wir hören etwas anderes.'], answer:0,
      explain:'Hauptsatzstellung nach „es sei denn". Mit „dass" ginge auch: es sei denn, dass wir etwas anderes hören.' },
    { type:'choice', q:'Welcher Satz ist richtig?',
      options:['Der Termin passt gut, zumal ich ohnehin in der Stadt bin.','Der Termin passt gut, zumal bin ich ohnehin in der Stadt.','Der Termin passt gut, zumal ich bin ohnehin in der Stadt.','Zumal ich ohnehin in der Stadt, passt der Termin gut.'], answer:0,
      explain:'Nach „zumal" Nebensatzstellung: Verb ganz hinten.' },
    { type:'choice', q:'„Er hat kein Geld, geschweige denn ___." Was passt?',
      options:['eine Wohnung','hat er eine Wohnung','dass er eine Wohnung hat','eine Wohnung hat er'], answer:0,
      explain:'Nach „geschweige denn" steht meist nur das verkürzte Satzglied, kein ganzer Satz.' },
    { type:'choice', q:'Welche Verbindung drückt einen Gegensatz aus, der trotzdem bestehen bleibt?',
      options:['wenngleich','sofern','zumal','insofern'], answer:0,
      explain:'„wenngleich" ist das gehobene „obwohl" und steht oft in Gutachten und Essays.' },
    { type:'gap', text:'Der Befund ist eindeutig, ___ die Datenbasis klein ist.', answer:'wenngleich', alts:['obwohl','obgleich'],
      explain:'Einräumung im gehobenen Stil. Verb am Ende.' },
    { type:'order', answer:'Wir halten an dem Termin fest es sei denn Sie melden sich bis Freitag',
      hint:'Beginne mit „Wir".',
      explain:'Nach „es sei denn" normale Hauptsatzstellung: Sie melden sich.' },
    { type:'order', answer:'Der Vorschlag verdient Zustimmung zumal er ohne Mehrkosten auskommt',
      hint:'Beginne mit „Der".',
      explain:'Nach „zumal" rutscht auskommt ans Ende.' },
    { type:'order', answer:'Sie hat sich nicht entschuldigt geschweige denn den Schaden ersetzt',
      hint:'Beginne mit „Sie".',
      explain:'Die Steigerung schließt direkt an die Verneinung an.' },
    { type:'order', answer:'Sofern keine Einwände vorliegen verfahren wir wie besprochen',
      hint:'Beginne mit „Sofern".',
      explain:'Steht der Nebensatz vorn, folgt im Hauptsatz sofort das Verb: verfahren wir.' },
    { type:'choice', q:'Welche dieser Verbindungen gehört NICHT in eine formelle E-Mail?',
      options:['und so weiter halt','sofern','insofern','wenngleich'], answer:0,
      explain:'„halt" ist gesprochene Sprache. Die anderen drei sind Schriftdeutsch.' },
    { type:'gap', text:'Eine Lösung ist nicht in Sicht, ___ die Beteiligten gar nicht miteinander reden.', answer:'zumal', alts:['da','weil'],
      explain:'„zumal" passt, weil ein verstärkender Zusatzgrund folgt.' },
    { type:'choice', q:'„Es sei denn" steht fast immer …',
      options:['nach einer positiven Aussage, als einzige Ausnahme.','am Satzanfang.','nach einer Frage.','nach einer Verneinung.'], answer:0,
      explain:'Die Hauptaussage gilt — außer in diesem einen Fall.' }
  ]}

  ]);
})();
