/* ============================================================
   deutschoderwas club — HÖREN A2 (Goethe-Zertifikat A2)

   Schwesterdatei zu hoeren-a1.js, gleicher Aufbau, gleiche Optik.
   Wer den A1-Teil kennt, findet sich hier sofort zurecht.

   Das Prüfungsformat A2: vier Teile, 20 Aufgaben, 30 Minuten.

     Teil 1  Fünf kurze Gespräche im Alltag           · zweimal hören
     Teil 2  Fünf Durchsagen, richtig oder falsch     · einmal hören
     Teil 3  Fünf Nachrichten auf dem Anrufbeantworter · einmal hören
     Teil 4  Fünf Meinungen im Radio                  · zweimal hören

   Der Unterschied zu A1 ist nicht die Geschwindigkeit, sondern die
   Genauigkeit. Auf A1 heißt es „um acht", auf A2 „Viertel vor acht".
   Nicht 20 Euro, sondern 19,90. Und fast jeder Text nennt zuerst den
   Plan und danach die Änderung.

   Jede Aufgabe trägt die Fundstelle im Text (stelle) und eine
   Erklärung, die sagt, WORAN man es hört — nicht nur, was richtig ist.
   Nach dem Antworten wird der Text eingeblendet, die Stelle markiert.

   Wichtig für alle, die hier später weiterschreiben:
     · stelle muss wörtlich im Text stehen, sonst gibt es keine Markierung
     · loesung darf nicht immer 0 sein — die Position wechselt bewusst
     · bei Durchsagen (Teil 2) gilt mal:1, auch im Training
   ============================================================ */
window.HOEREN_A2 = {
  niveau: 'A2',
  pruefung: 'Goethe-Zertifikat A2',
  minuten: 30,
  punkte: 20,

  stufen: [
    { nr:1, titel:'Zahlen, Zeiten und Preise', zeichen:'🔢',
      was:'Auf A2 wird es genauer als auf A1. Nicht mehr „um acht", sondern „Viertel vor acht". Nicht 20 Euro, sondern neunzehn Euro neunzig. Genau diese Feinheiten entscheiden über den Punkt.' },
    { nr:2, titel:'Das Wort, das alles ändert', zeichen:'🔄',
      was:'Fast jeder Hörtext nennt zuerst den Plan und dann die Änderung. Wer nur den Anfang hört, kreuzt falsch an. Warte auf leider, statt, sondern, erst, ausnahmsweise, stattdessen.' },
    { nr:3, titel:'Die vier Aufgabentypen', zeichen:'🎧',
      was:'Jetzt echte Prüfungsaufgaben, einzeln und in Ruhe. Gespräche und Radio-Meinungen hörst du zweimal, Durchsagen und Anrufbeantworter nur einmal — genau wie in der Prüfung.' },
    { nr:4, titel:'Die ganze Prüfung', zeichen:'⏱️',
      was:'20 Aufgaben, 30 Minuten, keine Rückmeldung zwischendurch. So wie am Prüfungstag.' }
  ],

  bloecke: [

    { id:'a2b1', stufe:1, titel:'Zahlen, Preise, Mengen', kurz:'Euro, Nummern, Stückzahlen',
      ziel:'Nach diesem Block hörst du 19,90 und 90,19 sofort auseinander.',
      zeichen:'🔢', farbe:'turq',
      aufgaben:[
        { art:'hoerwahl', wer:'Mann', text:'Das macht dann neunzehn Euro neunzig, bitte.',
          frage:'Was kostet es?', opt:['19,90 €','90,19 €','19,19 €'], loesung:0,
          stelle:'neunzehn Euro neunzig',
          erklaerung:'Zuerst kommen die Euro, dann die Cent: neunzehn Euro und neunzig Cent. Die Reihenfolge ist immer gleich — der erste Betrag sind die Euro.' },
        { art:'hoerwahl', wer:'Frau', text:'Ihr Zimmer ist die dreihundertvierzehn, im dritten Stock rechts.',
          frage:'Welche Zimmernummer hat der Gast?', opt:['Zimmer 314','Zimmer 340','Zimmer 3'], loesung:0,
          stelle:'die dreihundertvierzehn',
          erklaerung:'Dreihundertvierzehn ist 314. Bei 340 würdest du dreihundertvierzig hören — ohne das und dazwischen.' },
        { art:'hoerwahl', wer:'Mann', text:'Sie erreichen mich unter null eins sieben sechs, vierundzwanzig, achtzehn, neunzig.',
          frage:'Wie lautet die Nummer?', opt:['0176 42 81 90','0176 24 81 09','0176 24 18 90'], loesung:2,
          stelle:'vierundzwanzig, achtzehn, neunzig',
          erklaerung:'Vierundzwanzig ist 24, achtzehn ist 18. Im Deutschen kommt bei zwei Ziffern die Einerzahl zuerst — hör auf das und in der Mitte.' },
        { art:'hoerwahl', wer:'Frau', text:'Die Wohnung kostet sechshundertfünfzig Euro kalt, dazu kommen hundertzwanzig Euro Nebenkosten.',
          frage:'Wie viel kostet die Wohnung warm?', opt:['650 €','770 €','120 €'], loesung:1,
          stelle:'dazu kommen hundertzwanzig Euro Nebenkosten',
          erklaerung:'Warm heißt: Kaltmiete plus Nebenkosten. 650 und 120 zusammen sind 770 Euro. Bei dazu kommen musst du rechnen.' },
        { art:'hoerwahl', wer:'Mann', text:'Wir wohnen in der Gartenstraße siebenundsechzig, direkt neben der Apotheke.',
          frage:'Welche Hausnummer ist es?', opt:['Nummer 67','Nummer 76','Nummer 60'], loesung:0,
          stelle:'siebenundsechzig',
          erklaerung:'Siebenundsechzig ist 67: erst sieben, dann sechzig. Sechsundsiebzig wäre 76 — genau umgekehrt.' },
        { art:'hoerwahl', wer:'Frau', text:'Ich nehme zwei Kilo Kartoffeln, ein Kilo Tomaten und drei Zitronen.',
          frage:'Wie viele Tomaten kauft die Frau?', opt:['Zwei Kilo','Drei Kilo','Ein Kilo'], loesung:2,
          stelle:'ein Kilo Tomaten',
          erklaerung:'Drei Mengen hintereinander — gefragt ist nur eine. Merk dir beim Hören das Wort Tomaten und nimm die Zahl direkt davor.' },
        { art:'hoerwahl', wer:'Mann', text:'Die Jacke hat vorher vierzig Euro gekostet, im Angebot bekommen Sie sie für neunundzwanzig fünfzig.',
          frage:'Was kostet die Jacke jetzt?', opt:['40 €','29,50 €','25,90 €'], loesung:1,
          stelle:'für neunundzwanzig fünfzig',
          erklaerung:'Vorher nennt den alten Preis. Der Preis nach im Angebot gilt jetzt: 29,50 Euro.' },
        { art:'hoerwahl', wer:'Frau', text:'Der Kurs kostet hundertachtzig Euro. Sie können auch in drei Raten zu je sechzig Euro zahlen.',
          frage:'Wie viel zahlt man pro Rate?', opt:['180 €','3 €','60 €'], loesung:2,
          stelle:'in drei Raten zu je sechzig Euro',
          erklaerung:'Je heißt: jedes Mal so viel. Hundertachtzig ist der ganze Kurs, sechzig ist eine Rate.' },
        { art:'hoerwahl', wer:'Mann', text:'Der Regionalzug nach Ulm fährt heute nicht von Gleis zwei, sondern von Gleis zwölf.',
          frage:'Von welchem Gleis fährt der Zug?', opt:['Von Gleis 12','Von Gleis 2','Von Gleis 20'], loesung:0,
          stelle:'sondern von Gleis zwölf',
          erklaerung:'Zwei und zwölf klingen ähnlich. Die Zahl nach sondern ist die richtige — das erste Gleis kannst du vergessen.' },
        { art:'hoerwahl', wer:'Frau', text:'Wir sind zu sechst. Zwei Kollegen kommen aber erst später dazu.',
          frage:'Wie viele Personen sind am Anfang da?', opt:['Sechs','Zwei','Vier'], loesung:2,
          stelle:'Zwei Kollegen kommen aber erst später dazu',
          erklaerung:'Sechs sind es am Ende. Am Anfang fehlen zwei, also sind vier da. Das Wort aber kündigt die Einschränkung an.' }
      ] },

    { id:'a2b2', stufe:1, titel:'Termine und Uhrzeiten', kurz:'Viertel vor, halb, ab wann',
      ziel:'Nach diesem Block verwechselst du halb sieben und sieben Uhr dreißig nie wieder.',
      zeichen:'🕐', farbe:'gold',
      aufgaben:[
        { art:'hoerwahl', wer:'Frau', text:'Der Zug fährt um Viertel vor acht, nicht um Viertel nach acht.',
          frage:'Wann fährt der Zug?', opt:['Um 7.45 Uhr','Um 8.15 Uhr','Um 8.45 Uhr'], loesung:0,
          stelle:'um Viertel vor acht',
          erklaerung:'Viertel vor acht ist 7.45 Uhr — eine Viertelstunde VOR acht. Viertel nach acht wäre 8.15 Uhr.' },
        { art:'hoerwahl', wer:'Mann', text:'Wir treffen uns halb sieben vor dem Kino, der Film beginnt um sieben.',
          frage:'Wann treffen sich die beiden?', opt:['Um 19.30 Uhr','Um 18.30 Uhr','Um 19 Uhr'], loesung:1,
          stelle:'halb sieben',
          erklaerung:'Halb sieben heißt 6.30 Uhr, abends also 18.30 — eine halbe Stunde VOR sieben. Sieben Uhr dreißig wäre 19.30.' },
        { art:'hoerwahl', wer:'Frau', text:'Ihr Termin ist am dreizehnten März um elf Uhr.',
          frage:'Wann ist der Termin?', opt:['Am 30. März','Am 3. März','Am 13. März'], loesung:2,
          stelle:'am dreizehnten März',
          erklaerung:'Dreizehnter und dreißigster klingen ähnlich. Achte auf die Endung: -zehnten ist der 13., -ßigsten der 30.' },
        { art:'hoerwahl', wer:'Mann', text:'Wir haben von neun bis achtzehn Uhr geöffnet, am Samstag nur bis vierzehn Uhr.',
          frage:'Wann schließt das Geschäft am Samstag?', opt:['Um 14 Uhr','Um 18 Uhr','Um 9 Uhr'], loesung:0,
          stelle:'am Samstag nur bis vierzehn Uhr',
          erklaerung:'Der zweite Satzteil gilt nur für Samstag. Das Wörtchen nur zeigt an, dass hier etwas anders ist.' },
        { art:'hoerwahl', wer:'Frau', text:'Heute ist Montag. Der Handwerker kommt übermorgen am Vormittag.',
          frage:'An welchem Tag kommt der Handwerker?', opt:['Am Mittwoch','Am Dienstag','Am Montag'], loesung:0,
          stelle:'übermorgen',
          erklaerung:'Übermorgen ist der Tag nach morgen. Von Montag aus: morgen Dienstag, übermorgen Mittwoch.' },
        { art:'hoerwahl', wer:'Mann', text:'Heute haben wir Donnerstag. Das nächste Treffen ist in einer Woche, also wieder am Donnerstag.',
          frage:'Wann ist das nächste Treffen?', opt:['Morgen','In einem Monat','In sieben Tagen'], loesung:2,
          stelle:'in einer Woche',
          erklaerung:'Eine Woche sind sieben Tage. Der Satz nach also wiederholt es zur Sicherheit — solche Wiederholungen sind Geschenke.' },
        { art:'hoerwahl', wer:'Frau', text:'Bitte melden Sie sich bis spätestens Ende des Monats an. Danach ist der Kurs voll.',
          frage:'Bis wann kann man sich anmelden?', opt:['Bis morgen','Bis Ende des Monats','Bis Ende des Jahres'], loesung:1,
          stelle:'bis spätestens Ende des Monats',
          erklaerung:'Spätestens markiert die letzte Möglichkeit. Alles danach ist zu spät.' },
        { art:'hoerwahl', wer:'Mann', text:'Der Elternabend ist jeden zweiten Dienstag im Monat, immer um neunzehn Uhr.',
          frage:'Wie oft ist der Elternabend?', opt:['Einmal im Monat','Jeden Dienstag','Zweimal im Monat'], loesung:0,
          stelle:'jeden zweiten Dienstag im Monat',
          erklaerung:'Jeden zweiten Dienstag im Monat heißt: einmal im Monat, nämlich am zweiten Dienstag. Nicht alle vierzehn Tage.' },
        { art:'hoerwahl', wer:'Frau', text:'Ihr Termin am Mittwoch muss leider verschoben werden. Wir tragen Sie für Freitag ein, gleiche Uhrzeit.',
          frage:'An welchem Tag ist der Termin jetzt?', opt:['Am Mittwoch','Am Donnerstag','Am Freitag'], loesung:2,
          stelle:'Wir tragen Sie für Freitag ein',
          erklaerung:'Verschoben heißt: der alte Tag fällt weg. Der neue Tag kommt im Satz danach.' },
        { art:'hoerwahl', wer:'Mann', text:'Das Museum öffnet erst ab zehn Uhr. Die Kasse schließt schon um siebzehn Uhr dreißig.',
          frage:'Wann schließt die Kasse?', opt:['Um 10 Uhr','Um 17.30 Uhr','Um 18 Uhr'], loesung:1,
          stelle:'um siebzehn Uhr dreißig',
          erklaerung:'Zwei Zeiten, zwei verschiedene Dinge: erst ab gehört zur Öffnung, schon um zur Kasse. Die Frage nennt dir, welche du brauchst.' }
      ] },

    { id:'a2b3', stufe:2, titel:'Nicht, kein, sondern, statt', kurz:'Wenn ein Wort alles umdreht',
      ziel:'Nach diesem Block überhörst du kein nicht und kein sondern mehr.',
      zeichen:'❗', farbe:'rot',
      aufgaben:[
        { art:'hoerwahl', wer:'Mann', text:'Der Deutschkurs findet heute ausnahmsweise nicht in Raum zwölf statt, sondern in Raum drei.',
          frage:'In welchem Raum ist der Kurs heute?', opt:['In Raum 12','In Raum 30','In Raum 3'], loesung:2,
          stelle:'sondern in Raum drei',
          erklaerung:'Nach sondern kommt, was wirklich gilt. Raum zwölf war der ursprüngliche Plan.' },
        { art:'hoerwahl', wer:'Frau', text:'Der Arzt kommt heute später. Die Sprechstunde beginnt statt um zehn erst um elf.',
          frage:'Wann beginnt die Sprechstunde?', opt:['Um 11 Uhr','Um 10 Uhr','Um 12 Uhr'], loesung:0,
          stelle:'statt um zehn erst um elf',
          erklaerung:'Nach statt steht die alte Zeit, nach erst die neue. Die neue gilt.' },
        { art:'hoerwahl', wer:'Mann', text:'Achtung: Die Linie sechs fährt heute nicht bis zum Hauptbahnhof, sondern nur bis zum Marktplatz.',
          frage:'Wo endet die Linie 6 heute?', opt:['Am Hauptbahnhof','An der Schule','Am Marktplatz'], loesung:2,
          stelle:'sondern nur bis zum Marktplatz',
          erklaerung:'Nur bis grenzt ein: weiter fährt der Bus heute nicht.' },
        { art:'hoerwahl', wer:'Frau', text:'Wir nehmen leider keine Kartenzahlung an. Sie können aber bar bezahlen oder überweisen.',
          frage:'Wie kann man bezahlen?', opt:['Mit Karte','Bar','Gar nicht'], loesung:1,
          stelle:'Sie können aber bar bezahlen',
          erklaerung:'Kein sagt, was nicht geht. Nach aber kommt die Möglichkeit, die bleibt.' },
        { art:'hoerwahl', wer:'Mann', text:'Zum Kurs müssen Sie kein Buch mitbringen, nur einen Stift und ein Heft.',
          frage:'Was soll man mitbringen?', opt:['Ein Buch','Nichts','Stift und Heft'], loesung:2,
          stelle:'nur einen Stift und ein Heft',
          erklaerung:'Kein Buch heißt nicht, dass man gar nichts braucht. Nach nur steht, was wirklich nötig ist.' },
        { art:'hoerwahl', wer:'Frau', text:'Frau Berger ist heute im Homeoffice. Im Büro erreichen Sie sie nicht, aber gern auf dem Handy.',
          frage:'Wie erreicht man Frau Berger heute?', opt:['Auf dem Handy','Im Büro','Gar nicht'], loesung:0,
          stelle:'aber gern auf dem Handy',
          erklaerung:'Die Verneinung gilt nur für das Büro. Das Wort aber kündigt an, dass jetzt der andere Weg kommt.' },
        { art:'hoerwahl', wer:'Mann', text:'Das Formular schicken Sie bitte nicht per E-Mail, sondern mit der Post an unser Amt.',
          frage:'Wie soll man das Formular schicken?', opt:['Mit der Post','Per E-Mail','Per Fax'], loesung:0,
          stelle:'sondern mit der Post',
          erklaerung:'Nicht … sondern ist das häufigste Paar in der Prüfung. Die Antwort steht immer im zweiten Teil.' },
        { art:'hoerwahl', wer:'Frau', text:'Ich habe kein Auto mehr. Ich fahre jetzt jeden Tag mit dem Rad zur Arbeit.',
          frage:'Wie kommt die Frau zur Arbeit?', opt:['Mit dem Auto','Mit dem Bus','Mit dem Rad'], loesung:2,
          stelle:'mit dem Rad zur Arbeit',
          erklaerung:'Kein Auto mehr heißt: früher ja, heute nicht. Der zweite Satz sagt, was jetzt gilt.' },
        { art:'hoerwahl', wer:'Mann', text:'Wir suchen keine Aushilfe für das Wochenende, sondern jemanden für die Woche.',
          frage:'Wann wird jemand gesucht?', opt:['Am Wochenende','In der Woche','Nur am Sonntag'], loesung:1,
          stelle:'sondern jemanden für die Woche',
          erklaerung:'Das Wochenende wird ausdrücklich ausgeschlossen. Was gesucht wird, steht nach sondern.' },
        { art:'hoerwahl', wer:'Frau', text:'Der Eintritt kostet nichts. Für die Führung zahlen Sie allerdings fünf Euro extra.',
          frage:'Was muss man bezahlen?', opt:['Den Eintritt','Nichts','Die Führung'], loesung:2,
          stelle:'Für die Führung zahlen Sie allerdings fünf Euro extra',
          erklaerung:'Allerdings ist ein Warnwort wie aber: Danach kommt die Einschränkung. Frei ist nur der Eintritt.' }
      ] },

    { id:'a2b4', stufe:2, titel:'Wenn sich Pläne ändern', kurz:'fällt aus, verschoben, stattdessen',
      ziel:'Nach diesem Block hörst du bis zum Ende und nimmst immer die zweite Information.',
      zeichen:'🔄', farbe:'lila',
      aufgaben:[
        { art:'hoerwahl', wer:'Mann', text:'Die Lieferung kommt leider nicht am Freitag. Wir bringen das Paket am Montag zwischen acht und zwölf.',
          frage:'Wann kommt das Paket?', opt:['Am Freitag','Am Montag','Am Dienstag'], loesung:1,
          stelle:'Wir bringen das Paket am Montag',
          erklaerung:'Nach leider nicht steht immer, was ausfällt. Der neue Termin kommt im nächsten Satz.' },
        { art:'hoerwahl', wer:'Frau', text:'Das Schwimmbad ist wegen einer Reparatur bis Ende der Woche geschlossen. Ab Montag sind wir wieder für Sie da.',
          frage:'Ab wann ist das Schwimmbad wieder offen?', opt:['Ab Montag','Ab heute','Ab Ende der Woche'], loesung:0,
          stelle:'Ab Montag sind wir wieder für Sie da',
          erklaerung:'Bis Ende der Woche sagt, wie lange geschlossen ist. Ab Montag sagt, wann wieder offen ist.' },
        { art:'hoerwahl', wer:'Mann', text:'Der Vortrag beginnt eine halbe Stunde später als geplant, also erst um zwanzig Uhr.',
          frage:'Wann beginnt der Vortrag?', opt:['Um 19.30 Uhr','Um 20.30 Uhr','Um 20 Uhr'], loesung:2,
          stelle:'also erst um zwanzig Uhr',
          erklaerung:'Nach also steht die fertige Uhrzeit — du musst nicht selbst rechnen. Solche Sätze nehmen dir die Arbeit ab.' },
        { art:'hoerwahl', wer:'Frau', text:'Ihr Tisch für vier Personen ist reserviert. Können Sie statt um neunzehn Uhr schon um achtzehn Uhr dreißig kommen?',
          frage:'Wann sollen die Gäste kommen?', opt:['Um 19 Uhr','Um 16 Uhr','Um 18.30 Uhr'], loesung:2,
          stelle:'schon um achtzehn Uhr dreißig',
          erklaerung:'Die Bitte mit statt fragt nach der früheren Zeit. Schon zeigt an: eher als geplant.' },
        { art:'hoerwahl', wer:'Mann', text:'Der Ausflug in die Berge fällt bei Regen aus. Wir gehen dann stattdessen ins Museum.',
          frage:'Was machen die Leute bei Regen?', opt:['Sie fahren in die Berge','Sie bleiben zu Hause','Sie gehen ins Museum'], loesung:2,
          stelle:'stattdessen ins Museum',
          erklaerung:'Stattdessen heißt: an Stelle des ersten Plans. Danach steht immer die Ersatzlösung.' },
        { art:'hoerwahl', wer:'Frau', text:'Der Termin bei der Bank am Dienstag wurde abgesagt. Einen neuen Termin bekommen Sie nächste Woche.',
          frage:'Was ist mit dem Termin am Dienstag?', opt:['Er fällt aus','Er ist früher','Er bleibt'], loesung:0,
          stelle:'wurde abgesagt',
          erklaerung:'Abgesagt heißt: findet nicht statt. Der neue Termin steht noch nicht fest — nächste Woche ist keine Uhrzeit.' },
        { art:'hoerwahl', wer:'Mann', text:'Wir haben Ihre Bestellung erhalten. Die blaue Jacke ist leider ausverkauft, wir schicken Ihnen die graue.',
          frage:'Welche Jacke bekommt der Kunde?', opt:['Die blaue','Die graue','Gar keine'], loesung:1,
          stelle:'wir schicken Ihnen die graue',
          erklaerung:'Ausverkauft betrifft nur die blaue Jacke. Was wirklich kommt, steht nach dem Komma.' },
        { art:'hoerwahl', wer:'Frau', text:'Ursprünglich wollten wir im Juli umziehen. Jetzt wird es doch erst der August.',
          frage:'Wann ist der Umzug?', opt:['Im Juli','Im Juni','Im August'], loesung:2,
          stelle:'Jetzt wird es doch erst der August',
          erklaerung:'Ursprünglich zeigt den alten Plan an, jetzt den neuen. Das Wort doch verrät schon, dass sich etwas geändert hat.' },
        { art:'hoerwahl', wer:'Mann', text:'Der Kurs am Vormittag ist voll. Wenn Sie möchten, setze ich Sie auf die Liste für den Abendkurs.',
          frage:'Welchen Kurs kann die Person noch machen?', opt:['Den Vormittagskurs','Den Abendkurs','Keinen'], loesung:1,
          stelle:'auf die Liste für den Abendkurs',
          erklaerung:'Voll heißt: hier geht nichts mehr. Das Angebot danach ist die einzige offene Möglichkeit.' },
        { art:'hoerwahl', wer:'Frau', text:'Wegen des Sturms fahren heute keine Busse. Die Straßenbahnen fahren aber nach Plan.',
          frage:'Was fährt heute?', opt:['Die Busse','Nichts','Die Straßenbahnen'], loesung:2,
          stelle:'Die Straßenbahnen fahren aber nach Plan',
          erklaerung:'Die Absage gilt nur für die Busse. Nach aber steht, was trotzdem funktioniert.' }
      ] }
  ],

  teile: [

    { nr:1, art:'gespraech', name:'Kurze Gespräche', kurz:'Fünf Gespräche, drei Antworten',
      was:'Zwei Menschen reden miteinander — im Laden, am Telefon, im Büro, beim Amt. Dazu eine Frage mit drei Antworten. Du hörst jedes Gespräch zweimal.',
      tipp:'Lies die Frage, BEVOR du auf Abspielen drückst. Die Frage sagt dir, auf wen du hören musst. Wenn zwei Personen verschiedene Wünsche haben, zählt nur die Person aus der Frage.',
      zeichen:'💬', farbe:'turq', mal:2,
      runden:[

        { id:'a2t1r1', aufgaben:[
          { ort:'Im Reisebüro', zeilen:[
              { wer:'Frau', text:'Guten Tag, wir möchten im September nach Italien fahren, am liebsten ans Meer.' },
              { wer:'Mann', text:'Da hätte ich etwas an der Adria, eine Woche mit Frühstück für sechshundert Euro pro Person.' },
              { wer:'Frau', text:'Das ist uns zu teuer. Gibt es auch etwas ohne Frühstück?' },
              { wer:'Mann', text:'Ja, dann sind es vierhundertfünfzig Euro pro Person.' } ],
            frage:'Wie viel kostet die Reise ohne Frühstück?',
            opt:['450 Euro pro Person','600 Euro pro Person','1050 Euro pro Person'], loesung:0,
            stelle:'dann sind es vierhundertfünfzig Euro pro Person',
            erklaerung:'Beide Preise stehen im Text. Gefragt ist der Preis OHNE Frühstück — der kommt erst nach der Frage der Frau.' },
          { ort:'An der Rezeption im Hotel', zeilen:[
              { wer:'Mann', text:'Guten Abend, ich habe ein Einzelzimmer auf den Namen Kolb reserviert.' },
              { wer:'Frau', text:'Einen Moment... ja, Zimmer zweihundertelf im zweiten Stock. Das Frühstück gibt es von sieben bis zehn.' },
              { wer:'Mann', text:'Und wann muss ich am Abreisetag das Zimmer räumen?' },
              { wer:'Frau', text:'Bis elf Uhr, bitte. Das Gepäck können Sie danach gern bei uns lassen.' } ],
            frage:'Bis wann muss der Gast das Zimmer räumen?',
            opt:['Bis 10 Uhr','Bis 7 Uhr','Bis 11 Uhr'], loesung:2,
            stelle:'Bis elf Uhr, bitte',
            erklaerung:'Sieben und zehn gehören zum Frühstück. Die Antwort auf die Frage nach dem Zimmer kommt ganz am Schluss.' },
          { ort:'Beim Bäcker', zeilen:[
              { wer:'Frau', text:'Ich hätte gern sechs Brötchen und ein Roggenbrot.' },
              { wer:'Mann', text:'Das Roggenbrot ist leider aus. Ich hätte noch Vollkornbrot oder Weißbrot.' },
              { wer:'Frau', text:'Dann nehme ich das Vollkornbrot.' },
              { wer:'Mann', text:'Gern. Das macht zusammen sieben Euro achtzig.' } ],
            frage:'Welches Brot kauft die Frau?',
            opt:['Roggenbrot','Vollkornbrot','Weißbrot'], loesung:1,
            stelle:'Dann nehme ich das Vollkornbrot',
            erklaerung:'Drei Brotsorten werden genannt. Nur eine wird wirklich gekauft — hör auf den Satz mit ich nehme.' },
          { ort:'Im Büro', zeilen:[
              { wer:'Mann', text:'Frau Yilmaz, können Sie am Donnerstag die Besprechung übernehmen? Ich bin auf einer Fortbildung.' },
              { wer:'Frau', text:'Donnerstag ist schwierig, da habe ich einen Arzttermin. Freitag wäre kein Problem.' },
              { wer:'Mann', text:'Gut, dann verschiebe ich die Besprechung auf Freitag.' } ],
            frage:'Wann findet die Besprechung statt?',
            opt:['Am Freitag','Am Donnerstag','Gar nicht'], loesung:0,
            stelle:'dann verschiebe ich die Besprechung auf Freitag',
            erklaerung:'Der erste Vorschlag wird abgelehnt. Erst der letzte Satz sagt, was wirklich passiert.' },
          { ort:'Am Telefon bei der Autowerkstatt', zeilen:[
              { wer:'Frau', text:'Werkstatt Krause, guten Tag.' },
              { wer:'Mann', text:'Hier ist Herr Sander. Ist mein Auto fertig? Sie wollten heute anrufen.' },
              { wer:'Frau', text:'Entschuldigung, ein Ersatzteil fehlt noch. Sie können den Wagen morgen ab vierzehn Uhr abholen.' },
              { wer:'Mann', text:'In Ordnung, dann komme ich morgen Nachmittag.' } ],
            frage:'Wann kann Herr Sander sein Auto abholen?',
            opt:['Heute','Morgen früh','Morgen ab 14 Uhr'], loesung:2,
            stelle:'Sie können den Wagen morgen ab vierzehn Uhr abholen',
            erklaerung:'Heute war der Plan, morgen ist die Wirklichkeit. Ab vierzehn Uhr heißt Nachmittag — vormittags geht es nicht.' } ] },

        { id:'a2t1r2', aufgaben:[
          { ort:'Im Elektrogeschäft', zeilen:[
              { wer:'Mann', text:'Ich suche einen Drucker für zu Hause, nicht zu teuer.' },
              { wer:'Frau', text:'Dieser hier kostet achtzig Euro und druckt nur schwarz-weiß. Der daneben druckt in Farbe und kostet hundertdreißig.' },
              { wer:'Mann', text:'Meine Kinder brauchen Farbe für die Schule. Dann nehme ich den teureren.' } ],
            frage:'Welchen Drucker kauft der Mann?',
            opt:['Den für 80 Euro','Gar keinen','Den für 130 Euro'], loesung:2,
            stelle:'Dann nehme ich den teureren',
            erklaerung:'Der teurere ist der für hundertdreißig Euro. Die Begründung mit Farbe verrät dir die Antwort schon vorher.' },
          { ort:'Beim Einwohnermeldeamt', zeilen:[
              { wer:'Frau', text:'Guten Tag, ich möchte mich anmelden. Ich bin letzte Woche umgezogen.' },
              { wer:'Mann', text:'Dafür brauche ich Ihren Ausweis und die Bestätigung vom Vermieter.' },
              { wer:'Frau', text:'Den Ausweis habe ich dabei, die Bestätigung leider nicht.' },
              { wer:'Mann', text:'Dann kommen Sie bitte noch einmal. Ohne die Bestätigung geht es nicht.' } ],
            frage:'Was fehlt der Frau?',
            opt:['Die Bestätigung vom Vermieter','Der Ausweis','Ein Foto'], loesung:0,
            stelle:'die Bestätigung leider nicht',
            erklaerung:'Zwei Dinge werden verlangt, eines fehlt. Das Wort leider steht direkt vor dem Problem.' },
          { ort:'In der Sprachschule', zeilen:[
              { wer:'Mann', text:'Ich möchte den A2-Kurs machen. Geht das auch abends?' },
              { wer:'Frau', text:'Der Abendkurs ist zurzeit voll. Es gibt aber einen Kurs am Samstagvormittag.' },
              { wer:'Mann', text:'Samstag passt mir gut, ich arbeite unter der Woche.' } ],
            frage:'Wann macht der Mann den Kurs?',
            opt:['Abends','Am Samstagvormittag','Unter der Woche'], loesung:1,
            stelle:'einen Kurs am Samstagvormittag',
            erklaerung:'Der Wunsch am Anfang geht nicht. Nach aber kommt das, was möglich ist — und genau das nimmt er.' },
          { ort:'Am Bahnschalter', zeilen:[
              { wer:'Frau', text:'Eine Fahrkarte nach Hamburg, bitte. Wann fährt der nächste Zug?' },
              { wer:'Mann', text:'Um zwölf Uhr zwanzig mit Umstieg in Hannover, oder um dreizehn Uhr direkt.' },
              { wer:'Frau', text:'Ich habe viel Gepäck. Dann lieber ohne Umsteigen.' } ],
            frage:'Welchen Zug nimmt die Frau?',
            opt:['Den um 12.20 Uhr','Den um 13 Uhr','Den nach Hannover'], loesung:1,
            stelle:'oder um dreizehn Uhr direkt',
            erklaerung:'Ohne Umsteigen heißt direkt — das ist der Zug um dreizehn Uhr. Die Frau nennt die Uhrzeit selbst gar nicht mehr.' },
          { ort:'Beim Arzt an der Anmeldung', zeilen:[
              { wer:'Mann', text:'Guten Tag, ich habe einen Termin um halb zehn bei Doktor Wolf.' },
              { wer:'Frau', text:'Doktor Wolf ist heute krank. Sie können zu Doktor Prem, dann müssten Sie aber bis zehn Uhr warten.' },
              { wer:'Mann', text:'Das ist in Ordnung, ich habe Zeit.' } ],
            frage:'Was macht der Mann?',
            opt:['Er wartet auf Doktor Prem','Er geht wieder','Er kommt morgen'], loesung:0,
            stelle:'Das ist in Ordnung, ich habe Zeit',
            erklaerung:'Das ist in Ordnung ist eine Zustimmung. Sie bezieht sich auf den Vorschlag davor: warten und zum anderen Arzt gehen.' } ] },

        { id:'a2t1r3', aufgaben:[
          { ort:'In der Wohnungsbesichtigung', zeilen:[
              { wer:'Frau', text:'Die Wohnung hat zwei Zimmer, Küche und Bad, insgesamt sechzig Quadratmeter.' },
              { wer:'Mann', text:'Und der Balkon? In der Anzeige stand etwas von einem Balkon.' },
              { wer:'Frau', text:'Einen Balkon gibt es leider nicht, aber einen Kellerraum und einen Stellplatz.' } ],
            frage:'Was gehört zur Wohnung?',
            opt:['Ein Balkon','Ein Garten','Ein Stellplatz'], loesung:2,
            stelle:'aber einen Kellerraum und einen Stellplatz',
            erklaerung:'Der Balkon wird ausdrücklich verneint. Was es wirklich gibt, steht nach aber.' },
          { ort:'Am Kundenservice', zeilen:[
              { wer:'Mann', text:'Ich habe vor zwei Wochen eine Waschmaschine bestellt. Sie ist immer noch nicht da.' },
              { wer:'Frau', text:'Das tut mir leid. Ich sehe hier: Die Lieferung ist für kommenden Dienstag geplant.' },
              { wer:'Mann', text:'Dienstag arbeite ich. Geht auch Mittwoch?' },
              { wer:'Frau', text:'Mittwoch ist möglich, zwischen neun und dreizehn Uhr.' } ],
            frage:'Wann wird die Waschmaschine geliefert?',
            opt:['Am Mittwoch','Am Dienstag','In zwei Wochen'], loesung:0,
            stelle:'Mittwoch ist möglich',
            erklaerung:'Der geplante Termin wird gewechselt. Die Zustimmung der Mitarbeiterin am Ende macht den neuen Tag verbindlich.' },
          { ort:'In der Kantine', zeilen:[
              { wer:'Frau', text:'Nimmst du auch das Menü mit Fisch? Das gibt es nur freitags.' },
              { wer:'Mann', text:'Ich esse keinen Fisch. Ich nehme die Gemüsesuppe und einen Salat.' },
              { wer:'Frau', text:'Dann gehe ich schon mal zur Kasse.' } ],
            frage:'Was isst der Mann?',
            opt:['Fisch','Suppe und Salat','Nichts'], loesung:1,
            stelle:'Ich nehme die Gemüsesuppe und einen Salat',
            erklaerung:'Die Frage fragt nach dem Mann. Was die Frau isst, wird gar nicht gesagt — lass dich davon nicht ablenken.' },
          { ort:'Am Telefon mit der Nachbarin', zeilen:[
              { wer:'Frau', text:'Frau Demir, könnten Sie am Wochenende unsere Katze füttern? Wir sind bei meinen Eltern.' },
              { wer:'Mann', text:'Am Samstag bin ich selbst weg, aber am Sonntag gern.' },
              { wer:'Frau', text:'Dann frage ich für Samstag meinen Sohn. Vielen Dank!' } ],
            frage:'Wann füttert der Nachbar die Katze?',
            opt:['Am Samstag','Das ganze Wochenende','Am Sonntag'], loesung:2,
            stelle:'aber am Sonntag gern',
            erklaerung:'Am Samstag geht es nicht, am Sonntag schon. Die Frau bestätigt es, indem sie für Samstag jemand anderen fragt.' },
          { ort:'Im Fitnessstudio', zeilen:[
              { wer:'Mann', text:'Was kostet die Mitgliedschaft?' },
              { wer:'Frau', text:'Monatlich neunundzwanzig Euro. Bei einem Jahresvertrag zahlen Sie nur vierundzwanzig im Monat.' },
              { wer:'Mann', text:'Ich bin nur ein halbes Jahr in der Stadt. Dann nehme ich den monatlichen Vertrag.' } ],
            frage:'Wie viel zahlt der Mann im Monat?',
            opt:['24 Euro','29 Euro','Ein halbes Jahr im Voraus'], loesung:1,
            stelle:'Monatlich neunundzwanzig Euro',
            erklaerung:'Der günstigere Preis gilt nur mit Jahresvertrag. Weil er den nicht nimmt, zahlt er den höheren Preis.' } ] }
      ] },

    { nr:2, art:'durchsage', name:'Durchsagen', kurz:'Fünf Durchsagen, richtig oder falsch',
      was:'Lautsprecherdurchsagen am Bahnhof, im Kaufhaus, im Schwimmbad, in der Firma. Dazu eine Aussage: Stimmt sie oder nicht?',
      tipp:'Diese Texte hörst du nur EINMAL — auch hier im Training. Deshalb: erst die Aussage lesen, dann abspielen, und beim Hören nur auf dieses eine Detail achten. Meistens stimmt fast alles und ein einziges Wort ist falsch.',
      zeichen:'📢', farbe:'rot', mal:1,
      runden:[

        { id:'a2t2r1', aufgaben:[
          { ort:'Am Hauptbahnhof', wer:'Mann',
            text:'Information für die Reisenden nach Nürnberg: Der Intercity um vierzehn Uhr sieben hat heute etwa zwanzig Minuten Verspätung. Der Anschlusszug in Nürnberg wartet.',
            satz:'Der Zug nach Nürnberg fällt heute aus.', loesung:false,
            stelle:'hat heute etwa zwanzig Minuten Verspätung',
            erklaerung:'Verspätung heißt: Der Zug kommt später, aber er kommt. Ausfallen wäre etwas ganz anderes.' },
          { ort:'Im Kaufhaus', wer:'Frau',
            text:'Liebe Kundinnen und Kunden, unsere Sportabteilung im dritten Stock ist wegen Umbau geschlossen. Sportartikel finden Sie in dieser Woche im Erdgeschoss.',
            satz:'Sportartikel gibt es diese Woche im Erdgeschoss.', loesung:true,
            stelle:'Sportartikel finden Sie in dieser Woche im Erdgeschoss',
            erklaerung:'Der dritte Stock ist zu, aber die Ware ist nicht weg. Der zweite Satz sagt, wohin man gehen muss.' },
          { ort:'Im Schwimmbad', wer:'Mann',
            text:'Achtung, eine Durchsage: Das große Becken wird in zehn Minuten für den Schwimmkurs gesperrt. Das kleine Becken und die Sauna bleiben geöffnet.',
            satz:'Die Sauna wird auch gesperrt.', loesung:false,
            stelle:'Das kleine Becken und die Sauna bleiben geöffnet',
            erklaerung:'Gesperrt wird nur das große Becken. Bleiben geöffnet ist die klare Gegeninformation.' },
          { ort:'Am Flughafen', wer:'Frau',
            text:'Letzter Aufruf für Flug LH zweiundfünfzig nach Wien. Die Passagiere werden gebeten, sich sofort zum Ausgang B zwölf zu begeben.',
            satz:'Die Passagiere sollen zum Ausgang B12 kommen.', loesung:true,
            stelle:'sich sofort zum Ausgang B zwölf zu begeben',
            erklaerung:'Sich zu einem Ausgang begeben heißt: dorthin gehen. B zwölf ist B12 — die Zahl wird ausgesprochen, nicht buchstabiert.' },
          { ort:'In der Firma', wer:'Mann',
            text:'Eine Information aus der Personalabteilung: Die Kantine bleibt am Freitag geschlossen. Getränke und belegte Brötchen gibt es wie immer im Automaten im Erdgeschoss.',
            satz:'Am Freitag bekommt man in der Firma gar nichts zu essen.', loesung:false,
            stelle:'belegte Brötchen gibt es wie immer im Automaten',
            erklaerung:'Die Kantine ist zu, der Automat nicht. Gar nichts ist zu absolut — solche Wörter sind in dieser Aufgabe fast immer falsch.' } ] },

        { id:'a2t2r2', aufgaben:[
          { ort:'Im Supermarkt', wer:'Frau',
            text:'Liebe Kunden, wir schließen heute bereits um achtzehn Uhr. Bitte kommen Sie in den nächsten zwanzig Minuten zur Kasse.',
            satz:'Der Supermarkt schließt heute früher als sonst.', loesung:true,
            stelle:'wir schließen heute bereits um achtzehn Uhr',
            erklaerung:'Bereits und heute zeigen zusammen an: Das ist nicht die normale Zeit. Genau darauf zielt die Aussage.' },
          { ort:'In der Straßenbahn', wer:'Mann',
            text:'Nächste Haltestelle Rathausplatz. Wegen einer Baustelle fährt diese Bahn heute nicht bis zum Zoo, sondern endet am Stadtpark.',
            satz:'Die Bahn fährt heute bis zum Zoo.', loesung:false,
            stelle:'sondern endet am Stadtpark',
            erklaerung:'Nicht bis zum Zoo, sondern bis zum Stadtpark. Die Aussage nennt genau das Ziel, das gestrichen wurde.' },
          { ort:'In der Bibliothek', wer:'Frau',
            text:'Wir weisen darauf hin, dass die Bibliothek in zwanzig Minuten schließt. Bücher können Sie noch bis fünf vor sechs ausleihen.',
            satz:'Man kann noch Bücher ausleihen.', loesung:true,
            stelle:'Bücher können Sie noch bis fünf vor sechs ausleihen',
            erklaerung:'Noch heißt: es geht weiterhin, aber nicht mehr lange. Die Aussage stimmt also.' },
          { ort:'Im Zug', wer:'Mann',
            text:'Sehr geehrte Fahrgäste, das Bordrestaurant im Wagen sechs ist heute leider nicht besetzt. Ein Getränkewagen kommt gleich durch die Wagen.',
            satz:'Man kann im Zug etwas trinken kaufen.', loesung:true,
            stelle:'Ein Getränkewagen kommt gleich durch die Wagen',
            erklaerung:'Das Restaurant fällt aus, der Getränkewagen nicht. Hier musst du bis zum zweiten Satz warten.' },
          { ort:'Im Parkhaus', wer:'Frau',
            text:'Achtung: Die Ausfahrt Süd ist wegen einer Reparatur gesperrt. Bitte benutzen Sie die Ausfahrt Nord neben dem Aufzug.',
            satz:'Man kann das Parkhaus im Moment nicht verlassen.', loesung:false,
            stelle:'Bitte benutzen Sie die Ausfahrt Nord',
            erklaerung:'Eine Ausfahrt ist zu, die andere offen. Rausfahren geht also — nur an einer anderen Stelle.' } ] },

        { id:'a2t2r3', aufgaben:[
          { ort:'Auf dem Campingplatz', wer:'Mann',
            text:'Guten Morgen, liebe Gäste. Wegen der Trockenheit ist Grillen auf dem ganzen Platz verboten. Die Küche im Hauptgebäude können Sie gern benutzen.',
            satz:'Grillen ist auf dem Campingplatz erlaubt.', loesung:false,
            stelle:'ist Grillen auf dem ganzen Platz verboten',
            erklaerung:'Verboten ist das Gegenteil von erlaubt. Die Küche ist eine Alternative, kein Widerspruch.' },
          { ort:'In der Schule', wer:'Frau',
            text:'Eine Durchsage für die Klassen sieben und acht: Der Sportunterricht in der fünften Stunde fällt heute aus. Ihr habt in dieser Zeit frei.',
            satz:'Die Schüler haben in der fünften Stunde frei.', loesung:true,
            stelle:'Ihr habt in dieser Zeit frei',
            erklaerung:'Fällt aus und habt frei sagen dasselbe. Der zweite Satz bestätigt den ersten.' },
          { ort:'Im Krankenhaus', wer:'Mann',
            text:'Wir bitten um Beachtung: Die Besuchszeit endet um zwanzig Uhr. Für Eltern von kleinen Kindern gilt diese Regel nicht.',
            satz:'Alle Besucher müssen um 20 Uhr gehen.', loesung:false,
            stelle:'Für Eltern von kleinen Kindern gilt diese Regel nicht',
            erklaerung:'Alle ist zu viel: Für eine Gruppe gilt die Regel ausdrücklich nicht. Achte auf Ausnahmen am Satzende.' },
          { ort:'Im Museum', wer:'Frau',
            text:'Liebe Besucher, die Sonderausstellung im Obergeschoss schließt bereits um sechzehn Uhr. Die übrigen Räume sind bis achtzehn Uhr geöffnet.',
            satz:'Die Sonderausstellung schließt früher als die anderen Räume.', loesung:true,
            stelle:'schließt bereits um sechzehn Uhr',
            erklaerung:'Sechzehn Uhr ist früher als achtzehn Uhr. Hier musst du zwei Zeiten vergleichen, nicht nur eine hören.' },
          { ort:'Auf dem Wochenmarkt', wer:'Mann',
            text:'Liebe Kundinnen und Kunden, wegen des Feiertags findet der Markt am Donnerstag nicht statt. Wir sind stattdessen am Mittwoch für Sie da.',
            satz:'Der Markt findet in dieser Woche am Mittwoch statt.', loesung:true,
            stelle:'Wir sind stattdessen am Mittwoch für Sie da',
            erklaerung:'Der gewohnte Tag fällt weg, nach stattdessen kommt der Ersatztag. Genau diesen nennt die Aussage.' } ] }
      ] },

    { nr:3, art:'ansage', name:'Auf dem Anrufbeantworter', kurz:'Fünf Nachrichten, drei Antworten',
      was:'Eine Nachricht auf der Mailbox: Die Praxis sagt den Termin ab, die Schule meldet sich wegen des Ausflugs, ein Freund verschiebt die Verabredung, das Amt will noch ein Papier.',
      tipp:'Auch diese Texte hörst du nur EINMAL. Fast jede Nachricht nennt zuerst den alten Plan und dann den neuen. Warte auf leider, aber, statt, neu — danach kommt die Antwort.',
      zeichen:'📞', farbe:'gold', mal:1,
      runden:[

        { id:'a2t3r1', aufgaben:[
          { von:'Praxis Doktor Berger', wer:'Frau',
            text:'Guten Tag, Frau Novak, hier ist die Praxis Doktor Berger. Ihr Termin am Dienstag um neun Uhr muss leider ausfallen, der Arzt ist auf einer Fortbildung. Wir hätten am Donnerstag um halb elf einen Platz für Sie. Bitte rufen Sie kurz zurück.',
            frage:'Wann ist der neue Termin?',
            opt:['Am Dienstag um 9 Uhr','Am Donnerstag um 10.30 Uhr','Am Donnerstag um 11 Uhr'], loesung:1,
            stelle:'am Donnerstag um halb elf',
            erklaerung:'Halb elf ist 10.30 Uhr, nicht 11 Uhr. Bei leider ausfallen weißt du schon: Den ersten Termin kannst du streichen.' },
          { von:'Grundschule am Park', wer:'Mann',
            text:'Guten Morgen, hier ist die Grundschule am Park. Der Ausflug am Freitag findet statt, aber wir treffen uns nicht in der Schule, sondern direkt am Bahnhof um acht Uhr. Bitte geben Sie Ihrem Kind ein Lunchpaket mit.',
            frage:'Wo treffen sich die Kinder am Freitag?',
            opt:['Am Bahnhof','In der Schule','Im Park'], loesung:0,
            stelle:'sondern direkt am Bahnhof um acht Uhr',
            erklaerung:'Der Ausflug fällt nicht aus — nur der Treffpunkt ist anders. Die Antwort steht nach sondern.' },
          { von:'Deine Freundin Sabine', wer:'Frau',
            text:'Hallo, ich bin es, Sabine. Wegen morgen Abend: Ins Kino schaffe ich es nicht, ich muss länger arbeiten. Sollen wir stattdessen am Samstag essen gehen? Melde dich bitte.',
            frage:'Was schlägt Sabine vor?',
            opt:['Am Samstag essen zu gehen','Ins Kino zu gehen','Sich morgen früher zu treffen'], loesung:0,
            stelle:'stattdessen am Samstag essen gehen',
            erklaerung:'Stattdessen leitet den Ersatzvorschlag ein. Das Kino ist genau das, was NICHT klappt.' },
          { von:'Stadtverwaltung, Zimmer 214', wer:'Mann',
            text:'Guten Tag, Herr Osei, Stadtverwaltung, Zimmer zweihundertvierzehn. Ihr Antrag ist bei uns eingegangen. Es fehlt allerdings noch eine Kopie Ihres Mietvertrags. Sie können sie per Post schicken oder bis Freitag vorbeibringen.',
            frage:'Was soll Herr Osei tun?',
            opt:['Einen neuen Antrag stellen','Am Freitag anrufen','Eine Kopie des Mietvertrags schicken'], loesung:2,
            stelle:'Es fehlt allerdings noch eine Kopie Ihres Mietvertrags',
            erklaerung:'Der Antrag ist da, es fehlt nur ein Papier. Allerdings kündigt an, dass jetzt das Problem kommt.' },
          { von:'Möbelhaus Lindner', wer:'Frau',
            text:'Guten Tag, hier ist das Möbelhaus Lindner. Ihr Schrank ist eingetroffen. Wir liefern am Mittwoch zwischen zehn und vierzehn Uhr. Wenn das nicht passt, rufen Sie uns bitte bis Dienstagmittag an.',
            frage:'Wann wird der Schrank geliefert?',
            opt:['Am Mittwoch','Am Dienstagmittag','Zwischen 14 und 18 Uhr'], loesung:0,
            stelle:'Wir liefern am Mittwoch zwischen zehn und vierzehn Uhr',
            erklaerung:'Dienstagmittag ist nur die Frist zum Absagen, nicht der Liefertag. Zwei Termine in einer Nachricht — lies vorher genau, welcher gefragt ist.' } ] },

        { id:'a2t3r2', aufgaben:[
          { von:'Autohaus Weber', wer:'Mann',
            text:'Guten Tag, Frau Lange, Autohaus Weber. Ihr Wagen ist fertig, die Reparatur hat weniger gekostet als gedacht: statt dreihundert nur zweihundertvierzig Euro. Abholen können Sie ihn ab morgen früh.',
            frage:'Wie viel kostet die Reparatur?',
            opt:['300 Euro','240 Euro','340 Euro'], loesung:1,
            stelle:'statt dreihundert nur zweihundertvierzig Euro',
            erklaerung:'Nach statt steht der alte Preis, danach der wirkliche. Weniger als gedacht sagt dir schon, dass die kleinere Zahl richtig ist.' },
          { von:'Sprachschule Aktiv', wer:'Frau',
            text:'Hallo Herr Petrov, hier ist die Sprachschule Aktiv. Ihr Kurs beginnt nächste Woche, aber nicht am Montag, sondern erst am Mittwoch. Der Raum ist wie besprochen die Nummer vier im Erdgeschoss.',
            frage:'Wann beginnt der Kurs?',
            opt:['Am Montag','Im Raum vier','Nächste Woche Mittwoch'], loesung:2,
            stelle:'sondern erst am Mittwoch',
            erklaerung:'Der Raum bleibt gleich, der Tag ändert sich. Eine der Antworten ist gar kein Zeitpunkt — die kannst du sofort streichen.' },
          { von:'Nachbar Herr Klein', wer:'Mann',
            text:'Hallo, hier ist Herr Klein von nebenan. Ihr Paket wurde bei mir abgegeben. Ich bin heute bis zwanzig Uhr zu Hause, morgen erst wieder ab siebzehn Uhr. Kommen Sie einfach vorbei.',
            frage:'Wann kann man das Paket morgen abholen?',
            opt:['Ab 17 Uhr','Bis 20 Uhr','Gar nicht'], loesung:0,
            stelle:'morgen erst wieder ab siebzehn Uhr',
            erklaerung:'Zwei Tage, zwei Zeiten. Gefragt ist morgen — die Zeit für heute ist die Ablenkung.' },
          { von:'Zahnarztpraxis Dr. Sommer', wer:'Frau',
            text:'Guten Tag, Praxis Doktor Sommer. Zur Erinnerung an Ihren Termin am Montag um vierzehn Uhr dreißig. Bringen Sie bitte Ihre Versichertenkarte und den Bonusheft mit. Kommen Sie zehn Minuten früher.',
            frage:'Wann soll die Patientin in der Praxis sein?',
            opt:['Um 14.30 Uhr','Um 14.20 Uhr','Um 14.40 Uhr'], loesung:1,
            stelle:'Kommen Sie zehn Minuten früher',
            erklaerung:'Der Termin ist um 14.30, aber da sein soll sie zehn Minuten vorher — also um 14.20 Uhr. Hier musst du selbst rechnen.' },
          { von:'Reisebüro Sonnenweg', wer:'Mann',
            text:'Guten Tag, Reisebüro Sonnenweg. Leider ist das Hotel am Strand für Ihren Termin ausgebucht. Wir haben ein Hotel im Ort reserviert, zehn Minuten zu Fuß vom Meer. Der Preis bleibt gleich.',
            frage:'Wo ist das neue Hotel?',
            opt:['Direkt am Strand','Im Ort','In einer anderen Stadt'], loesung:1,
            stelle:'Wir haben ein Hotel im Ort reserviert',
            erklaerung:'Ausgebucht heißt: dort ist kein Platz mehr. Was wirklich gebucht wurde, steht im nächsten Satz.' } ] },

        { id:'a2t3r3', aufgaben:[
          { von:'Hausverwaltung Mertens', wer:'Frau',
            text:'Guten Tag, Hausverwaltung Mertens. Am Donnerstag wird im ganzen Haus das Wasser abgestellt, von acht bis etwa dreizehn Uhr. Bitte stellen Sie sich rechtzeitig Wasser bereit.',
            frage:'Was passiert am Donnerstag?',
            opt:['Es gibt kein Wasser','Der Strom fällt aus','Die Heizung wird repariert'], loesung:0,
            stelle:'wird im ganzen Haus das Wasser abgestellt',
            erklaerung:'Abgestellt heißt: es kommt nichts mehr aus dem Hahn. Die Uhrzeiten sagen nur, wie lange.' },
          { von:'Deine Kollegin Anna', wer:'Frau',
            text:'Hi, ich bin es, Anna. Ich stehe im Stau und schaffe die Besprechung um neun nicht. Kannst du bitte anfangen? Ich bin spätestens um halb zehn da.',
            frage:'Wann kommt Anna?',
            opt:['Um 9 Uhr','Gar nicht','Um 9.30 Uhr'], loesung:2,
            stelle:'Ich bin spätestens um halb zehn da',
            erklaerung:'Halb zehn ist 9.30 Uhr. Neun Uhr ist der Beginn der Besprechung, nicht ihre Ankunft.' },
          { von:'Fahrschule Mobil', wer:'Mann',
            text:'Guten Tag, Fahrschule Mobil. Ihre theoretische Prüfung ist bestätigt für den achtzehnten Mai um acht Uhr dreißig. Bringen Sie Ihren Pass mit. Ohne Ausweis dürfen Sie nicht teilnehmen.',
            frage:'Was muss der Schüler mitbringen?',
            opt:['Den Pass','Geld','Ein Foto'], loesung:0,
            stelle:'Bringen Sie Ihren Pass mit',
            erklaerung:'Der zweite Satz wiederholt es mit anderen Worten: ohne Ausweis geht es nicht. Solche Wiederholungen sind der sicherste Beweis.' },
          { von:'Bücherei am Markt', wer:'Frau',
            text:'Guten Tag, hier ist die Bücherei am Markt. Zwei Ihrer Bücher sind seit einer Woche überfällig. Bringen Sie sie bitte bis Samstag zurück, dann müssen Sie nichts bezahlen.',
            frage:'Was passiert, wenn die Bücher bis Samstag zurückkommen?',
            opt:['Man zahlt eine Gebühr','Man zahlt nichts','Man bekommt neue Bücher'], loesung:1,
            stelle:'dann müssen Sie nichts bezahlen',
            erklaerung:'Der Satz mit dann nennt die Folge. Sie ist positiv — die Gebühr kommt nur, wenn man die Frist verpasst.' },
          { von:'Herr Wagner vom Sportverein', wer:'Mann',
            text:'Hallo, hier ist Herr Wagner vom Sportverein. Das Training am Samstag verlegen wir nach draußen auf den Rasenplatz, die Halle wird gestrichen. Zieht bitte Turnschuhe für draußen an.',
            frage:'Wo ist das Training am Samstag?',
            opt:['In der Halle','Auf dem Rasenplatz','Es fällt aus'], loesung:1,
            stelle:'nach draußen auf den Rasenplatz',
            erklaerung:'Verlegen heißt: derselbe Termin, ein anderer Ort. Die Halle ist der Grund, nicht das Ziel.' } ] }
      ] },

    { nr:4, art:'interview', name:'Meinungen im Radio', kurz:'Fünf Meinungen, drei Antworten',
      was:'Im Radio werden Leute auf der Straße gefragt: zum Einkaufen im Internet, zum Fahrrad in der Stadt, zum Handy für Kinder. Jede Person sagt ihre Meinung und begründet sie.',
      tipp:'Hier zählt nicht das Thema, sondern die Haltung: dafür, dagegen oder es kommt darauf an. Achte auf ich finde, mir ist wichtig, das stört mich — und besonders auf ein aber in der Mitte, denn danach kommt oft die eigentliche Meinung.',
      zeichen:'🎙️', farbe:'gruen', mal:2,
      runden:[

        { id:'a2t4r1', aufgaben:[
          { ort:'Radio Stadtwelle — Thema Online-Einkauf', zeilen:[
              { wer:'Frau', text:'Kaufen Sie lieber im Internet oder im Geschäft?' },
              { wer:'Mann', text:'Im Internet ist es bequem, das stimmt. Aber ich möchte die Sachen vorher anfassen, gerade bei Kleidung. Deshalb gehe ich fast immer in die Stadt.' } ],
            frage:'Wo kauft der Mann meistens ein?',
            opt:['Im Internet','Er kauft fast nichts','Im Geschäft'], loesung:2,
            stelle:'Deshalb gehe ich fast immer in die Stadt',
            erklaerung:'Der erste Satz klingt nach Zustimmung zum Internet. Nach aber dreht sich die Meinung — und deshalb nennt das Ergebnis.' },
          { ort:'Radio Stadtwelle — Thema Fahrrad in der Stadt', zeilen:[
              { wer:'Mann', text:'Sollen mehr Straßen für Fahrräder da sein?' },
              { wer:'Frau', text:'Unbedingt. Ich fahre jeden Tag mit dem Rad zur Arbeit und habe oft Angst neben den Autos. Mit breiteren Radwegen würden viel mehr Leute fahren.' } ],
            frage:'Was meint die Frau?',
            opt:['Es gibt genug Radwege','Autos sind wichtiger','Es braucht mehr Radwege'], loesung:2,
            stelle:'Mit breiteren Radwegen würden viel mehr Leute fahren',
            erklaerung:'Unbedingt ist eine starke Zustimmung. Der letzte Satz sagt noch einmal, was sie sich wünscht.' },
          { ort:'Radio Stadtwelle — Thema Handy für Kinder', zeilen:[
              { wer:'Frau', text:'Ab welchem Alter soll ein Kind ein Handy haben?' },
              { wer:'Mann', text:'Meine Tochter ist neun und hat noch keines. Ab der weiterführenden Schule finde ich es sinnvoll, dann fährt sie allein mit dem Bus.' } ],
            frage:'Wann soll das Kind ein Handy bekommen?',
            opt:['Mit neun Jahren','Wenn es allein Bus fährt','Gar nicht'], loesung:1,
            stelle:'dann fährt sie allein mit dem Bus',
            erklaerung:'Er nennt kein Alter, sondern einen Anlass. Die Begründung nach dann ist die Antwort.' },
          { ort:'Radio Stadtwelle — Thema Homeoffice', zeilen:[
              { wer:'Mann', text:'Arbeiten Sie lieber zu Hause oder im Büro?' },
              { wer:'Frau', text:'Zu Hause spare ich eine Stunde Fahrt, das ist toll. Trotzdem gehe ich zweimal in der Woche ins Büro, weil mir sonst die Kollegen fehlen.' } ],
            frage:'Was macht die Frau?',
            opt:['Sie arbeitet nur zu Hause','Sie arbeitet nur im Büro','Sie macht beides'], loesung:2,
            stelle:'gehe ich zweimal in der Woche ins Büro',
            erklaerung:'Trotzdem heißt: obwohl das Erste gut ist, macht sie auch das Zweite. Beides zusammen ist die Antwort.' },
          { ort:'Radio Stadtwelle — Thema Sonntagsverkauf', zeilen:[
              { wer:'Frau', text:'Sollen Geschäfte auch sonntags öffnen?' },
              { wer:'Mann', text:'Ich arbeite selbst im Einzelhandel. Für die Kunden wäre es praktisch, für uns Angestellte wäre der Sonntag dann weg. Ich bin dagegen.' } ],
            frage:'Wie steht der Mann zum Sonntagsverkauf?',
            opt:['Dagegen','Dafür','Es ist ihm egal'], loesung:0,
            stelle:'Ich bin dagegen',
            erklaerung:'Er nennt zuerst das Argument der anderen Seite. Seine eigene Meinung steht klar im letzten Satz.' } ] },

        { id:'a2t4r2', aufgaben:[
          { ort:'Radio Stadtwelle — Thema Fernsehen', zeilen:[
              { wer:'Mann', text:'Wie viel Fernsehen ist gut für Kinder?' },
              { wer:'Frau', text:'Bei uns gibt es eine halbe Stunde am Tag, am Wochenende etwas mehr. Wichtiger als die Zeit finde ich aber, dass wir zusammen schauen und reden.' } ],
            frage:'Was ist der Frau am wichtigsten?',
            opt:['Zusammen schauen und reden','Die genaue Zeit','Gar kein Fernsehen'], loesung:0,
            stelle:'dass wir zusammen schauen und reden',
            erklaerung:'Wichtiger als die Zeit sagt es direkt: Die Minuten sind nicht der Punkt. Nach aber kommt ihre eigentliche Meinung.' },
          { ort:'Radio Stadtwelle — Thema Umzug aufs Land', zeilen:[
              { wer:'Frau', text:'Würden Sie aufs Land ziehen?' },
              { wer:'Mann', text:'Die Ruhe wäre schön, und die Mieten sind günstiger. Ohne Auto geht dort aber nichts, und ich habe keinen Führerschein. Für mich kommt das nicht infrage.' } ],
            frage:'Warum zieht der Mann nicht aufs Land?',
            opt:['Es ist zu teuer','Es ist zu laut','Er hat kein Auto'], loesung:2,
            stelle:'ich habe keinen Führerschein',
            erklaerung:'Zwei Vorteile, ein Hindernis. Der Grund für sein Nein steht direkt vor dem Schlusssatz.' },
          { ort:'Radio Stadtwelle — Thema Müll trennen', zeilen:[
              { wer:'Mann', text:'Trennen Sie Ihren Müll?' },
              { wer:'Frau', text:'Ja, seit Jahren, das ist bei uns normal. Schwierig finde ich nur die Verpackungen, bei denen man nicht weiß, wohin damit.' } ],
            frage:'Was findet die Frau schwierig?',
            opt:['Manche Verpackungen','Das Trennen allgemein','Die Mülltonnen zu finden'], loesung:0,
            stelle:'Schwierig finde ich nur die Verpackungen',
            erklaerung:'Sie trennt selbstverständlich. Das Wort nur grenzt das Problem auf einen kleinen Bereich ein.' },
          { ort:'Radio Stadtwelle — Thema Sport im Verein', zeilen:[
              { wer:'Frau', text:'Sport im Verein oder allein im Studio?' },
              { wer:'Mann', text:'Im Studio kann ich gehen, wann ich will. Im Verein habe ich feste Zeiten, aber genau das hilft mir. Allein hätte ich längst aufgehört.' } ],
            frage:'Warum ist der Mann im Verein?',
            opt:['Weil es billiger ist','Weil die festen Zeiten ihm helfen','Weil er allein trainieren will'], loesung:1,
            stelle:'aber genau das hilft mir',
            erklaerung:'Feste Zeiten klingen erst wie ein Nachteil. Nach aber wird daraus sein wichtigstes Argument.' },
          { ort:'Radio Stadtwelle — Thema Urlaub', zeilen:[
              { wer:'Mann', text:'Machen Sie lieber Strand- oder Städtereisen?' },
              { wer:'Frau', text:'Mit kleinen Kindern war es immer der Strand. Jetzt sind sie größer, und wir fahren zum ersten Mal in eine Stadt — nach Prag.' } ],
            frage:'Wohin fährt die Familie in diesem Jahr?',
            opt:['An den Strand','Nach Prag','Sie bleibt zu Hause'], loesung:1,
            stelle:'wir fahren zum ersten Mal in eine Stadt',
            erklaerung:'Der Strand gehört in die Vergangenheit — hör auf war. Was jetzt gilt, steht nach jetzt.' } ] },

        { id:'a2t4r3', aufgaben:[
          { ort:'Radio Stadtwelle — Thema Kochen', zeilen:[
              { wer:'Frau', text:'Kochen Sie selbst?' },
              { wer:'Mann', text:'Unter der Woche schaffe ich das nicht, da hole ich mir oft etwas. Am Wochenende koche ich dafür richtig, meistens für die ganze Familie.' } ],
            frage:'Wann kocht der Mann selbst?',
            opt:['Jeden Tag','Nie','Am Wochenende'], loesung:2,
            stelle:'Am Wochenende koche ich dafür richtig',
            erklaerung:'Dafür stellt die beiden Zeiten gegenüber: unter der Woche nicht, am Wochenende schon.' },
          { ort:'Radio Stadtwelle — Thema Deutsch lernen', zeilen:[
              { wer:'Mann', text:'Was hilft beim Deutschlernen am meisten?' },
              { wer:'Frau', text:'Der Kurs ist die Grundlage, ohne Grammatik geht es nicht. Am meisten gebracht hat mir aber, dass ich mit meinen Nachbarn rede.' } ],
            frage:'Was hat der Frau am meisten geholfen?',
            opt:['Die Grammatik im Kurs','Filme auf Deutsch','Das Reden mit den Nachbarn'], loesung:2,
            stelle:'dass ich mit meinen Nachbarn rede',
            erklaerung:'Am meisten gebracht hat mir aber zeigt an: Jetzt kommt die eigentliche Antwort. Der Kurs wird nur als Grundlage genannt.' },
          { ort:'Radio Stadtwelle — Thema Bus und Bahn', zeilen:[
              { wer:'Frau', text:'Fahren Sie mit Bus und Bahn?' },
              { wer:'Mann', text:'Zur Arbeit ja, das klappt gut. Am Abend fährt bei uns nur noch alle Stunde etwas, da nehme ich dann doch das Auto.' } ],
            frage:'Wann nimmt der Mann das Auto?',
            opt:['Zur Arbeit','Am Abend','Nie'], loesung:1,
            stelle:'da nehme ich dann doch das Auto',
            erklaerung:'Zwei Situationen, zwei Verkehrsmittel. Das Wort da verweist auf den Abend im Satz davor.' },
          { ort:'Radio Stadtwelle — Thema Haustiere in der Wohnung', zeilen:[
              { wer:'Mann', text:'Passen Hunde in eine kleine Wohnung?' },
              { wer:'Frau', text:'Auf die Größe kommt es nicht an, finde ich. Entscheidend ist, ob jemand dreimal am Tag rausgeht. Wer zehn Stunden arbeitet, sollte keinen Hund nehmen.' } ],
            frage:'Was ist für die Frau entscheidend?',
            opt:['Die Größe der Wohnung','Die Rasse des Hundes','Die Zeit des Besitzers'], loesung:2,
            stelle:'ob jemand dreimal am Tag rausgeht',
            erklaerung:'Sie widerspricht der Frage zuerst. Entscheidend ist markiert ihr eigentliches Argument: die Zeit.' },
          { ort:'Radio Stadtwelle — Thema Nachbarschaft', zeilen:[
              { wer:'Frau', text:'Kennen Sie Ihre Nachbarn?' },
              { wer:'Mann', text:'Früher habe ich niemanden gekannt. Seit wir ein Sommerfest im Hof machen, grüßt man sich und hilft sich auch mal. Das würde ich jedem empfehlen.' } ],
            frage:'Was hat sich für den Mann geändert?',
            opt:['Er kennt jetzt seine Nachbarn','Er ist umgezogen','Er hat weniger Kontakt'], loesung:0,
            stelle:'grüßt man sich und hilft sich auch mal',
            erklaerung:'Früher steht für den alten Zustand, seit für den neuen. Die Empfehlung am Ende zeigt, dass er es gut findet.' } ] }
      ] }
  ],

  laeufe: [

    { id:'a2p1', titel:'Prüfungslauf 1', minuten:30, teile:[

      { nr:1, art:'gespraech', aufgaben:[
        { ort:'In der Apotheke', zeilen:[
            { wer:'Frau', text:'Ich brauche etwas gegen Husten, aber ohne Alkohol, bitte.' },
            { wer:'Mann', text:'Dann nehmen Sie diesen Saft hier für neun Euro fünfzig, oder die Tabletten für sechs Euro.' },
            { wer:'Frau', text:'Tabletten schlucke ich nicht gern. Ich nehme den Saft.' } ],
          frage:'Was kauft die Frau?',
          opt:['Den Saft für 9,50 €','Die Tabletten für 6 €','Nichts'], loesung:0,
          stelle:'Ich nehme den Saft',
          erklaerung:'Der Grund steht vor der Entscheidung: Tabletten mag sie nicht. Der letzte Satz nennt die Antwort.' },
        { ort:'Am Empfang einer Firma', zeilen:[
            { wer:'Mann', text:'Guten Tag, ich bin um vierzehn Uhr mit Frau Schuster verabredet.' },
            { wer:'Frau', text:'Frau Schuster ist noch in einer Besprechung. Möchten Sie im Wartebereich Platz nehmen? Es dauert etwa zehn Minuten.' },
            { wer:'Mann', text:'Gern, ich warte.' } ],
          frage:'Wie reagiert der Mann?',
          opt:['Er kommt später wieder','Er wartet','Er geht zur Besprechung'], loesung:1,
          stelle:'Gern, ich warte',
          erklaerung:'Auf den Vorschlag folgt eine kurze Zustimmung. Solche kurzen Sätze am Ende sind oft die ganze Antwort.' },
        { ort:'Im Blumenladen', zeilen:[
            { wer:'Frau', text:'Ich suche ein Geschenk für eine Kollegin, die in Rente geht.' },
            { wer:'Mann', text:'Wie wäre ein Strauß mit Rosen? Oder lieber eine Pflanze, die lange hält?' },
            { wer:'Frau', text:'Eine Pflanze ist eine gute Idee, dann hat sie länger etwas davon.' } ],
          frage:'Was nimmt die Frau?',
          opt:['Rosen','Eine Pflanze','Eine Karte'], loesung:1,
          stelle:'Eine Pflanze ist eine gute Idee',
          erklaerung:'Zwei Vorschläge, einer wird gelobt. Eine gute Idee heißt hier: Das nehme ich.' },
        { ort:'Beim Sportverein', zeilen:[
            { wer:'Mann', text:'Mein Sohn möchte Fußball spielen. Er ist sieben.' },
            { wer:'Frau', text:'Die Gruppe der Sechs- bis Achtjährigen trainiert dienstags und donnerstags um sechzehn Uhr.' },
            { wer:'Mann', text:'Dienstag hat er Musikunterricht. Kann er nur donnerstags kommen?' },
            { wer:'Frau', text:'Natürlich, einmal in der Woche ist auch in Ordnung.' } ],
          frage:'Wann kommt der Junge zum Training?',
          opt:['Dienstags','Zweimal in der Woche','Donnerstags'], loesung:2,
          stelle:'Kann er nur donnerstags kommen?',
          erklaerung:'Der Verein bietet zwei Tage an, das Kind kann nur einen. Die Trainerin stimmt zu.' },
        { ort:'An der Kinokasse', zeilen:[
            { wer:'Frau', text:'Zweimal für den Film um zwanzig Uhr, bitte.' },
            { wer:'Mann', text:'Der ist leider ausverkauft. Um zweiundzwanzig Uhr dreißig hätte ich noch Plätze.' },
            { wer:'Frau', text:'So spät ist mir zu viel. Dann kommen wir morgen wieder.' } ],
          frage:'Was machen die beiden?',
          opt:['Sie gehen um 22.30 Uhr ins Kino','Sie kommen morgen wieder','Sie gehen um 20 Uhr ins Kino'], loesung:1,
          stelle:'Dann kommen wir morgen wieder',
          erklaerung:'Beide Vorstellungen fallen weg: die erste ist voll, die zweite zu spät. Die Lösung steht im letzten Satz.' } ] },

      { nr:2, art:'durchsage', aufgaben:[
        { ort:'Im Fernzug', wer:'Frau',
          text:'Sehr geehrte Fahrgäste, wir erreichen Frankfurt Hauptbahnhof in wenigen Minuten. Der Anschlusszug nach Köln fährt heute nicht von Gleis sieben, sondern von Gleis neun.',
          satz:'Der Zug nach Köln fährt von Gleis 7.', loesung:false,
          stelle:'sondern von Gleis neun',
          erklaerung:'Die erste Zahl ist das alte Gleis. Nach sondern kommt das neue — genau darauf musst du warten.' },
        { ort:'Im Baumarkt', wer:'Mann',
          text:'Liebe Kundinnen und Kunden, heute und morgen bekommen Sie alle Gartenpflanzen zwanzig Prozent günstiger. Das Angebot gilt nicht für Werkzeug.',
          satz:'Werkzeug ist heute auch billiger.', loesung:false,
          stelle:'Das Angebot gilt nicht für Werkzeug',
          erklaerung:'Der letzte Satz nennt die Ausnahme. Solche Einschränkungen kommen fast immer am Schluss.' },
        { ort:'Im Hallenbad', wer:'Frau',
          text:'Eine Durchsage für unsere Gäste: Die Sauna öffnet heute erst um fünfzehn Uhr. Die Schwimmbecken können Sie wie gewohnt ab acht Uhr nutzen.',
          satz:'Schwimmen kann man ab 8 Uhr.', loesung:true,
          stelle:'ab acht Uhr',
          erklaerung:'Die spätere Zeit gilt nur für die Sauna. Für die Becken bleibt alles wie immer.' },
        { ort:'In der Universität', wer:'Mann',
          text:'Achtung, eine wichtige Mitteilung: Die Vorlesung von Professor Hahn beginnt heute eine Stunde später, also um elf Uhr. Der Raum bleibt derselbe.',
          satz:'Die Vorlesung findet in einem anderen Raum statt.', loesung:false,
          stelle:'Der Raum bleibt derselbe',
          erklaerung:'Geändert hat sich nur die Zeit. Der Raum wird ausdrücklich bestätigt.' },
        { ort:'Auf dem Bahnsteig', wer:'Frau',
          text:'Information für die Reisenden nach Leipzig: Der Zug ist heute besonders voll. Wir bitten Sie, auch die vorderen Wagen eins bis drei zu benutzen.',
          satz:'Die Reisenden sollen auch vorne einsteigen.', loesung:true,
          stelle:'auch die vorderen Wagen eins bis drei zu benutzen',
          erklaerung:'Benutzen heißt hier einsteigen. Die Bitte richtet sich an alle Reisenden nach Leipzig.' } ] },

      { nr:3, art:'ansage', aufgaben:[
        { von:'Kindergarten Sonnenblume', wer:'Frau',
          text:'Guten Morgen, Kindergarten Sonnenblume. Am Freitag ist unser Sommerfest. Es beginnt um fünfzehn Uhr, nicht wie im Brief um sechzehn Uhr. Bringen Sie gern einen Salat oder einen Kuchen mit.',
          frage:'Wann beginnt das Fest?',
          opt:['Um 15 Uhr','Um 16 Uhr','Am Samstag'], loesung:0,
          stelle:'Es beginnt um fünfzehn Uhr',
          erklaerung:'Die Zeit aus dem Brief gilt nicht mehr. Nach nicht wie steht immer die alte, falsche Information.' },
        { von:'Physiotherapie Aktiv', wer:'Mann',
          text:'Guten Tag, Frau Ilic, Physiotherapie Aktiv. Ihre sechs Termine sind eingetragen, immer montags um siebzehn Uhr. Der erste ist am kommenden Montag. Bitte bringen Sie ein großes Handtuch mit.',
          frage:'Was soll Frau Ilic mitbringen?',
          opt:['Eine Überweisung','Ein Handtuch','Sportschuhe'], loesung:1,
          stelle:'Bitte bringen Sie ein großes Handtuch mit',
          erklaerung:'Die Termine sind die Hauptinformation, die Bitte kommt am Ende. Gefragt ist genau dieser letzte Satz.' },
        { von:'Dein Bruder Tom', wer:'Mann',
          text:'Hey, ich bin es, Tom. Ich hole dich morgen vom Bahnhof ab. Mein Auto ist in der Werkstatt, ich komme mit dem Rad — nimm also bitte nur den kleinen Koffer mit.',
          frage:'Warum soll nur der kleine Koffer mitkommen?',
          opt:['Weil Tom mit dem Rad kommt','Weil der Zug voll ist','Weil das Auto klein ist'], loesung:0,
          stelle:'ich komme mit dem Rad',
          erklaerung:'Der Grund steht vor der Bitte. Das Auto ist in der Werkstatt — deshalb das Rad, deshalb wenig Gepäck.' },
        { von:'Volkshochschule', wer:'Frau',
          text:'Guten Tag, hier ist die Volkshochschule. Für Ihren Computerkurs brauchen wir noch die Anmeldegebühr von dreißig Euro. Sie können sie überweisen oder bar im Büro bezahlen, spätestens bis nächsten Freitag.',
          frage:'Was muss die Person tun?',
          opt:['30 Euro bezahlen','Einen Computer kaufen','Am Freitag zum Kurs kommen'], loesung:0,
          stelle:'die Anmeldegebühr von dreißig Euro',
          erklaerung:'Zwei Wege werden genannt, überweisen oder bar. Beide führen zum selben: Es geht ums Bezahlen.' },
        { von:'Tierarztpraxis Dr. Falk', wer:'Mann',
          text:'Guten Tag, Praxis Doktor Falk. Ihre Katze kann heute Nachmittag abgeholt werden, ab sechzehn Uhr. Sie hat die Narkose gut vertragen. Bitte geben Sie ihr heute noch kein Futter.',
          frage:'Was soll der Besitzer heute nicht tun?',
          opt:['Die Katze abholen','Der Katze Futter geben','Anrufen'], loesung:1,
          stelle:'Bitte geben Sie ihr heute noch kein Futter',
          erklaerung:'Abholen ist ausdrücklich erlaubt. Verboten ist nur das Füttern — achte auf kein.' } ] },

      { nr:4, art:'interview', aufgaben:[
        { ort:'Radio Stadtwelle — Thema Bücher lesen', zeilen:[
            { wer:'Frau', text:'Lesen Sie noch Bücher aus Papier?' },
            { wer:'Mann', text:'Im Urlaub nehme ich das Lesegerät mit, das ist leichter. Zu Hause habe ich aber lieber ein richtiges Buch in der Hand.' } ],
          frage:'Was liest der Mann zu Hause?',
          opt:['Auf dem Lesegerät','Er liest zu Hause nicht','Ein richtiges Buch'], loesung:2,
          stelle:'lieber ein richtiges Buch in der Hand',
          erklaerung:'Zwei Orte, zwei Antworten. Gefragt ist zu Hause — das steht nach aber.' },
        { ort:'Radio Stadtwelle — Thema Sprachen lernen im Alter', zeilen:[
            { wer:'Mann', text:'Kann man mit sechzig noch eine Sprache lernen?' },
            { wer:'Frau', text:'Natürlich, es dauert vielleicht länger als mit zwanzig. Aber ich habe mit achtundfünfzig mit Spanisch angefangen und bestelle heute im Urlaub alles selbst.' } ],
          frage:'Was sagt die Frau?',
          opt:['Im Alter lernt man nichts mehr','Man lernt es genauso schnell','Es geht, dauert aber länger'], loesung:2,
          stelle:'es dauert vielleicht länger als mit zwanzig',
          erklaerung:'Natürlich ist die Zustimmung, der Nebensatz die Einschränkung. Beides zusammen ergibt die Antwort.' },
        { ort:'Radio Stadtwelle — Thema Einkaufen auf dem Markt', zeilen:[
            { wer:'Frau', text:'Kaufen Sie auf dem Wochenmarkt ein?' },
            { wer:'Mann', text:'Das Gemüse dort schmeckt besser, keine Frage. Nur passt der Markt nicht zu meinen Arbeitszeiten, deshalb schaffe ich es höchstens einmal im Monat.' } ],
          frage:'Wie oft geht der Mann auf den Markt?',
          opt:['Jede Woche','Höchstens einmal im Monat','Nie'], loesung:1,
          stelle:'höchstens einmal im Monat',
          erklaerung:'Er findet den Markt gut, kommt aber selten hin. Höchstens heißt: nicht öfter als das.' },
        { ort:'Radio Stadtwelle — Thema Ehrenamt', zeilen:[
            { wer:'Mann', text:'Sie helfen ehrenamtlich in einer Kleiderkammer. Warum?' },
            { wer:'Frau', text:'Ich bin seit einem Jahr in Rente und hatte plötzlich viel Zeit. Zwei Nachmittage in der Woche gebe ich Kleidung aus — und bekomme dafür viele nette Gespräche.' } ],
          frage:'Wie oft hilft die Frau?',
          opt:['Zweimal in der Woche','Jeden Tag','Einmal im Monat'], loesung:0,
          stelle:'Zwei Nachmittage in der Woche',
          erklaerung:'Zwei Nachmittage in der Woche heißt zweimal wöchentlich. Das Jahr im ersten Satz gehört zur Rente, nicht zur Häufigkeit.' },
        { ort:'Radio Stadtwelle — Thema Musik im Alltag', zeilen:[
            { wer:'Frau', text:'Hören Sie beim Arbeiten Musik?' },
            { wer:'Mann', text:'Beim Aufräumen und Kochen immer. Wenn ich etwas lesen oder rechnen muss, brauche ich dagegen völlige Ruhe.' } ],
          frage:'Wann hört der Mann keine Musik?',
          opt:['Beim Kochen','Beim Lesen und Rechnen','Er hört immer Musik'], loesung:1,
          stelle:'brauche ich dagegen völlige Ruhe',
          erklaerung:'Dagegen stellt die zweite Situation der ersten gegenüber. Völlige Ruhe ist das Gegenteil von Musik.' } ] }
    ] },

    { id:'a2p2', titel:'Prüfungslauf 2', minuten:30, teile:[

      { nr:1, art:'gespraech', aufgaben:[
        { ort:'Beim Optiker', zeilen:[
            { wer:'Mann', text:'Meine Brille ist kaputt. Wie lange dauert eine neue?' },
            { wer:'Frau', text:'Die Gläser sind in etwa einer Woche da. Wenn es schneller gehen soll, kostet es dreißig Euro extra, dann sind es drei Tage.' },
            { wer:'Mann', text:'Ich fahre erst in zwei Wochen weg. Dann warte ich lieber.' } ],
          frage:'Wann bekommt der Mann seine Brille?',
          opt:['In etwa einer Woche','In drei Tagen','In zwei Wochen'], loesung:0,
          stelle:'Die Gläser sind in etwa einer Woche da',
          erklaerung:'Er verzichtet auf den schnellen Weg. Dann warte ich verweist auf die normale Dauer aus dem ersten Angebot.' },
        { ort:'Bei der Wohnungsübergabe', zeilen:[
            { wer:'Frau', text:'Hier sind zwei Schlüssel für die Wohnungstür und einer für den Keller.' },
            { wer:'Mann', text:'Und für den Briefkasten?' },
            { wer:'Frau', text:'Ach ja, der kleine hier. Also insgesamt vier.' } ],
          frage:'Wie viele Schlüssel bekommt der Mann?',
          opt:['Drei','Vier','Zwei'], loesung:1,
          stelle:'Also insgesamt vier',
          erklaerung:'Erst werden drei genannt, dann kommt einer dazu. Das Wort insgesamt fasst am Ende zusammen — darauf kannst du dich verlassen.' },
        { ort:'Im Restaurant', zeilen:[
            { wer:'Mann', text:'Haben Sie auch etwas Vegetarisches?' },
            { wer:'Frau', text:'Heute gibt es Gemüselasagne und einen großen Salat mit Ziegenkäse.' },
            { wer:'Mann', text:'Käse vertrage ich nicht. Dann nehme ich die Lasagne.' },
            { wer:'Frau', text:'Gern. Und zu trinken?' } ],
          frage:'Was bestellt der Mann?',
          opt:['Den Salat','Nur etwas zu trinken','Die Lasagne'], loesung:2,
          stelle:'Dann nehme ich die Lasagne',
          erklaerung:'Der Grund kommt zuerst: Käse geht nicht, also fällt der Salat weg.' },
        { ort:'Am Telefon mit der Versicherung', zeilen:[
            { wer:'Frau', text:'Versicherung Nordwest, was kann ich für Sie tun?' },
            { wer:'Mann', text:'Bei mir ist gestern ein Wasserschaden aufgetreten. Was muss ich machen?' },
            { wer:'Frau', text:'Machen Sie bitte Fotos und schicken Sie uns eine kurze Beschreibung per E-Mail. Ein Techniker kommt dann in den nächsten Tagen.' } ],
          frage:'Was soll der Mann zuerst tun?',
          opt:['Fotos machen und eine E-Mail schicken','Auf den Techniker warten','Noch einmal anrufen'], loesung:0,
          stelle:'Machen Sie bitte Fotos',
          erklaerung:'Der Techniker kommt später und von allein. Die Aufgabe des Kunden steht im Satz mit bitte.' },
        { ort:'In der Stadtbibliothek', zeilen:[
            { wer:'Mann', text:'Ich möchte einen Ausweis beantragen. Was kostet das?' },
            { wer:'Frau', text:'Für Erwachsene fünfzehn Euro im Jahr. Für Schüler und Studenten ist es kostenlos.' },
            { wer:'Mann', text:'Ich studiere noch. Hier ist mein Studentenausweis.' } ],
          frage:'Wie viel bezahlt der Mann?',
          opt:['15 Euro','Nichts','5 Euro'], loesung:1,
          stelle:'Für Schüler und Studenten ist es kostenlos',
          erklaerung:'Der Preis gilt nur für Erwachsene ohne Ausweis. Sein Satz ich studiere noch entscheidet die Aufgabe.' } ] },

      { nr:2, art:'durchsage', aufgaben:[
        { ort:'Am Bahnhof', wer:'Mann',
          text:'Achtung an Gleis drei: Der Regionalexpress nach Kassel fährt heute in umgekehrter Wagenreihenfolge. Die erste Klasse befindet sich vorne.',
          satz:'Die erste Klasse ist heute vorne.', loesung:true,
          stelle:'Die erste Klasse befindet sich vorne',
          erklaerung:'Der schwierige Anfang ist nur die Erklärung. Die einfache Information steht im zweiten Satz.' },
        { ort:'Im Einkaufszentrum', wer:'Frau',
          text:'Liebe Besucher, im zweiten Stock ist ein Kind abgegeben worden, ein Junge im roten Pullover. Die Eltern werden gebeten, sich beim Informationsschalter im Erdgeschoss zu melden.',
          satz:'Die Eltern sollen in den zweiten Stock kommen.', loesung:false,
          stelle:'sich beim Informationsschalter im Erdgeschoss zu melden',
          erklaerung:'Der zweite Stock ist der Fundort, das Erdgeschoss der Treffpunkt. Zwei Stockwerke in einem Text — hör auf das Wort melden.' },
        { ort:'Im Freibad', wer:'Mann',
          text:'Wegen des Gewitters müssen wir das Freibad in fünfzehn Minuten schließen. Ihre Eintrittskarte gilt morgen noch einmal.',
          satz:'Die Besucher müssen morgen neu bezahlen.', loesung:false,
          stelle:'Ihre Eintrittskarte gilt morgen noch einmal',
          erklaerung:'Gilt noch einmal heißt: Man darf mit derselben Karte wiederkommen. Bezahlen muss man also nicht.' },
        { ort:'In der Firma', wer:'Frau',
          text:'Eine Mitteilung an alle Mitarbeiterinnen und Mitarbeiter: Am Montag wird die Software erneuert. Der Computer steht Ihnen bis mittags nicht zur Verfügung, das Telefon funktioniert normal.',
          satz:'Am Montag kann man vormittags nicht am Computer arbeiten.', loesung:true,
          stelle:'Der Computer steht Ihnen bis mittags nicht zur Verfügung',
          erklaerung:'Bis mittags nicht heißt: den ganzen Vormittag nicht. Das Telefon ist die Ausnahme, nach der nicht gefragt wird.' },
        { ort:'In der Turnhalle', wer:'Mann',
          text:'Liebe Eltern, das Turnier beginnt gleich. Die Sitzplätze auf der Tribüne sind frei, aber wir bitten Sie, den Bereich hinter den Toren nicht zu betreten.',
          satz:'Man darf sich überall hinstellen.', loesung:false,
          stelle:'den Bereich hinter den Toren nicht zu betreten',
          erklaerung:'Überall ist zu absolut. Ein Bereich wird ausdrücklich ausgenommen — das steht nach aber.' } ] },

      { nr:3, art:'ansage', aufgaben:[
        { von:'Elektro Sanchez', wer:'Mann',
          text:'Guten Tag, hier ist Elektro Sanchez. Wir wollten heute Ihre Waschmaschine anschließen. Unser Kollege ist leider krank geworden. Passt Ihnen Donnerstag um neun oder lieber um vierzehn Uhr?',
          frage:'Warum ruft die Firma an?',
          opt:['Die Waschmaschine ist kaputt','Der Termin heute fällt aus','Die Rechnung fehlt'], loesung:1,
          stelle:'Unser Kollege ist leider krank geworden',
          erklaerung:'Der Grund steht in der Mitte, die Folge in der Frage danach. Wer einen neuen Termin anbietet, sagt damit: Der alte gilt nicht mehr.' },
        { von:'Frau Kaya von der Schule', wer:'Frau',
          text:'Guten Tag, hier ist Frau Kaya, die Klassenlehrerin. Mir ist aufgefallen, dass Ihre Tochter in Mathematik Schwierigkeiten hat. Können wir nächste Woche in Ruhe sprechen? Rufen Sie mich bitte zurück.',
          frage:'Was möchte die Lehrerin?',
          opt:['Ein Gespräch mit den Eltern','Eine Entschuldigung','Geld für den Ausflug'], loesung:0,
          stelle:'Können wir nächste Woche in Ruhe sprechen?',
          erklaerung:'Mathematik ist der Anlass, nicht der Wunsch. Der Wunsch steht in der Frage: sprechen.' },
        { von:'Deine Freundin Marta', wer:'Frau',
          text:'Hallo! Wegen Samstag: Meine Schwester kommt doch zu Besuch. Können wir unser Frühstück auf Sonntag verschieben? Dann bringe ich auch den Kuchen mit, den ich dir versprochen habe.',
          frage:'Was möchte Marta?',
          opt:['Am Sonntag frühstücken','Das Frühstück absagen','Am Samstag früher kommen'], loesung:0,
          stelle:'unser Frühstück auf Sonntag verschieben',
          erklaerung:'Verschieben heißt: nicht absagen, sondern an einem anderen Tag machen. Der neue Tag steht direkt dabei.' },
        { von:'Bürgeramt der Stadt', wer:'Mann',
          text:'Guten Tag, Bürgeramt. Ihr neuer Personalausweis ist da. Sie können ihn ohne Termin abholen, montags bis freitags von acht bis zwölf Uhr. Bringen Sie den alten Ausweis mit.',
          frage:'Wann kann man den Ausweis abholen?',
          opt:['Nur mit Termin','Vormittags an Werktagen','Am Wochenende'], loesung:1,
          stelle:'montags bis freitags von acht bis zwölf Uhr',
          erklaerung:'Montags bis freitags sind die Werktage, acht bis zwölf ist der Vormittag. Das Wort ohne schließt die Antwort mit Termin aus.' },
        { von:'Hotel Alpenblick', wer:'Frau',
          text:'Guten Tag, Hotel Alpenblick. Wir bestätigen Ihr Doppelzimmer vom vierten bis zum siebten August. Anreise ist ab vierzehn Uhr möglich. Falls Sie später als zwanzig Uhr kommen, sagen Sie uns bitte Bescheid.',
          frage:'Was soll der Gast tun, wenn er um 21 Uhr ankommt?',
          opt:['Bescheid sagen','Früher anreisen','Ein anderes Zimmer nehmen'], loesung:0,
          stelle:'Falls Sie später als zwanzig Uhr kommen, sagen Sie uns bitte Bescheid',
          erklaerung:'Einundzwanzig Uhr ist später als zwanzig Uhr — also gilt der Satz mit falls. Solche Bedingungssätze musst du auf deine Situation übertragen.' } ] },

      { nr:4, art:'interview', aufgaben:[
        { ort:'Radio Stadtwelle — Thema Autofrei in der Innenstadt', zeilen:[
            { wer:'Mann', text:'Soll die Innenstadt autofrei werden?' },
            { wer:'Frau', text:'Als Mutter finde ich weniger Autos gut. Nur muss dann der Bus öfter fahren, sonst kommen ältere Leute gar nicht mehr in die Stadt.' } ],
          frage:'Was fordert die Frau?',
          opt:['Mehr Parkplätze','Alles soll bleiben','Bessere Busverbindungen'], loesung:2,
          stelle:'muss dann der Bus öfter fahren',
          erklaerung:'Sie ist grundsätzlich dafür. Ihre Bedingung steht nach nur — das ist hier so stark wie ein aber.' },
        { ort:'Radio Stadtwelle — Thema Nachbarn im Haus', zeilen:[
            { wer:'Frau', text:'Stört Sie Lärm im Haus?' },
            { wer:'Mann', text:'Kinder, die im Hof spielen, stören mich überhaupt nicht. Was mich stört, ist die Waschmaschine um Mitternacht.' } ],
          frage:'Was stört den Mann?',
          opt:['Spielende Kinder','Die Waschmaschine nachts','Nichts'], loesung:1,
          stelle:'ist die Waschmaschine um Mitternacht',
          erklaerung:'Der erste Satz nennt, was ihn NICHT stört. Was mich stört, ist leitet die Antwort ein.' },
        { ort:'Radio Stadtwelle — Thema Handy am Esstisch', zeilen:[
            { wer:'Mann', text:'Darf das Handy mit an den Tisch?' },
            { wer:'Frau', text:'Bei uns liegt es in einer Kiste im Flur. Am Anfang gab es Streit, inzwischen vermisst es niemand mehr.' } ],
          frage:'Wie ist es heute in der Familie?',
          opt:['Es gibt oft Streit','Alle haben das Handy dabei','Niemand vermisst das Handy'], loesung:2,
          stelle:'inzwischen vermisst es niemand mehr',
          erklaerung:'Am Anfang gehört zur Vergangenheit, inzwischen zur Gegenwart. Gefragt ist heute.' },
        { ort:'Radio Stadtwelle — Thema Arbeiten am Wochenende', zeilen:[
            { wer:'Frau', text:'Sie arbeiten als Krankenpfleger auch sonntags. Wie geht es Ihnen damit?' },
            { wer:'Mann', text:'Der Dienst am Wochenende gehört dazu, das war mir vorher klar. Schwer ist eher, dass ich nie weiß, wie der nächste Monat aussieht.' } ],
          frage:'Was findet der Mann schwierig?',
          opt:['Die Arbeit am Sonntag','Die unsichere Planung','Die langen Wege'], loesung:1,
          stelle:'dass ich nie weiß, wie der nächste Monat aussieht',
          erklaerung:'Den Sonntagsdienst nimmt er hin. Schwer ist eher zeigt an, wo das eigentliche Problem liegt.' },
        { ort:'Radio Stadtwelle — Thema Garten in der Stadt', zeilen:[
            { wer:'Mann', text:'Sie haben einen Schrebergarten. Lohnt sich das?' },
            { wer:'Frau', text:'Das Gemüse ist nicht billiger als im Laden, wenn man ehrlich rechnet. Aber ich bin an der frischen Luft und kenne inzwischen den halben Verein.' } ],
          frage:'Warum hat die Frau den Garten?',
          opt:['Weil sie draußen ist und Leute trifft','Weil das Gemüse billiger ist','Weil sie einen Beruf im Garten hat'], loesung:0,
          stelle:'ich bin an der frischen Luft und kenne inzwischen den halben Verein',
          erklaerung:'Den Geldgrund schließt sie selbst aus. Nach aber kommen ihre wirklichen Gründe.' } ] }
    ] }
  ]
};
