/* ============================================================
   hoeren-c1.js — Prüfungstraining Hören auf C1

   Das letzte Feld, das in der Matrix A1–C1 noch leer war:
   Lesen, Schreiben und Sprechen gab es auf C1 schon, Hören nicht.

   Gebaut nach dem Modellsatz des Goethe-Zertifikats C1 (modular),
   nicht nach der alten C1-Prüfung. Das Modul Hören dort:
   40 Minuten, 100 Punkte, vier Teile mit zusammen 30 Aufgaben.
     Teil 1  Podcast über neue Bücher — 6 Aufgaben, einmal hören,
             jede Aussage einem von drei Büchern zuordnen
     Teil 2  Radiointerview — 9 Aufgaben, zweimal hören,
             stimmt / stimmt nicht / dazu wird nichts gesagt
     Teil 3  Gespräch mehrerer Personen — 8 Aufgaben, je Abschnitt
             einmal, Auswahl aus drei Möglichkeiten
     Teil 4  Vortrag — 7 Aufgaben, zweimal hören, Auswahl aus drei

   Im Training sind die Texte kürzer und in sich geschlossen —
   genau wie auf A1 bis B2. Es geht darum, die Hörhaltung zu üben,
   nicht darum, eine ganze Prüfung nachzustellen. Die Anzahl der
   Hördurchgänge (mal) ist aber übernommen: Teil 1 und 3 gibt es
   wirklich nur einmal.

   Gesprochen wird über die Sprachausgabe des Browsers
   (window.sagen), wie in den anderen Hör-Dateien auch.
   ============================================================ */
window.HOEREN_C1 = {
  niveau: 'C1',
  pruefung: 'Goethe-Zertifikat C1 · telc Deutsch C1 Hochschule',
  minuten: 40,
  punkte: 100,

  stufen: [
    { nr:1, titel:'Zuordnen statt verstehen', zeichen:'🎧',
      was:'Drei Bücher, drei Projekte, drei Fachleute — und eine Aussage, die nur zu einem davon passt. Auf C1 hörst du nicht mehr nach Einzelheiten, sondern nach Zugehörigkeit. Das Wort, das in der Aufgabe steht, kommt im Text fast nie vor.' },
    { nr:2, titel:'Stimmt, stimmt nicht, steht nicht da', zeichen:'⚖️',
      was:'Der dritte Fall ist der schwerste und kostet in der Prüfung die meisten Punkte. Etwas klingt plausibel, wurde aber nie gesagt. Wer dann aus dem eigenen Weltwissen antwortet, liegt falsch.' },
    { nr:3, titel:'Mehrere Stimmen', zeichen:'🗣️',
      was:'Drei Personen reden, zwei davon sind sich scheinbar einig. Du musst hören, wer wem zustimmt, wer nur höflich ist und wer die Position leise verlässt.' },
    { nr:4, titel:'Der Vortrag', zeichen:'📊',
      was:'Gliederungssignale, Zahlen und Einschränkungen. Ein Vortrag auf C1 nennt selten das Fazit zuerst — und fast jede Zahl bekommt hinterher eine Relativierung.' }
  ],

  bloecke: [

    { id:'s1b1', stufe:1, titel:'Wem gehört die Aussage?', kurz:'Zuordnen unter drei Möglichkeiten',
      ziel:'Du ordnest eine Aussage dem richtigen von drei Gegenständen zu, auch wenn kein Wort wörtlich wiederkehrt.',
      zeichen:'🎧', farbe:'turq', mal:1, aufgaben:[
      { art:'hoerwahl', ort:'Literaturpodcast', wer:'Frau',
        text:'Bei Hallers Roman habe ich zweihundert Seiten gebraucht, bis ich drin war. Danach allerdings wollte ich nicht mehr aufhören. Bei Winters Essayband war es umgekehrt: großartiger Anfang, und dann wiederholt er sich.',
        frage:'Welches Buch wird am Ende schwächer?',
        opt:['Hallers Roman','Winters Essayband','beide'], loesung:1,
        stelle:'großartiger Anfang, und dann wiederholt er sich',
        erklaerung:'„Umgekehrt" dreht das Urteil: Haller wird besser, Winter schlechter.' },
      { art:'hoerwahl', ort:'Literaturpodcast', wer:'Mann',
        text:'Was mich bei dem Gedichtband überrascht hat, ist die Sprache — sie ist karg, fast spröde. Man muss sich darauf einlassen. Die beiden anderen Bücher nehmen einen viel schneller mit, aber sie bleiben auch flacher.',
        frage:'Was sagt der Sprecher über den Gedichtband?',
        opt:['Er ist leicht zugänglich.','Er verlangt Einlassung, bietet aber mehr Tiefe.','Er ist sprachlich belanglos.'], loesung:1,
        stelle:'Man muss sich darauf einlassen',
        erklaerung:'„karg", „spröde", „einlassen" gegen „schneller mit" und „flacher" — das ist das Gegensatzpaar.' },
      { art:'hoerwahl', ort:'Sachbuchrunde', wer:'Frau',
        text:'Das eine Buch stützt sich auf Interviews, das zweite auf Statistik. Mir hat das dritte am meisten gegeben, weil es beides verbindet, ohne daraus eine Methode zu machen.',
        frage:'Was lobt die Sprecherin am dritten Buch?',
        opt:['Die große Zahl der Interviews.','Die Verbindung beider Zugänge.','Die klare Methodik.'], loesung:1,
        stelle:'weil es beides verbindet',
        erklaerung:'„ohne daraus eine Methode zu machen" ist sogar ein Argument gegen Antwort c.' },
      { art:'hoerwahl', ort:'Podcast über Ausstellungen', wer:'Mann',
        text:'Die Schau im Westflügel ist klug kuratiert, aber sie braucht Vorwissen. Wer zum ersten Mal mit dem Thema zu tun hat, ist in der kleinen Kabinettausstellung nebenan deutlich besser aufgehoben.',
        frage:'Was wird Einsteigern empfohlen?',
        opt:['Die Schau im Westflügel.','Die Kabinettausstellung.','Beides nacheinander.'], loesung:1,
        stelle:'deutlich besser aufgehoben',
        erklaerung:'„Wer zum ersten Mal …" bezeichnet die Einsteiger; die Empfehlung steht direkt dahinter.' },
      { art:'hoerwahl', ort:'Podcast über Hörbücher', wer:'Frau',
        text:'Bei der ersten Lesung trägt die Stimme den Text, bei der zweiten arbeitet sie gegen ihn. Die dritte ist am unauffälligsten — und gerade deshalb hält man sie am längsten aus.',
        frage:'Welche Lesung eignet sich für langes Hören?',
        opt:['Die erste.','Die zweite.','Die dritte.'], loesung:2,
        stelle:'am längsten aus',
        erklaerung:'„unauffällig" wird hier positiv gewendet — das ist die C1-Bewegung.' },
      { art:'hoerwahl', ort:'Wissenschaftspodcast', wer:'Mann',
        text:'Die Studie aus Lund ist sauber gemacht, nur eben klein. Die Rotterdamer Arbeit hat die größere Stichprobe, dafür ein schwächeres Design. Belastbar ist streng genommen keine von beiden allein.',
        frage:'Was sagt der Sprecher über die beiden Studien?',
        opt:['Lund ist belastbar, Rotterdam nicht.','Beide haben je eine Schwäche.','Rotterdam ersetzt Lund.'], loesung:1,
        stelle:'Belastbar ist streng genommen keine von beiden allein',
        erklaerung:'Zweimal „nur eben" und „dafür" — jede Stärke bekommt ihre Einschränkung.' },
      { art:'hoerwahl', ort:'Podcast über Serien', wer:'Frau',
        text:'Staffel eins war ein Versprechen, Staffel zwei hat es eingelöst, und Staffel drei lebt davon, dass man die ersten beiden gesehen hat. Für sich genommen trägt sie nicht.',
        frage:'Was gilt für Staffel drei?',
        opt:['Sie funktioniert nur im Zusammenhang.','Sie ist die stärkste.','Sie eignet sich als Einstieg.'], loesung:0,
        stelle:'Für sich genommen trägt sie nicht',
        erklaerung:'„Für sich genommen" ist das Signal: allein nicht, im Zusammenhang schon.' },
      { art:'hoerwahl', ort:'Podcast über Städte', wer:'Mann',
        text:'In Leipzig hat man früh auf Zwischennutzung gesetzt, in Dresden eher auf Rekonstruktion. Was in Halle passiert, ist noch nicht entschieden — und genau das macht es im Moment am interessantesten.',
        frage:'Welche Stadt findet der Sprecher gerade am spannendsten?',
        opt:['Leipzig','Dresden','Halle'], loesung:2,
        stelle:'noch nicht entschieden',
        erklaerung:'Die Offenheit selbst ist das Argument. Nicht das Ergebnis macht es interessant, sondern dass keines feststeht.' },
      { art:'hoerwahl', ort:'Podcast über Musik', wer:'Frau',
        text:'Das Debüt war roh, das zweite Album poliert bis zur Unkenntlichkeit. Beim neuen hört man endlich wieder, dass da Menschen im Raum stehen.',
        frage:'Was gefällt der Sprecherin am neuen Album?',
        opt:['Die saubere Produktion.','Die hörbare Lebendigkeit.','Die Rückkehr zum rohen Debütklang.'], loesung:1,
        stelle:'dass da Menschen im Raum stehen',
        erklaerung:'Nicht „wie das Debüt", sondern „wieder lebendig" — Antwort c ginge einen Schritt zu weit.' },
      { art:'hoerwahl', ort:'Podcast über Fachliteratur', wer:'Mann',
        text:'Band eins erklärt die Grundlagen, Band zwei die Anwendung. Wer das Thema unterrichtet, kommt um Band drei nicht herum, auch wenn er stellenweise schwer zu lesen ist.',
        frage:'Welcher Band ist für Lehrende unverzichtbar?',
        opt:['Band eins','Band zwei','Band drei'], loesung:2,
        stelle:'kommt um Band drei nicht herum',
        erklaerung:'„kommt nicht herum um" heißt: unverzichtbar, trotz der Einschränkung danach.' }
    ]},

    { id:'s2b1', stufe:2, titel:'Steht das wirklich da?', kurz:'stimmt · stimmt nicht · dazu wird nichts gesagt',
      ziel:'Du unterscheidest, was gesagt wurde, was widerlegt wurde und was nur plausibel klingt.',
      zeichen:'⚖️', farbe:'gold', mal:2, aufgaben:[
      { art:'hoerwahl', ort:'Radiointerview mit einer Hirnforscherin', wer:'Frau',
        text:'Wir sehen bei den Versuchspersonen nach dem Training deutlich kürzere Reaktionszeiten. Ob sich das auf den Alltag überträgt, haben wir nicht untersucht — das wäre die nächste Frage.',
        frage:'Aussage: Das Training wirkt sich auch im Alltag aus.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
        stelle:'haben wir nicht untersucht',
        erklaerung:'Nicht untersucht heißt weder ja noch nein. Wer hier „stimmt nicht" wählt, legt der Forscherin etwas in den Mund.' },
      { art:'hoerwahl', ort:'Radiointerview mit einem Stadtplaner', wer:'Mann',
        text:'Die Zahl der Radwege hat sich in zehn Jahren verdoppelt. Trotzdem fahren nicht mehr Menschen Rad als vorher — das Netz hat Lücken an genau den Stellen, wo es darauf ankäme.',
        frage:'Aussage: Mehr Radwege haben zu mehr Radfahrenden geführt.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
        stelle:'Trotzdem fahren nicht mehr Menschen Rad als vorher',
        erklaerung:'Hier wird ausdrücklich widersprochen. „Trotzdem" kündigt genau das an.' },
      { art:'hoerwahl', ort:'Radiointerview mit einer Ökonomin', wer:'Frau',
        text:'Der Fachkräftemangel ist in der Pflege am deutlichsten, im Handwerk ebenfalls spürbar. Über die Industrie kann ich Ihnen aus unseren Daten nichts Belastbares sagen.',
        frage:'Aussage: In der Industrie fehlen keine Fachkräfte.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
        stelle:'nichts Belastbares sagen',
        erklaerung:'Keine Daten ist nicht dasselbe wie kein Mangel.' },
      { art:'hoerwahl', ort:'Radiointerview mit einem Klimaforscher', wer:'Mann',
        text:'Das Ziel für 2030 halte ich für erreichbar, aber nur mit Maßnahmen, die politisch zurzeit niemand ernsthaft vorschlägt. Technisch ist es keine Frage.',
        frage:'Aussage: Technisch ist das Ziel machbar.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:0,
        stelle:'Technisch ist es keine Frage',
        erklaerung:'„keine Frage" ist volle Zustimmung — die Einschränkung betrifft die Politik, nicht die Technik.' },
      { art:'hoerwahl', ort:'Radiointerview mit einer Archäologin', wer:'Frau',
        text:'Die Funde stammen sicher aus dem zweiten Jahrhundert. Wer dort gelebt hat, wissen wir nicht; die Siedlungsreste sind zu stark gestört.',
        frage:'Aussage: Die Fundstelle wurde von einer bekannten Gruppe bewohnt.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
        stelle:'Wer dort gelebt hat, wissen wir nicht',
        erklaerung:'Hier ist das ausdrückliche Nichtwissen selbst die Aussage — die Behauptung wird also verneint, nicht offengelassen.' },
      { art:'hoerwahl', ort:'Radiointerview mit einem Verkehrsexperten', wer:'Mann',
        text:'Tempo 30 senkt die Zahl schwerer Unfälle, das ist gut belegt. Dass der Verkehr dadurch insgesamt langsamer wird, stimmt übrigens nicht — der Fluss wird gleichmäßiger.',
        frage:'Aussage: Mit Tempo 30 braucht man insgesamt länger.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
        stelle:'stimmt übrigens nicht',
        erklaerung:'Das „übrigens" kündigt an, dass er eine verbreitete Annahme korrigiert.' },
      { art:'hoerwahl', ort:'Radiointerview mit einer Medizinerin', wer:'Frau',
        text:'Die Nebenwirkungen sind selten und meist mild. Zur Anwendung bei Kindern liegen noch keine Studien vor, deshalb raten wir dort vorerst ab.',
        frage:'Aussage: Bei Kindern ist das Mittel nachweislich gefährlich.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
        stelle:'liegen noch keine Studien vor',
        erklaerung:'Vorsicht aus Unkenntnis ist kein Nachweis von Gefahr. Das ist der klassische dritte Fall.' },
      { art:'hoerwahl', ort:'Radiointerview mit einem Historiker', wer:'Mann',
        text:'Den Brief kannte die Forschung schon lange. Neu ist nur, dass wir jetzt wissen, an wen er gerichtet war — und das ändert die Lesart des ganzen Bestands.',
        frage:'Aussage: Der Brief wurde kürzlich entdeckt.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
        stelle:'kannte die Forschung schon lange',
        erklaerung:'Neu ist die Zuordnung, nicht der Fund. Genau solche Verschiebungen prüft Teil 2.' },
      { art:'hoerwahl', ort:'Radiointerview mit einer Bildungsforscherin', wer:'Frau',
        text:'Kleinere Klassen helfen vor allem den schwächeren Kindern. Für die Leistungsspitze sehen wir keinen Effekt. Was das kostet, ist nicht meine Frage, das müssen andere beantworten.',
        frage:'Aussage: Kleinere Klassen sind zu teuer.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
        stelle:'ist nicht meine Frage',
        erklaerung:'Sie weicht der Kostenfrage ausdrücklich aus. Ausweichen ist keine Antwort.' },
      { art:'hoerwahl', ort:'Radiointerview mit einem Energieexperten', wer:'Mann',
        text:'Die Speicher reichen heute für wenige Stunden, nicht für Tage. Dass wir sie brauchen, bestreitet niemand mehr; die Debatte dreht sich nur noch um das Wie.',
        frage:'Aussage: Über die Notwendigkeit von Speichern wird noch gestritten.',
        opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
        stelle:'bestreitet niemand mehr',
        erklaerung:'„niemand mehr" beendet den Streit über das Ob; strittig ist nur noch das Wie.' }
    ]},

    { id:'s3b1', stufe:3, titel:'Wer sagt was?', kurz:'Positionen in einem Gespräch auseinanderhalten',
      ziel:'Du erkennst, wer zustimmt, wer nur höflich ist und wer seine Position still räumt.',
      zeichen:'🗣️', farbe:'rose', mal:1, aufgaben:[
      { art:'hoerwahl', ort:'Planungsrunde', wer:'Frau',
        text:'Ich will dem Vorschlag nicht im Weg stehen. Nur sollten wir ehrlich sagen, dass wir damit das Budget für die zweite Phase aufbrauchen.',
        frage:'Wie steht die Sprecherin zu dem Vorschlag?',
        opt:['Sie lehnt ihn ab.','Sie trägt ihn mit, weist aber auf die Folgen hin.','Sie unterstützt ihn vorbehaltlos.'], loesung:1,
        stelle:'nicht im Weg stehen',
        erklaerung:'„Ich will nicht im Weg stehen" ist Zustimmung ohne Begeisterung; das „Nur" bringt die Bedingung.' },
      { art:'hoerwahl', ort:'Redaktionskonferenz', wer:'Mann',
        text:'Das Thema ist richtig, keine Frage. Die Frage ist nur, ob wir die Richtigen dafür haben. Ich würde es nicht in dieser Woche machen.',
        frage:'Was schlägt der Sprecher vor?',
        opt:['Das Thema fallen lassen.','Es später und mit anderen Leuten machen.','Sofort beginnen.'], loesung:1,
        stelle:'nicht in dieser Woche',
        erklaerung:'Er bestreitet das Thema nicht, sondern Zeitpunkt und Besetzung.' },
      { art:'hoerwahl', ort:'Teamgespräch', wer:'Frau',
        text:'Also, ich hatte das anders im Kopf, aber wenn alle anderen das so sehen, dann machen wir das eben so.',
        frage:'Was tut die Sprecherin?',
        opt:['Sie beharrt auf ihrer Position.','Sie gibt ihre Position auf.','Sie schlägt einen Kompromiss vor.'], loesung:1,
        stelle:'dann machen wir das eben so',
        erklaerung:'Das „eben" verrät, dass sie nachgibt, ohne überzeugt zu sein. Auf C1 wird genau das geprüft.' },
      { art:'hoerwahl', ort:'Podiumsgespräch', wer:'Mann',
        text:'Frau Kessler hat völlig recht, was die Zahlen angeht. Wenn man allerdings dieselben Zahlen über zwanzig Jahre anschaut, sieht die Sache anders aus.',
        frage:'Wie verhält sich der Sprecher zu Frau Kessler?',
        opt:['Er stimmt ihr vollständig zu.','Er widerspricht ihr höflich.','Er versteht sie nicht.'], loesung:1,
        stelle:'sieht die Sache anders aus',
        erklaerung:'Zustimmung zuerst, Widerspruch danach — „allerdings" ist das Scharnier.' },
      { art:'hoerwahl', ort:'Projektbesprechung', wer:'Frau',
        text:'Ich übernehme das gern, sofern ich die Auswertung nicht auch noch machen muss. Zwei Sachen gleichzeitig gehen nicht.',
        frage:'Unter welcher Bedingung übernimmt sie die Aufgabe?',
        opt:['Wenn sie mehr Zeit bekommt.','Wenn sie die Auswertung abgeben kann.','Ohne Bedingung.'], loesung:1,
        stelle:'sofern ich die Auswertung nicht auch noch machen muss',
        erklaerung:'„sofern" ist das Bedingungswort. Zeit wird nicht erwähnt.' },
      { art:'hoerwahl', ort:'Gespräch unter Kollegen', wer:'Mann',
        text:'Das haben wir vor drei Jahren schon einmal versucht. Ich sage nicht, dass es wieder scheitert — nur sollten wir wissen, warum es damals schiefging.',
        frage:'Was will der Sprecher?',
        opt:['Den Versuch verhindern.','Vorher die alten Gründe klären.','Noch einmal genau dasselbe tun.'], loesung:1,
        stelle:'warum es damals schiefging',
        erklaerung:'„Ich sage nicht, dass …" nimmt die Ablehnung ausdrücklich zurück.' },
      { art:'hoerwahl', ort:'Elternabend', wer:'Frau',
        text:'Ich finde den Ausflug eine schöne Idee. Was mich beschäftigt, ist nur die Aufsicht: zwei Begleitpersonen auf achtundzwanzig Kinder ist wenig.',
        frage:'Worum geht es der Sprecherin?',
        opt:['Um die Kosten.','Um die Aufsicht.','Um das Ziel des Ausflugs.'], loesung:1,
        stelle:'ist nur die Aufsicht',
        erklaerung:'Die Zahl ist das Argument, nicht das Thema. Kosten kommen nicht vor.' },
      { art:'hoerwahl', ort:'Diskussion im Verein', wer:'Mann',
        text:'Dass wir etwas ändern müssen, bestreite ich gar nicht. Ich bestreite, dass ausgerechnet die Beiträge der richtige Hebel sind.',
        frage:'Was lehnt der Sprecher ab?',
        opt:['Jede Veränderung.','Die Erhöhung der Beiträge als Mittel.','Die Diskussion insgesamt.'], loesung:1,
        stelle:'ausgerechnet die Beiträge',
        erklaerung:'Zweimal „bestreite" mit unterschiedlichem Bezug — der zweite zählt.' },
      { art:'hoerwahl', ort:'Übergabegespräch', wer:'Frau',
        text:'Frau Adler kennt den Vorgang am besten. Sie ist allerdings bis Ende des Monats im Ausland, deshalb müsste es jemand anders übernehmen — zumindest vorläufig.',
        frage:'Wer soll den Vorgang jetzt übernehmen?',
        opt:['Frau Adler.','Eine andere Person, vorübergehend.','Niemand, es wird gewartet.'], loesung:1,
        stelle:'zumindest vorläufig',
        erklaerung:'„zumindest vorläufig" beantwortet genau die Nachfrage, ob es dauerhaft ist.' },
      { art:'hoerwahl', ort:'Gespräch im Betriebsrat', wer:'Mann',
        text:'Ich habe im Protokoll gelesen, dass die Zusage mündlich erfolgt sein soll. Mündlich ist mir für diesen Punkt zu wenig.',
        frage:'Was fordert der Sprecher?',
        opt:['Eine schriftliche Zusage.','Eine neue Abstimmung.','Die Streichung des Punktes.'], loesung:0,
        stelle:'Mündlich ist mir für diesen Punkt zu wenig',
        erklaerung:'Das Gegenteil von mündlich ist hier gemeint, ohne dass „schriftlich" fällt. Typisch C1.' }
    ]},

    { id:'s4b1', stufe:4, titel:'Zahlen, Signale, Einschränkungen', kurz:'Einem Vortrag folgen',
      ziel:'Du hältst im Vortrag Gliederung, Zahlen und Relativierungen auseinander.',
      zeichen:'📊', farbe:'indigo', mal:2, aufgaben:[
      { art:'hoerwahl', ort:'Vortrag über Mobilität', wer:'Frau',
        text:'Lassen Sie mich mit dem Befund beginnen und erst danach zu den Ursachen kommen. Der Befund lautet: Die Wege werden nicht mehr, sie werden länger.',
        frage:'Was kündigt die Sprecherin an?',
        opt:['Zuerst Ursachen, dann Befund.','Zuerst Befund, dann Ursachen.','Nur den Befund.'], loesung:1,
        stelle:'erst danach zu den Ursachen',
        erklaerung:'Gliederungssignale am Anfang sagen dir, worauf du warten musst.' },
      { art:'hoerwahl', ort:'Vortrag über Ernährung', wer:'Mann',
        text:'Der Verbrauch ist um vierzehn Prozent gestiegen — allerdings von einem sehr niedrigen Ausgangswert. In absoluten Zahlen reden wir über wenige Kilogramm im Jahr.',
        frage:'Wie ordnet der Sprecher die vierzehn Prozent ein?',
        opt:['Als großen Sprung.','Als wenig aussagekräftig wegen des Ausgangswerts.','Als Rückgang.'], loesung:1,
        stelle:'von einem sehr niedrigen Ausgangswert',
        erklaerung:'Auf C1 folgt fast jeder Prozentzahl eine Relativierung. Sie ist die eigentliche Information.' },
      { art:'hoerwahl', ort:'Vortrag über Wohnungsbau', wer:'Frau',
        text:'Drei Faktoren spielen zusammen: die Baukosten, die Zinsen und das Bauland. Die ersten beiden kennen Sie aus der Presse; über den dritten wird kaum gesprochen, dabei ist er der entscheidende.',
        frage:'Welchen Faktor hält die Sprecherin für den wichtigsten?',
        opt:['Die Baukosten.','Die Zinsen.','Das Bauland.'], loesung:2,
        stelle:'dabei ist er der entscheidende',
        erklaerung:'„dabei" führt den Gegensatz ein: wenig besprochen, aber am wichtigsten.' },
      { art:'hoerwahl', ort:'Vortrag über Digitalisierung', wer:'Mann',
        text:'Ich komme zum letzten Punkt, und er ist mir der liebste: Technik scheitert selten an der Technik. Sie scheitert an Zuständigkeiten.',
        frage:'Woran scheitert Digitalisierung laut Vortrag meistens?',
        opt:['An der Technik.','An den Zuständigkeiten.','Am Geld.'], loesung:1,
        stelle:'Sie scheitert an Zuständigkeiten',
        erklaerung:'„Ich komme zum letzten Punkt" markiert die Pointe — dort steht fast immer die Prüfungsfrage.' },
      { art:'hoerwahl', ort:'Vortrag über Bildung', wer:'Frau',
        text:'Zwei Drittel der Befragten halten das Angebot für ausreichend. Das klingt gut, bis man sieht, dass nur ein Fünftel es jemals genutzt hat.',
        frage:'Was folgt aus der zweiten Zahl?',
        opt:['Das Urteil beruht meist nicht auf eigener Erfahrung.','Das Angebot wird stark genutzt.','Zwei Drittel sind unzufrieden.'], loesung:0,
        stelle:'nur ein Fünftel es jemals genutzt hat',
        erklaerung:'„Das klingt gut, bis …" ist die Einladung, die erste Zahl zu misstrauen.' },
      { art:'hoerwahl', ort:'Vortrag über Energie', wer:'Mann',
        text:'Bevor ich zu den Netzen komme, noch ein Wort zur Speicherung — ohne sie ergibt alles Weitere keinen Sinn.',
        frage:'Was sagt der Sprecher über die Reihenfolge?',
        opt:['Die Netze sind wichtiger als die Speicherung.','Die Speicherung ist Voraussetzung für alles Weitere.','Beides hängt nicht zusammen.'], loesung:1,
        stelle:'ohne sie ergibt alles Weitere keinen Sinn',
        erklaerung:'Ein Einschub kann die Hauptsache enthalten — hier tut er es ausdrücklich.' },
      { art:'hoerwahl', ort:'Vortrag über Gesundheit', wer:'Frau',
        text:'Die Zahl ist seit 2019 stabil. Stabil heißt in diesem Fall allerdings: stabil hoch. Eine Verbesserung ist das nicht.',
        frage:'Wie bewertet die Sprecherin die stabile Zahl?',
        opt:['Als Erfolg.','Als unverändert schlechten Zustand.','Als Verschlechterung.'], loesung:1,
        stelle:'stabil hoch',
        erklaerung:'Sie definiert ein scheinbar neutrales Wort um. Diese Umdeutung ist die Aufgabe.' },
      { art:'hoerwahl', ort:'Vortrag über Arbeitsmarkt', wer:'Mann',
        text:'Ich fasse zusammen: Der Mangel ist regional sehr unterschiedlich, er trifft kleine Betriebe härter als große, und er wird sich in den nächsten zehn Jahren eher verschärfen.',
        frage:'Welche Aussage gehört NICHT zur Zusammenfassung?',
        opt:['Der Mangel ist regional verschieden.','Große Betriebe sind stärker betroffen.','Der Mangel nimmt voraussichtlich zu.'], loesung:1,
        stelle:'kleine Betriebe härter als große',
        erklaerung:'Die Umkehrung ist der klassische Fallenstrick. Höre bei Vergleichen immer die Richtung mit.' },
      { art:'hoerwahl', ort:'Vortrag über Sprachen', wer:'Frau',
        text:'Dass Mehrsprachigkeit dem Denken nützt, gilt heute als gesichert. Wie groß dieser Nutzen ist, darüber streitet die Forschung weiter.',
        frage:'Was ist in der Forschung umstritten?',
        opt:['Ob Mehrsprachigkeit nützt.','Wie stark der Nutzen ist.','Ob man Sprachen lernen soll.'], loesung:1,
        stelle:'Wie groß dieser Nutzen ist',
        erklaerung:'Das Ob ist geklärt, das Wie viel nicht. Auf C1 wird genau diese Grenze geprüft.' },
      { art:'hoerwahl', ort:'Vortrag über Städtebau', wer:'Mann',
        text:'Nehmen wir das Beispiel Kopenhagen — nicht, weil man es nachbauen könnte, sondern weil es zeigt, wie lange so etwas dauert: dreißig Jahre.',
        frage:'Warum nennt der Sprecher Kopenhagen?',
        opt:['Als Vorbild zum Nachbauen.','Als Beispiel für den langen Zeitraum.','Als abschreckendes Beispiel.'], loesung:1,
        stelle:'wie lange so etwas dauert',
        erklaerung:'„nicht weil …, sondern weil …" liefert die Begründung gleich mit.' }
    ]}
  ],

  teile: [

    { nr:1, art:'podcast', name:'Podcast — drei Bücher', kurz:'Aussagen zuordnen — nur einmal hören',
      was:'Du hörst Ausschnitte aus einer Podcast-Folge über drei neue Bücher. Jede Aussage gehört zu genau einem davon.',
      tipp:'Lies die drei Titel, bevor der Ton läuft, und merke dir zu jedem ein einziges Stichwort. In der Prüfung läuft dieser Teil nur einmal — hier auch.',
      zeichen:'🎧', farbe:'turq', punkte:20, mal:1, runden:[

      { id:'c1h1r1', titel:'Drei Romane des Herbstes', aufgaben:[
        { ort:'Literaturpodcast — Folge über drei Romane', wer:'Frau',
          text:'Fangen wir mit Anselm Roths Familiengeschichte an. Sie ist über sechshundert Seiten lang, und man merkt jede einzelne. Trotzdem bleibt man dran, weil die Figuren so genau beobachtet sind.',
          frage:'Was gilt für Roths Roman?',
          opt:['Er ist lang und trotzdem fesselnd.','Er ist kurz und dicht.','Er hat schwache Figuren.'], loesung:0,
          stelle:'Trotzdem bleibt man dran',
          erklaerung:'Zwei gegenläufige Urteile, verbunden durch „trotzdem" — das zweite gewinnt.' },
        { ort:'Literaturpodcast — Folge über drei Romane', wer:'Mann',
          text:'Bei Leila Faruqis Debüt ist es umgekehrt: knapp zweihundert Seiten, kein Wort zu viel. Was ich vermisst habe, ist ein Erzähler, der auch mal etwas riskiert.',
          frage:'Was kritisiert der Sprecher an Faruqis Debüt?',
          opt:['Die Länge.','Die fehlende Risikobereitschaft.','Die unklare Sprache.'], loesung:1,
          stelle:'der auch mal etwas riskiert',
          erklaerung:'Die Knappheit lobt er. Die Kritik steht hinter „Was ich vermisst habe".' },
        { ort:'Literaturpodcast — Folge über drei Romane', wer:'Frau',
          text:'Und dann der dritte: Mirko Petrescus Roman spielt in einem einzigen Treppenhaus. Das klingt nach Enge, ist aber das Gegenteil — über die Nachbarn kommt die halbe Stadt herein.',
          frage:'Was sagt die Sprecherin über Petrescus Roman?',
          opt:['Er wirkt eng und beschränkt.','Der enge Schauplatz öffnet den Blick.','Er spielt in der ganzen Stadt.'], loesung:1,
          stelle:'ist aber das Gegenteil',
          erklaerung:'„Das klingt nach …, ist aber …" kündigt die Umkehrung an.' },
        { ort:'Literaturpodcast — Folge über drei Romane', wer:'Mann',
          text:'Wenn Sie wenig Zeit haben und trotzdem etwas lesen wollen, das Ihnen eine Woche im Kopf bleibt, greifen Sie zu dem Debüt. Für den Urlaub nehmen Sie die Familiengeschichte.',
          frage:'Welches Buch empfiehlt er Leuten mit wenig Zeit?',
          opt:['Roths Familiengeschichte.','Faruqis Debüt.','Petrescus Roman.'], loesung:1,
          stelle:'greifen Sie zu dem Debüt',
          erklaerung:'Du musst „Debüt" mit Faruqi verbinden — der Name fällt hier nicht mehr.' },
        { ort:'Literaturpodcast — Folge über drei Romane', wer:'Frau',
          text:'Eines muss man sagen: Bei zweien der drei Bücher weiß man nach dreißig Seiten, woran man ist. Bei dem Treppenhaus-Roman dauert es deutlich länger, bis man den Ton hat.',
          frage:'Welches Buch braucht am längsten, bis man hineinfindet?',
          opt:['Roths Roman.','Faruqis Debüt.','Petrescus Roman.'], loesung:2,
          stelle:'dauert es deutlich länger',
          erklaerung:'„Treppenhaus-Roman" ist die Umschreibung für Petrescu, die vorher eingeführt wurde.' },
        { ort:'Literaturpodcast — Folge über drei Romane', wer:'Mann',
          text:'Und über welches werden wir in einem Jahr noch reden? Ich tippe auf keines der drei, ehrlich gesagt. Gute Bücher, aber keines davon wird bleiben.',
          frage:'Was erwartet der Sprecher?',
          opt:['Alle drei werden wichtig bleiben.','Keines der drei wird langfristig bleiben.','Nur das Debüt bleibt.'], loesung:1,
          stelle:'keines davon wird bleiben',
          erklaerung:'„Gute Bücher, aber" — das Lob ändert die Prognose nicht.' }
      ]},

      { id:'c1h1r2', titel:'Drei Sachbücher zur Arbeitswelt', aufgaben:[
        { ort:'Sachbuchpodcast', wer:'Frau',
          text:'Das erste Buch argumentiert streng empirisch. Jede These hat ihre Tabelle, und wo die Daten fehlen, sagt die Autorin das auch. Angenehm unaufgeregt.',
          frage:'Was lobt die Sprecherin am ersten Buch?',
          opt:['Den zugespitzten Ton.','Die Offenheit über Datenlücken.','Den Verzicht auf Zahlen.'], loesung:1,
          stelle:'wo die Daten fehlen, sagt die Autorin das auch',
          erklaerung:'„unaufgeregt" bestätigt es: gelobt wird die Zurückhaltung, nicht die Zuspitzung.' },
        { ort:'Sachbuchpodcast', wer:'Mann',
          text:'Das zweite ist das genaue Gegenteil: eine These, zweihundert Seiten, und auf jeder Seite wird sie lauter. Man liest es in einem Zug und glaubt danach kein Wort.',
          frage:'Wie wirkt das zweite Buch auf den Sprecher?',
          opt:['Überzeugend und gründlich.','Mitreißend, aber unglaubwürdig.','Langweilig und trocken.'], loesung:1,
          stelle:'glaubt danach kein Wort',
          erklaerung:'„in einem Zug" ist Lob für den Sog, „kein Wort" das Urteil über den Inhalt.' },
        { ort:'Sachbuchpodcast', wer:'Frau',
          text:'Beim dritten weiß ich bis heute nicht, für wen es geschrieben ist. Für Fachleute zu schlicht, für alle anderen zu voraussetzungsreich.',
          frage:'Was ist das Problem des dritten Buches?',
          opt:['Es hat kein klares Publikum.','Es ist zu kurz.','Es ist zu fachlich korrekt.'], loesung:0,
          stelle:'für wen es geschrieben ist',
          erklaerung:'Die beiden Teilurteile ergeben zusammen: niemand ist die Zielgruppe.' },
        { ort:'Sachbuchpodcast', wer:'Mann',
          text:'Wer im Betriebsrat sitzt und morgen argumentieren muss, nimmt das empirische. Da stehen die Zahlen drin, die man zitieren kann.',
          frage:'Welches Buch nützt in der Praxis am meisten?',
          opt:['Das erste.','Das zweite.','Das dritte.'], loesung:0,
          stelle:'nimmt das empirische',
          erklaerung:'„empirisch" verweist zurück auf das erste Buch mit den Tabellen.' },
        { ort:'Sachbuchpodcast', wer:'Frau',
          text:'Interessant ist, dass zwei der drei Bücher zum selben Schluss kommen — nur dass das eine ihn belegt und das andere ihn behauptet.',
          frage:'Was unterscheidet die beiden Bücher mit gleichem Ergebnis?',
          opt:['Die Länge.','Der Beleg.','Das Thema.'], loesung:1,
          stelle:'das eine ihn belegt und das andere ihn behauptet',
          erklaerung:'Belegen gegen behaupten — das ist der ganze Unterschied, in einem Satz.' },
        { ort:'Sachbuchpodcast', wer:'Mann',
          text:'Und wenn Sie nur Zeit für ein einziges haben? Dann keines davon. Dann lesen Sie noch einmal den Klassiker von vor zwanzig Jahren, der steht immer noch besser da.',
          frage:'Was empfiehlt der Sprecher am Ende?',
          opt:['Das empirische Buch.','Ein älteres Standardwerk.','Alle drei nacheinander.'], loesung:1,
          stelle:'den Klassiker von vor zwanzig Jahren',
          erklaerung:'Die Empfehlung liegt außerhalb der drei besprochenen Titel — darauf muss man gefasst sein.' }
      ]}
    ]},

    { nr:2, art:'interview', name:'Radiointerview', kurz:'stimmt · stimmt nicht · dazu wird nichts gesagt — zweimal hören',
      was:'Du hörst ein Interview mit einer Fachperson. Entscheide zu jeder Aussage, ob sie zutrifft, ob sie widerlegt wird oder ob darüber gar nichts gesagt wird.',
      tipp:'Der dritte Fall kostet die meisten Punkte. Frage dich immer: Steht das wirklich im Text — oder weiß ich es nur selbst?',
      zeichen:'🎙️', farbe:'gold', punkte:30, mal:2, runden:[

      { id:'c1h2r1', titel:'Interview: Schlafforschung', aufgaben:[
        { ort:'Radiointerview mit einer Schlafforscherin', wer:'Frau',
          text:'Wir sehen in unseren Daten, dass die durchschnittliche Schlafdauer seit den Neunzigern um etwa zwanzig Minuten gesunken ist. Woran das liegt, darüber kann ich nur spekulieren.',
          frage:'Aussage: Die Ursachen des Rückgangs sind geklärt.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'kann ich nur spekulieren',
          erklaerung:'Spekulieren heißt: nicht geklärt. Die Behauptung wird damit verneint, nicht offengelassen.' },
        { ort:'Radiointerview mit einer Schlafforscherin', wer:'Frau',
          text:'Für Jugendliche gilt etwas anderes als für Erwachsene — ihre innere Uhr verschiebt sich biologisch nach hinten. Das ist keine Faulheit, das ist Entwicklung.',
          frage:'Aussage: Jugendliche gehen aus Bequemlichkeit spät ins Bett.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'Das ist keine Faulheit',
          erklaerung:'Der Einwand wird wörtlich zurückgewiesen.' },
        { ort:'Radiointerview mit einer Schlafforscherin', wer:'Frau',
          text:'Ob ein späterer Schulbeginn die Noten verbessert, wird im Ausland untersucht. Bei uns gibt es dazu bisher keine belastbare Studie.',
          frage:'Aussage: Späterer Schulbeginn verbessert die Noten.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
          stelle:'keine belastbare Studie',
          erklaerung:'Sie sagt, dass es untersucht wird — nicht, was herauskommt.' },
        { ort:'Radiointerview mit einer Schlafforscherin', wer:'Frau',
          text:'Ein Mittagsschlaf von zwanzig Minuten ist unproblematisch und für viele hilfreich. Länger als eine halbe Stunde würde ich nicht empfehlen, dann wird man eher träge.',
          frage:'Aussage: Ein kurzer Mittagsschlaf ist empfehlenswert.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:0,
          stelle:'unproblematisch und für viele hilfreich',
          erklaerung:'Die Einschränkung betrifft nur die Dauer darüber.' },
        { ort:'Radiointerview mit einer Schlafforscherin', wer:'Frau',
          text:'Schlafmittel sind bei uns in der Forschung kein Thema, da bin ich die Falsche. Ich arbeite mit gesunden Probanden.',
          frage:'Aussage: Schlafmittel wirken langfristig nicht.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
          stelle:'da bin ich die Falsche',
          erklaerung:'Zuständigkeit verneint, Sache offen — das ist der dritte Fall in Reinform.' },
        { ort:'Radiointerview mit einer Schlafforscherin', wer:'Frau',
          text:'Was wir ziemlich sicher sagen können: Regelmäßigkeit schlägt Dauer. Sieben Stunden jeden Tag zur selben Zeit sind besser als mal fünf und mal neun.',
          frage:'Aussage: Gleichmäßige Zeiten sind wichtiger als die Stundenzahl.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:0,
          stelle:'Regelmäßigkeit schlägt Dauer',
          erklaerung:'„schlägt" ist hier der Vergleich: das eine wiegt schwerer als das andere.' }
      ]},

      { id:'c1h2r2', titel:'Interview: Stadtbäume', aufgaben:[
        { ort:'Radiointerview mit einem Stadtökologen', wer:'Mann',
          text:'Ein großer Baum kühlt an einem heißen Tag so stark wie mehrere Klimageräte. Dass er dabei kein Geld kostet, stimmt allerdings nicht — Pflege und Wasser sind teuer.',
          frage:'Aussage: Stadtbäume verursachen kaum Kosten.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'stimmt allerdings nicht',
          erklaerung:'Er greift eine verbreitete Annahme auf und widerspricht ihr ausdrücklich.' },
        { ort:'Radiointerview mit einem Stadtökologen', wer:'Mann',
          text:'Die meisten Bäume sterben nicht an der Hitze, sondern an dem, was unter dem Pflaster passiert: zu wenig Platz für die Wurzeln.',
          frage:'Aussage: Hitze ist die häufigste Todesursache für Stadtbäume.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'sterben nicht an der Hitze, sondern',
          erklaerung:'„nicht …, sondern" ist die deutlichste Form der Korrektur.' },
        { ort:'Radiointerview mit einem Stadtökologen', wer:'Mann',
          text:'Welche Arten in dreißig Jahren noch funktionieren, weiß im Moment niemand genau. Wir pflanzen deshalb bewusst gemischt.',
          frage:'Aussage: Die künftig geeigneten Arten sind bekannt.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'weiß im Moment niemand genau',
          erklaerung:'Ausdrückliches Nichtwissen widerlegt die Behauptung.' },
        { ort:'Radiointerview mit einem Stadtökologen', wer:'Mann',
          text:'In unserer Stadt sind in den letzten fünf Jahren rund viertausend Bäume gepflanzt worden. Wie viele davon angewachsen sind, erheben wir erst seit letztem Jahr.',
          frage:'Aussage: Die meisten neu gepflanzten Bäume sind angewachsen.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
          stelle:'erheben wir erst seit letztem Jahr',
          erklaerung:'Eine Zahl für die Pflanzungen ersetzt keine Zahl für das Anwachsen.' },
        { ort:'Radiointerview mit einem Stadtökologen', wer:'Mann',
          text:'Bürgerinnen und Bürger können viel tun — gießen vor allem, in den ersten drei Jahren. Danach braucht ein Baum uns kaum noch.',
          frage:'Aussage: Junge Bäume brauchen in den ersten Jahren Hilfe.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:0,
          stelle:'in den ersten drei Jahren',
          erklaerung:'Direkt bestätigt, mit Zeitangabe.' },
        { ort:'Radiointerview mit einem Stadtökologen', wer:'Mann',
          text:'Ob Bäume in der Straße den Verkehrslärm messbar senken, ist in der Fachwelt umstritten. Gefühlt tun sie es, physikalisch kaum.',
          frage:'Aussage: Bäume senken den Lärm deutlich messbar.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'physikalisch kaum',
          erklaerung:'Gefühl und Messung werden getrennt — gefragt ist die Messung.' }
      ]}
    ]},

    { nr:3, art:'gespraech', name:'Gespräch mehrerer Personen', kurz:'Positionen zuordnen — je Abschnitt einmal',
      was:'Mehrere Personen diskutieren. Du musst hören, wer welche Position vertritt — und wer sie im Lauf des Gesprächs verlässt.',
      tipp:'Merke dir zu jeder Person ein Stichwort, nicht den ganzen Satz. Und achte auf Zustimmung, die eigentlich Widerspruch ist: „Da bin ich ganz bei Ihnen, nur …"',
      zeichen:'🗣️', farbe:'rose', punkte:26, mal:1, runden:[

      { id:'c1h3r1', titel:'Wohnen der Zukunft', aufgaben:[
        { ort:'Gesprächsrunde — Frau Dahl, Herr Noll, Frau Prinz',
          zeilen:[
            {wer:'Frau', text:'Wir bauen weiter Wohnungen für eine Familienform, die es so kaum noch gibt. Vier Zimmer, Flur, Abstellraum — das passt für immer weniger Leute.'},
            {wer:'Mann', text:'Da bin ich ganz bei Ihnen. Nur wird jede kleinere Wohnung pro Quadratmeter teurer, und das zahlt am Ende die Mieterin.'}
          ],
          frage:'Was wendet Herr Noll ein?',
          opt:['Dass kleinere Wohnungen nicht gebraucht werden.','Dass sie pro Quadratmeter teurer sind.','Dass Familien Vorrang haben sollten.'], loesung:1,
          stelle:'pro Quadratmeter teurer',
          erklaerung:'Die Zustimmung ist echt, der Einwand betrifft nur den Preis.' },
        { ort:'Gesprächsrunde — Frau Dahl, Herr Noll, Frau Prinz',
          zeilen:[
            {wer:'Frau', text:'Mich überzeugt das Argument mit dem Quadratmeterpreis nicht. Wenn ich dreißig Quadratmeter weniger brauche, zahle ich unterm Strich trotzdem weniger.'},
            {wer:'Mann', text:'Rechnerisch ja. In der Realität werden die kleinen Wohnungen aber zuerst von Leuten genommen, die es sich leisten können.'}
          ],
          frage:'Worin besteht der Unterschied zwischen beiden Positionen?',
          opt:['Rechnung gegen tatsächliche Verteilung.','Groß gegen klein.','Stadt gegen Land.'], loesung:0,
          stelle:'In der Realität',
          erklaerung:'„Rechnerisch ja" räumt die Mathematik ein und setzt die Praxis dagegen.' },
        { ort:'Gesprächsrunde — Frau Dahl, Herr Noll, Frau Prinz',
          zeilen:[
            {wer:'Frau', text:'Ich habe lange für Gemeinschaftsflächen geworben — Waschküche, Werkstatt, Gästezimmer. Ehrlich gesagt sehe ich inzwischen, dass sie kaum genutzt werden.'},
            {wer:'Mann', text:'Das würde ich so nicht stehen lassen. Dort, wo jemand sich kümmert, werden sie sehr wohl genutzt.'}
          ],
          frage:'Was ist bei Frau Prinz passiert?',
          opt:['Sie hat ihre frühere Position relativiert.','Sie hat ihre Position verstärkt.','Sie hat das Thema gewechselt.'], loesung:0,
          stelle:'sehe ich inzwischen',
          erklaerung:'„Ich habe lange geworben … inzwischen sehe ich" ist eine offene Revision.' },
        { ort:'Gesprächsrunde — Frau Dahl, Herr Noll, Frau Prinz',
          zeilen:[
            {wer:'Mann', text:'Die entscheidende Frage ist doch, wer das organisiert. Ohne eine bezahlte Person läuft so etwas nach zwei Jahren aus.'},
            {wer:'Frau', text:'Genau das ist der Punkt, und genau daran sparen alle zuerst.'}
          ],
          frage:'Worin sind sich beide einig?',
          opt:['Dass Gemeinschaftsflächen überflüssig sind.','Dass es bezahlte Organisation braucht.','Dass zwei Jahre genug sind.'], loesung:1,
          stelle:'Ohne eine bezahlte Person',
          erklaerung:'„Genau das ist der Punkt" ist volle Zustimmung zur Bedingung.' },
        { ort:'Gesprächsrunde — Frau Dahl, Herr Noll, Frau Prinz',
          zeilen:[
            {wer:'Frau', text:'Beim Thema Autostellplätze bin ich strikt: keine mehr im Neubau, Punkt.'},
            {wer:'Frau', text:'So weit würde ich nicht gehen. Im Quartier, ja. Aber auf dem Land nehmen Sie den Leuten damit die Arbeit.'}
          ],
          frage:'Wie unterscheiden sich die beiden Sprecherinnen?',
          opt:['Die zweite will die Regel nur in der Stadt.','Beide wollen dasselbe.','Die zweite will mehr Stellplätze als bisher.'], loesung:0,
          stelle:'Im Quartier, ja. Aber auf dem Land',
          erklaerung:'Der Unterschied ist räumlich, nicht grundsätzlich.' },
        { ort:'Gesprächsrunde — Frau Dahl, Herr Noll, Frau Prinz',
          zeilen:[
            {wer:'Mann', text:'Wenn ich eines mitnehme aus dieser Runde, dann dass wir weniger über Quadratmeter und mehr über Betrieb reden müssen.'},
            {wer:'Frau', text:'Dem schließe ich mich an.'}
          ],
          frage:'Was ist das Fazit des Gesprächs?',
          opt:['Mehr Fläche pro Person.','Der laufende Betrieb ist wichtiger als die Fläche.','Weniger Neubau insgesamt.'], loesung:1,
          stelle:'mehr über Betrieb reden',
          erklaerung:'Das Fazit steht in der Schlusswendung „Wenn ich eines mitnehme".' }
      ]},

      { id:'c1h3r2', titel:'Künstliche Intelligenz im Büro', aufgaben:[
        { ort:'Diskussion — Herr Albrecht, Frau Yildiz, Herr Senn',
          zeilen:[
            {wer:'Mann', text:'Bei uns schreibt die Software inzwischen die ersten Entwürfe. Die Zeitersparnis ist erheblich, ungefähr ein Drittel.'},
            {wer:'Frau', text:'Ein Drittel wovon denn? Wenn das Korrekturlesen länger dauert als früher das Schreiben, haben Sie nichts gewonnen.'}
          ],
          frage:'Was bezweifelt Frau Yildiz?',
          opt:['Dass die Software Entwürfe schreibt.','Dass die Ersparnis unterm Strich bleibt.','Dass man Entwürfe braucht.'], loesung:1,
          stelle:'haben Sie nichts gewonnen',
          erklaerung:'Sie stellt die Nettorechnung infrage, nicht die Technik.' },
        { ort:'Diskussion — Herr Albrecht, Frau Yildiz, Herr Senn',
          zeilen:[
            {wer:'Mann', text:'Wir haben das gemessen. Beim zweiten Mal war das Korrekturlesen deutlich schneller, weil die Leute wussten, worauf sie achten müssen.'},
            {wer:'Frau', text:'Das überzeugt mich, zugegeben. Dann liegt der Gewinn aber in der Übung, nicht im Werkzeug.'}
          ],
          frage:'Wie reagiert Frau Yildiz?',
          opt:['Sie bleibt bei ihrem Einwand.','Sie nimmt ihn zurück und deutet den Befund um.','Sie wechselt das Thema.'], loesung:1,
          stelle:'Das überzeugt mich, zugegeben',
          erklaerung:'Zustimmung plus Umdeutung — eine typische C1-Bewegung.' },
        { ort:'Diskussion — Herr Albrecht, Frau Yildiz, Herr Senn',
          zeilen:[
            {wer:'Mann', text:'Mich beschäftigt etwas anderes: Wer haftet, wenn in so einem Entwurf ein Fehler steht und ihn niemand merkt?'},
            {wer:'Mann', text:'Rechtlich derjenige, der unterschreibt. Daran ändert die Software gar nichts.'}
          ],
          frage:'Welche Frage bringt Herr Senn ein?',
          opt:['Die Kostenfrage.','Die Haftungsfrage.','Die Datenschutzfrage.'], loesung:1,
          stelle:'Wer haftet',
          erklaerung:'Er verschiebt das Thema ausdrücklich: „Mich beschäftigt etwas anderes".' },
        { ort:'Diskussion — Herr Albrecht, Frau Yildiz, Herr Senn',
          zeilen:[
            {wer:'Frau', text:'In meiner Abteilung wollte die Hälfte das Werkzeug gar nicht. Nach drei Monaten wollte es niemand mehr hergeben.'},
            {wer:'Mann', text:'Das deckt sich mit unseren Erfahrungen, mit einer Ausnahme: Bei den Älteren hat es deutlich länger gedauert.'}
          ],
          frage:'Welche Einschränkung macht Herr Albrecht?',
          opt:['Bei älteren Beschäftigten dauerte es länger.','Niemand wollte das Werkzeug behalten.','Die Hälfte lehnt es bis heute ab.'], loesung:0,
          stelle:'Bei den Älteren hat es deutlich länger gedauert',
          erklaerung:'„mit einer Ausnahme" kündigt genau diese Einschränkung an.' },
        { ort:'Diskussion — Herr Albrecht, Frau Yildiz, Herr Senn',
          zeilen:[
            {wer:'Mann', text:'Ich warne davor, das als reine Effizienzfrage zu behandeln. Wenn der Entwurf immer schon da ist, denkt irgendwann niemand mehr von vorn.'},
            {wer:'Frau', text:'Das halte ich für übertrieben, aber ganz von der Hand weisen kann ich es nicht.'}
          ],
          frage:'Wie bewertet Frau Yildiz die Warnung?',
          opt:['Sie teilt sie vollständig.','Sie hält sie für überzogen, nicht für falsch.','Sie weist sie zurück.'], loesung:1,
          stelle:'ganz von der Hand weisen kann ich es nicht',
          erklaerung:'Doppelte Verneinung: nicht ganz zurückweisen heißt teilweise zustimmen.' },
        { ort:'Diskussion — Herr Albrecht, Frau Yildiz, Herr Senn',
          zeilen:[
            {wer:'Mann', text:'Was würden Sie einem Betrieb raten, der morgen anfängt?'},
            {wer:'Mann', text:'Klein anfangen, eine Abteilung, drei Monate, und vorher festlegen, woran man Erfolg misst. Sonst diskutieren Sie hinterher über Gefühle.'}
          ],
          frage:'Was rät Herr Senn?',
          opt:['Sofort im ganzen Betrieb einführen.','Begrenzt starten und Erfolgskriterien vorher festlegen.','Noch ein Jahr abwarten.'], loesung:1,
          stelle:'vorher festlegen, woran man Erfolg misst',
          erklaerung:'Zwei Teile: begrenzter Start und vorherige Messgröße.' }
      ]}
    ]},

    { nr:4, art:'vortrag', name:'Vortrag', kurz:'Auswahl aus drei — zweimal hören',
      was:'Du hörst Ausschnitte aus einem Fachvortrag. Gefragt sind Gliederung, Zahlen und die Einschränkungen, die der Vortragende selbst macht.',
      tipp:'Hör auf die Gliederungssignale: „Ich komme zum zweiten Punkt", „Lassen Sie mich zusammenfassen". Unmittelbar danach steht fast immer die Antwort.',
      zeichen:'📊', farbe:'indigo', punkte:24, mal:2, runden:[

      { id:'c1h4r1', titel:'Vortrag: Wasser in der Stadt', aufgaben:[
        { ort:'Fachvortrag', wer:'Frau',
          text:'Ich gliedere meinen Vortrag in drei Teile: zuerst das Problem, dann die üblichen Lösungen, und zuletzt das, was aus meiner Sicht übersehen wird.',
          frage:'Was kommt im dritten Teil?',
          opt:['Das Problem.','Die üblichen Lösungen.','Der übersehene Aspekt.'], loesung:2,
          stelle:'zuletzt das, was aus meiner Sicht übersehen wird',
          erklaerung:'Reihenfolgen am Anfang eines Vortrags sind Prüfungsstoff.' },
        { ort:'Fachvortrag', wer:'Frau',
          text:'In Starkregenlagen fallen bei uns inzwischen bis zu sechzig Liter pro Quadratmeter in einer Stunde. Das Kanalnetz ist auf etwa die Hälfte ausgelegt — und zwar nicht aus Nachlässigkeit, sondern weil es damals ausreichte.',
          frage:'Warum reicht das Kanalnetz nicht mehr?',
          opt:['Es wurde schlecht geplant.','Die Regenmengen haben sich verändert.','Es ist zu alt gebaut.'], loesung:1,
          stelle:'weil es damals ausreichte',
          erklaerung:'Sie weist die Schuldzuschreibung ausdrücklich zurück.' },
        { ort:'Fachvortrag', wer:'Frau',
          text:'Die übliche Antwort lautet: größere Rohre. Das hilft, kostet aber ein Vielfaches und löst das Problem nur dort, wo man gräbt.',
          frage:'Wie bewertet sie größere Rohre?',
          opt:['Wirkungslos.','Wirksam, aber teuer und örtlich begrenzt.','Die beste Lösung.'], loesung:1,
          stelle:'nur dort, wo man gräbt',
          erklaerung:'„Das hilft, kostet aber" — Wirkung bejaht, Einschränkung folgt.' },
        { ort:'Fachvortrag', wer:'Frau',
          text:'Ich komme zum übersehenen Punkt. Er heißt Fläche. Jeder Quadratmeter, der Wasser aufnimmt statt es abzuleiten, entlastet den Kanal — und davon gibt es in jeder Stadt mehr, als man denkt.',
          frage:'Was ist der übersehene Punkt?',
          opt:['Größere Rohre.','Entsiegelte Flächen.','Mehr Personal.'], loesung:1,
          stelle:'Wasser aufnimmt statt es abzuleiten',
          erklaerung:'Das Gliederungssignal „Ich komme zum übersehenen Punkt" markiert die Stelle.' },
        { ort:'Fachvortrag', wer:'Frau',
          text:'Eine Zahl dazu: Würde man in einer mittelgroßen Stadt nur die Parkplätze entsiegeln, nähme das Netz bis zu fünfzehn Prozent weniger Wasser auf — theoretisch. Praktisch gehören die Flächen vielen verschiedenen Leuten.',
          frage:'Was schränkt die Zahl ein?',
          opt:['Die Technik.','Die Eigentumsverhältnisse.','Die Kosten.'], loesung:1,
          stelle:'gehören die Flächen vielen verschiedenen Leuten',
          erklaerung:'„theoretisch … praktisch" ist das Signal für die Relativierung.' },
        { ort:'Fachvortrag', wer:'Frau',
          text:'Lassen Sie mich zusammenfassen: Das Problem ist nicht neu, die teure Lösung ist bekannt, und die billige scheitert nicht an der Technik, sondern an der Abstimmung.',
          frage:'Woran scheitert die günstige Lösung?',
          opt:['An der Technik.','An der Abstimmung zwischen Beteiligten.','Am Geld.'], loesung:1,
          stelle:'sondern an der Abstimmung',
          erklaerung:'„nicht …, sondern" trennt die falsche von der richtigen Antwort.' }
      ]},

      { id:'c1h4r2', titel:'Vortrag: Lesen und Bildschirm', aufgaben:[
        { ort:'Fachvortrag', wer:'Mann',
          text:'Ich beginne mit einer Warnung in eigener Sache: Die Studienlage zu diesem Thema ist schlechter, als die Schlagzeilen vermuten lassen.',
          frage:'Womit beginnt der Vortragende?',
          opt:['Mit einem klaren Ergebnis.','Mit einem Hinweis auf die schwache Datenlage.','Mit einer Zahl.'], loesung:1,
          stelle:'schlechter, als die Schlagzeilen vermuten lassen',
          erklaerung:'„Warnung in eigener Sache" kündigt Selbstrelativierung an.' },
        { ort:'Fachvortrag', wer:'Mann',
          text:'Beim Lesen längerer Sachtexte schneiden Papierleser in vielen Untersuchungen besser ab. Der Abstand ist klein, aber er taucht immer wieder auf.',
          frage:'Was sagt er über den Vorsprung des Papiers?',
          opt:['Er ist groß und eindeutig.','Er ist klein, aber wiederholt nachweisbar.','Er existiert nicht.'], loesung:1,
          stelle:'klein, aber er taucht immer wieder auf',
          erklaerung:'Beide Hälften gehören zur Antwort; eine allein wäre falsch.' },
        { ort:'Fachvortrag', wer:'Mann',
          text:'Bei kurzen Texten verschwindet der Unterschied vollständig. Und bei Texten, die man durchsuchen muss, ist der Bildschirm klar überlegen.',
          frage:'Wann ist der Bildschirm im Vorteil?',
          opt:['Bei langen Sachtexten.','Bei kurzen Texten.','Wenn man im Text suchen muss.'], loesung:2,
          stelle:'die man durchsuchen muss',
          erklaerung:'Drei Fälle werden unterschieden — gefragt ist der dritte.' },
        { ort:'Fachvortrag', wer:'Mann',
          text:'Die häufigste Erklärung lautet: Das Papier gibt dem Text einen Ort, man erinnert sich an die Stelle auf der Seite. Belegt ist das eher schwach.',
          frage:'Wie bewertet er diese Erklärung?',
          opt:['Als gut belegt.','Als verbreitet, aber schwach belegt.','Als widerlegt.'], loesung:1,
          stelle:'Belegt ist das eher schwach',
          erklaerung:'Häufig ist nicht dasselbe wie belegt. Der Unterschied ist die Aufgabe.' },
        { ort:'Fachvortrag', wer:'Mann',
          text:'Für die Schule heißt das aus meiner Sicht nicht: zurück zum Papier. Es heißt: beides üben, und zwar getrennt, denn es sind zwei verschiedene Fertigkeiten.',
          frage:'Was empfiehlt er für die Schule?',
          opt:['Nur noch Papier.','Beides getrennt üben.','Nur noch Bildschirm.'], loesung:1,
          stelle:'beides üben, und zwar getrennt',
          erklaerung:'Er weist die naheliegende Schlussfolgerung ausdrücklich zurück, bevor er seine nennt.' },
        { ort:'Fachvortrag', wer:'Mann',
          text:'Zum Schluss die ehrlichste Antwort, die ich geben kann: Wie das in zehn Jahren aussieht, wenn eine ganze Generation anders aufgewachsen ist, weiß heute niemand.',
          frage:'Wie endet der Vortrag?',
          opt:['Mit einer klaren Prognose.','Mit dem Eingeständnis, dass die Zukunft offen ist.','Mit einer Handlungsanweisung.'], loesung:1,
          stelle:'weiß heute niemand',
          erklaerung:'„die ehrlichste Antwort" leitet das Eingeständnis ein, keine Prognose.' }
      ]}
    ]}
  ],

  laeufe: [
    { id:'c1hlauf1', titel:'Prüfungslauf 1', minuten:40, teile:[

      { nr:1, art:'podcast', mal:1, aufgaben:[
        { von:'Podcast über drei Ausstellungen', wer:'Frau',
          text:'Die Schau im Alten Zollhaus zeigt Fotografien aus den Siebzigern. Was sie trägt, ist nicht das Material, sondern die Hängung — man geht chronologisch und merkt es nicht.',
          frage:'Was ist an der Zollhaus-Schau besonders?',
          opt:['Das Material.','Die Anordnung.','Die Größe.'], loesung:1,
          stelle:'sondern die Hängung',
          erklaerung:'„nicht …, sondern" nennt die Antwort direkt.' },
        { von:'Podcast über drei Ausstellungen', wer:'Mann',
          text:'Im Kunstverein hängen zwölf Bilder, mehr nicht. Für zwei davon lohnt die Fahrt, die übrigen zehn hätte man weglassen können.',
          frage:'Wie urteilt der Sprecher über den Kunstverein?',
          opt:['Durchweg stark.','Zwei starke Werke, der Rest schwach.','Insgesamt zu groß.'], loesung:1,
          stelle:'die übrigen zehn hätte man weglassen können',
          erklaerung:'Zahl gegen Zahl: zwei gegen zehn.' },
        { von:'Podcast über drei Ausstellungen', wer:'Frau',
          text:'Die dritte, im Museum am Park, ist die einzige, in die ich Kinder mitnehmen würde. Dort darf man anfassen, und das ändert alles.',
          frage:'Welche Ausstellung eignet sich für Familien?',
          opt:['Das Alte Zollhaus.','Der Kunstverein.','Das Museum am Park.'], loesung:2,
          stelle:'Kinder mitnehmen würde',
          erklaerung:'„die einzige" schließt die beiden anderen ausdrücklich aus.' },
        { von:'Podcast über drei Ausstellungen', wer:'Mann',
          text:'Wenn Sie nur eine schaffen und sich für Fotografie interessieren, ist die Sache klar. Wenn nicht, würde ich die zwölf Bilder nehmen — wegen der zwei.',
          frage:'Was empfiehlt er Besuchern ohne Interesse an Fotografie?',
          opt:['Das Alte Zollhaus.','Den Kunstverein.','Das Museum am Park.'], loesung:1,
          stelle:'die zwölf Bilder nehmen',
          erklaerung:'„die zwölf Bilder" verweist zurück auf den Kunstverein.' },
        { von:'Podcast über drei Ausstellungen', wer:'Frau',
          text:'Preislich sind zwei davon kostenlos. Ausgerechnet die teuerste ist die, bei der ich am wenigsten mitgenommen habe.',
          frage:'Was sagt sie über die teuerste Ausstellung?',
          opt:['Sie war ihr Geld wert.','Sie hat ihr am wenigsten gegeben.','Sie war ausverkauft.'], loesung:1,
          stelle:'am wenigsten mitgenommen',
          erklaerung:'„Ausgerechnet" markiert den Widerspruch zwischen Preis und Ertrag.' },
        { von:'Podcast über drei Ausstellungen', wer:'Mann',
          text:'Alle drei laufen noch bis Ende Januar. Nur die im Zollhaus wird danach weiterwandern, die anderen beiden sind dann weg.',
          frage:'Welche Ausstellung ist später noch anderswo zu sehen?',
          opt:['Die im Zollhaus.','Die im Kunstverein.','Die im Museum am Park.'], loesung:0,
          stelle:'wird danach weiterwandern',
          erklaerung:'„Nur die im Zollhaus" grenzt eindeutig ein.' }
      ]},

      { nr:2, art:'interview', mal:2, aufgaben:[
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Wir haben die Ampelschaltung an vierzig Kreuzungen geändert. Die Wartezeit für Fußgänger ist im Schnitt um ein Viertel gesunken.',
          frage:'Aussage: Fußgänger warten jetzt kürzer.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:0,
          stelle:'um ein Viertel gesunken', erklaerung:'Direkt bestätigt, mit Zahl.' },
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Für den Autoverkehr bedeutet das rechnerisch etwas längere Wartezeiten. Gemessen haben wir das bisher nicht.',
          frage:'Aussage: Autofahrer warten messbar länger.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
          stelle:'Gemessen haben wir das bisher nicht', erklaerung:'Rechnerisch ist nicht gemessen.' },
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Dass die Umstellung teuer war, höre ich oft. Sie hat pro Kreuzung weniger gekostet als ein einziges neues Verkehrsschild samt Mast.',
          frage:'Aussage: Die Umstellung war teuer.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'weniger gekostet als ein einziges neues Verkehrsschild', erklaerung:'Sie greift den Vorwurf auf und widerlegt ihn.' },
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Ob sich die Zahl der Unfälle verändert hat, kann ich nach acht Monaten nicht seriös sagen. Dafür braucht man Jahre.',
          frage:'Aussage: Die Unfallzahlen sind gesunken.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
          stelle:'nicht seriös sagen', erklaerung:'Zu früh für eine Aussage — also offen.' },
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Beschwerden gab es anfangs viele, vor allem aus den Randbezirken. Inzwischen sind es deutlich weniger.',
          frage:'Aussage: Die Beschwerden haben abgenommen.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:0,
          stelle:'Inzwischen sind es deutlich weniger', erklaerung:'„Inzwischen" markiert die Veränderung.' },
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Übertragen lässt sich das Verfahren überall dort, wo die Ampeln zentral gesteuert werden. In kleineren Orten ist das oft nicht der Fall.',
          frage:'Aussage: Jede Gemeinde kann das Verfahren übernehmen.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'In kleineren Orten ist das oft nicht der Fall', erklaerung:'Die Bedingung schließt einen Teil ausdrücklich aus.' },
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Mein Lieblingsbefund ist ein anderer: Die Leute gehen seitdem häufiger zu Fuß zum Einkaufen. Das hatten wir überhaupt nicht erwartet.',
          frage:'Aussage: Der Effekt auf das Zu-Fuß-Gehen war eingeplant.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:1,
          stelle:'überhaupt nicht erwartet', erklaerung:'Ausdrücklich unerwartet.' },
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Was die Umstellung für Radfahrende bringt, war nicht Gegenstand unserer Untersuchung.',
          frage:'Aussage: Radfahrende profitieren ebenfalls.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:2,
          stelle:'nicht Gegenstand unserer Untersuchung', erklaerung:'Nicht untersucht heißt offen.' },
        { von:'Interview mit einer Verkehrsplanerin', wer:'Frau',
          text:'Weitermachen werden wir auf jeden Fall. Der Stadtrat hat die Mittel für vierzig weitere Kreuzungen bereits freigegeben.',
          frage:'Aussage: Die Finanzierung der nächsten Stufe steht.',
          opt:['stimmt','stimmt nicht','dazu wird nichts gesagt'], loesung:0,
          stelle:'Mittel für vierzig weitere Kreuzungen bereits freigegeben', erklaerung:'„bereits freigegeben" ist die Bestätigung.' }
      ]},

      { nr:3, art:'gespraech', mal:1, aufgaben:[
        { von:'Gespräch über Ehrenamt — Frau Krüger, Herr Ott',
          zeilen:[{wer:'Frau', text:'Uns fehlen nicht die Freiwilligen. Uns fehlen die, die länger als ein halbes Jahr bleiben.'},
                  {wer:'Mann', text:'Das sehe ich anders. Bei uns melden sich seit drei Jahren immer weniger überhaupt.'}],
          frage:'Worin unterscheiden sich die beiden?',
          opt:['Krüger sieht ein Haltungsproblem, Ott ein Zahlenproblem.','Beide sehen dasselbe Problem.','Ott hält Ehrenamt für überflüssig.'], loesung:0,
          stelle:'immer weniger überhaupt', erklaerung:'„Das sehe ich anders" kündigt den Unterschied an.' },
        { von:'Gespräch über Ehrenamt — Frau Krüger, Herr Ott',
          zeilen:[{wer:'Frau', text:'Vielleicht liegt es an der Aufgabe. Wer nur Stühle stellen darf, kommt kein zweites Mal.'},
                  {wer:'Mann', text:'Da haben Sie wahrscheinlich recht. Nur traut man Neuen eben ungern mehr zu.'}],
          frage:'Was räumt Herr Ott ein?',
          opt:['Dass die Aufgaben zu anspruchsvoll sind.','Dass man Neuen zu wenig zutraut.','Dass es genug Freiwillige gibt.'], loesung:1,
          stelle:'traut man Neuen eben ungern mehr zu', erklaerung:'Zustimmung plus Erklärung des eigenen Verhaltens.' },
        { von:'Gespräch über Ehrenamt — Frau Krüger, Herr Ott',
          zeilen:[{wer:'Frau', text:'Wir haben angefangen, nach vier Wochen ein Gespräch zu führen. Was willst du eigentlich hier? Das kostet zwanzig Minuten.'},
                  {wer:'Mann', text:'Und das wirkt?'},
                  {wer:'Frau', text:'Bei uns ja. Ob das überall so ist, weiß ich nicht.'}],
          frage:'Wie bewertet Frau Krüger das Gespräch nach vier Wochen?',
          opt:['Als allgemein wirksames Mittel.','Als in ihrem Fall wirksam.','Als zu aufwendig.'], loesung:1,
          stelle:'Ob das überall so ist, weiß ich nicht', erklaerung:'Sie begrenzt die Reichweite ihrer eigenen Erfahrung.' },
        { von:'Gespräch über Ehrenamt — Frau Krüger, Herr Ott',
          zeilen:[{wer:'Mann', text:'Geld hilft übrigens nicht. Wir haben eine Aufwandsentschädigung eingeführt, es kam kein Mensch mehr.'},
                  {wer:'Frau', text:'Das deckt sich mit allem, was ich dazu gelesen habe.'}],
          frage:'Was sagen beide über Geld?',
          opt:['Es löst das Problem.','Es hat keinen Effekt auf die Zahl.','Es vertreibt Freiwillige.'], loesung:1,
          stelle:'es kam kein Mensch mehr', erklaerung:'„kein Mensch mehr" heißt hier: niemand zusätzlich.' },
        { von:'Gespräch über Ehrenamt — Frau Krüger, Herr Ott',
          zeilen:[{wer:'Frau', text:'Was tatsächlich zieht, ist Verbindlichkeit in die andere Richtung: feste Termine, die wir auch einhalten.'},
                  {wer:'Mann', text:'Zugegeben, daran scheitern wir regelmäßig.'}],
          frage:'Was gibt Herr Ott zu?',
          opt:['Dass sein Verein feste Termine nicht einhält.','Dass feste Termine nichts bringen.','Dass er keine Freiwilligen will.'], loesung:0,
          stelle:'daran scheitern wir regelmäßig', erklaerung:'„daran" verweist auf die eingehaltenen Termine.' },
        { von:'Gespräch über Ehrenamt — Frau Krüger, Herr Ott',
          zeilen:[{wer:'Mann', text:'Bei den Jüngeren habe ich den Eindruck, sie wollen sich nicht festlegen.'},
                  {wer:'Frau', text:'Diesen Eindruck hatte ich auch — bis wir Projekte mit Enddatum angeboten haben. Seitdem kommen genau die.'}],
          frage:'Was widerlegt Frau Krügers Erfahrung?',
          opt:['Dass Jüngere sich grundsätzlich nicht binden wollen.','Dass Projekte ein Enddatum brauchen.','Dass Jüngere gar nicht kommen.'], loesung:0,
          stelle:'Seitdem kommen genau die', erklaerung:'Nicht die Bindung ist das Problem, sondern die offene Dauer.' },
        { von:'Gespräch über Ehrenamt — Frau Krüger, Herr Ott',
          zeilen:[{wer:'Frau', text:'Ich würde jedem Verein raten: Fragt die, die gegangen sind, warum.'},
                  {wer:'Mann', text:'Das traut sich kaum jemand.'},
                  {wer:'Frau', text:'Eben deshalb lohnt es sich.'}],
          frage:'Warum empfiehlt sie, Ehemalige zu befragen?',
          opt:['Weil es einfach ist.','Weil es kaum jemand tut und darin die Chance liegt.','Weil der Verein dazu verpflichtet ist.'], loesung:1,
          stelle:'Eben deshalb lohnt es sich', erklaerung:'„Eben deshalb" dreht den Einwand in ein Argument.' },
        { von:'Gespräch über Ehrenamt — Frau Krüger, Herr Ott',
          zeilen:[{wer:'Mann', text:'Wenn ich eines mitnehme: nicht mehr Werbung, sondern bessere erste Wochen.'},
                  {wer:'Frau', text:'Genau so.'}],
          frage:'Was ist das Fazit?',
          opt:['Mehr Werbung.','Bessere Einarbeitung.','Höhere Entschädigung.'], loesung:1,
          stelle:'bessere erste Wochen', erklaerung:'„nicht …, sondern" im Schlusssatz.' }
      ]},

      { nr:4, art:'vortrag', mal:2, aufgaben:[
        { von:'Vortrag über Lebensmittelverschwendung', wer:'Frau',
          text:'Ich werde drei Zahlen nennen und bei jeder sagen, was sie nicht bedeutet. Das ist mir wichtiger als die Zahlen selbst.',
          frage:'Was kündigt die Vortragende an?',
          opt:['Drei Zahlen mit Einordnung.','Drei Lösungsvorschläge.','Eine Zusammenfassung der Forschung.'], loesung:0,
          stelle:'was sie nicht bedeutet', erklaerung:'Das Programm steht im ersten Satz.' },
        { von:'Vortrag über Lebensmittelverschwendung', wer:'Frau',
          text:'Erste Zahl: Rund sechzig Prozent der weggeworfenen Lebensmittel stammen aus Privathaushalten. Das bedeutet nicht, dass Haushalte die Hauptschuldigen sind — es bedeutet, dass dort am Ende der Kette weggeworfen wird.',
          frage:'Wie ordnet sie die sechzig Prozent ein?',
          opt:['Als Schuldzuweisung an Haushalte.','Als Hinweis auf die Stelle in der Kette.','Als Messfehler.'], loesung:1,
          stelle:'am Ende der Kette weggeworfen wird', erklaerung:'Die Zahl beschreibt den Ort, nicht die Ursache.' },
        { von:'Vortrag über Lebensmittelverschwendung', wer:'Frau',
          text:'Zweite Zahl: Ein Drittel davon ist Brot. Das heißt aber nicht, dass wir zu viel Brot kaufen — es heißt, dass Brot am schnellsten unansehnlich wird.',
          frage:'Was folgt aus der Brot-Zahl?',
          opt:['Wir kaufen zu viel Brot.','Brot verdirbt optisch schnell.','Brot ist zu teuer.'], loesung:1,
          stelle:'am schnellsten unansehnlich wird', erklaerung:'Dasselbe Muster: Ablehnung der naheliegenden Deutung, dann die eigene.' },
        { von:'Vortrag über Lebensmittelverschwendung', wer:'Frau',
          text:'Dritte Zahl, und die überrascht die meisten: Haushalte mit Kindern werfen pro Person weniger weg als Einpersonenhaushalte. Packungsgrößen erklären das zum großen Teil.',
          frage:'Warum werfen Einpersonenhaushalte mehr weg?',
          opt:['Sie kochen seltener.','Die Packungen sind zu groß.','Sie kaufen teurer ein.'], loesung:1,
          stelle:'Packungsgrößen erklären das', erklaerung:'Die Erklärung folgt direkt auf die Zahl.' },
        { von:'Vortrag über Lebensmittelverschwendung', wer:'Frau',
          text:'Aus all dem folgt für mich nicht, dass man an die Vernunft der Einzelnen appellieren sollte. Appelle wirken, aber nur ein paar Wochen.',
          frage:'Was hält sie von Appellen?',
          opt:['Sie wirken dauerhaft.','Sie wirken nur kurz.','Sie wirken gar nicht.'], loesung:1,
          stelle:'nur ein paar Wochen', erklaerung:'„wirken, aber nur" ist die Einschränkung, nicht die Verneinung.' },
        { von:'Vortrag über Lebensmittelverschwendung', wer:'Frau',
          text:'Wirksam ist, was die Entscheidung leichter macht: kleinere Packungen, klarere Daten, Kühlschränke, die man überblickt. Das klingt banal und ist es auch.',
          frage:'Was hält sie für wirksam?',
          opt:['Strengere Regeln.','Praktische Erleichterungen im Alltag.','Höhere Preise.'], loesung:1,
          stelle:'die Entscheidung leichter macht', erklaerung:'„Das klingt banal und ist es auch" ist kein Widerruf, sondern Bekräftigung.' },
        { von:'Vortrag über Lebensmittelverschwendung', wer:'Frau',
          text:'Lassen Sie mich mit dem schließen, was ich nicht weiß: Ob diese Maßnahmen zusammengenommen reichen, um das Ziel für 2030 zu erreichen, kann ich Ihnen nicht sagen.',
          frage:'Womit schließt sie?',
          opt:['Mit einer Erfolgsgarantie.','Mit einem offenen Punkt.','Mit einer Forderung an die Politik.'], loesung:1,
          stelle:'kann ich Ihnen nicht sagen', erklaerung:'„mit dem, was ich nicht weiß" kündigt das Eingeständnis an.' }
      ]}
    ]}
  ]
};
