/* deutschoderwas club — echte Beispielsätze zum Wortschatz.
   Schlüssel: das Wort genau so, wie es in uebungen.js steht.
   Wert: ein Satz aus dem Alltag. Das Zielwort steht zwischen §…§ —
   der Trainer macht daraus den gelben Textmarker.
   102 Sätze stammen aus den vorhandenen Lückenaufgaben,
   236 sind für die Wörter geschrieben, die noch keinen hatten. */
window.VOKABEL_SAETZE={
"Automatisierung": "Durch die §Automatisierung§ macht die Maschine viele Schritte ganz allein.",
"Datenschutz": "Beim Einsatz von KI darf der §Datenschutz§ nicht vergessen werden – der Schutz persönlicher Daten.",
"Daumen drücken": "Morgen habe ich meine Prüfung, bitte §Daumen drücken§!",
"Echt jetzt?": "Der Zug fällt schon wieder aus — §Echt jetzt?§",
"Effizienz": "KI steigert die §Effizienz§ in vielen Bereichen enorm.",
"Fuß fassen": "In der neuen Stadt habe ich langsam §Fuß gefasst§.",
"Füllung": "Der Zahnarzt hat das Loch mit einer §Füllung§ geschlossen.",
"Hals- und Beinbruch": "Morgen ist dein Vorstellungsgespräch, ich sage nur: §Hals- und Beinbruch§!",
"Ich bin platt.": "Nach acht Stunden im Lager §bin ich platt§.",
"Kein Ding": "Kannst du mir kurz helfen? Klar, §kein Ding§.",
"Kontrolle": "Zweimal im Jahr gehe ich zur §Kontrolle§ beim Zahnarzt.",
"Krone": "Der Zahn war kaputt, jetzt habe ich eine §Krone§.",
"Künstliche Intelligenz": "§Künstliche Intelligenz§ hilft mir, meine E-Mails schneller zu schreiben.",
"Läuft": "Wie geht's? – §Läuft§! Und bei dir?",
"Quatsch!": "Du bist zu alt zum Lernen? §Quatsch!§",
"Risiko": "Ein großes §Risiko§ ist, dass viele Menschen ihre Jobs verlieren.",
"Schwein haben": "Bei der Wohnungssuche §habe ich Schwein gehabt§.",
"Spritze": "Damit die Behandlung nicht weh tut, bekomme ich eine §Spritze§ (Betäubung).",
"Termin": "Ich möchte einen §Termin§ machen – haben Sie morgen Zeit?",
"Tomaten auf den Augen haben": "Der Schlüssel lag direkt vor mir, ich muss §Tomaten auf den Augen haben§.",
"Umschulung": "Nach der §Umschulung§ arbeitet mein Nachbar jetzt in einem neuen Beruf.",
"Verantwortung": "Wer trägt die §Verantwortung§, wenn die KI einen Fehler macht?",
"Zahn": "Mein linker §Zahn§ tut seit gestern richtig weh.",
"Zahnpasta": "Putz deine Zähne zweimal am Tag mit einer Zahnbürste und §Zahnpasta§.",
"Zahnschmerzen": "Ich habe seit gestern starke §Zahnschmerzen§ und kann nicht schlafen.",
"Zahnseide": "Abends benutze ich §Zahnseide§ zwischen den Zähnen.",
"Zusammenarbeit": "Eine gute §Zusammenarbeit§ von Mensch und KI nutzt das Beste aus beiden Welten.",
"abbiegen": "An der Ecke nach rechts §abbiegen§.",
"abwägen": "Ich §wäge§ noch §ab§, ob ich den neuen Job nehme.",
"alles in Butter": "Wir haben in Ruhe geredet, jetzt ist wieder §alles in Butter§.",
"anstoßen": "Wir §stoßen§ mit Sekt auf das neue Jahr §an§.",
"atemberaubend": "Oben auf dem Berg hatten wir eine §atemberaubende§ Aussicht.",
"auf dem Schlauch stehen": "Erklär es bitte noch mal, ich §stehe auf dem Schlauch§.",
"auf den Keks gehen": "Das ständige Klingeln am Handy §geht mir auf den Keks§.",
"auf die Nerven gehen": "Wenn er beim Essen so laut kaut, §geht mir das auf die Nerven§.",
"auf die lange Bank schieben": "Du solltest den Anruf beim Arzt nicht §auf die lange Bank schieben§.",
"aufgeregt": "Vor meinem ersten Arbeitstag war ich sehr §aufgeregt§.",
"ausgezeichnet": "Dein Zeugnis ist §ausgezeichnet§, du hast überall die beste Note.",
"authentisch": "Du wirkst §authentisch§, wenn du einfach ganz normal sprichst.",
"backen": "Zum Geburtstag §backe§ ich einen Kuchen im Ofen.",
"beeindruckend": "Dein Deutsch ist nach einem Jahr wirklich §beeindruckend§.",
"begründen": "Kannst du bitte §begründen§, warum du den Termin absagst?",
"bezaubernd": "In dem blauen Kleid siehst du heute §bezaubernd§ aus.",
"bohren": "Der Zahnarzt muss den Zahn §bohren§, das Geräusch ist laut.",
"braten": "Ich §brate§ das Fleisch fünf Minuten in der Pfanne.",
"chaotisch": "Mein Schreibtisch ist total §chaotisch§, ich finde nichts wieder.",
"checken": "Erst nach der dritten Erklärung habe ich es §gecheckt§.",
"dankbar": "Danke für die Hilfe, ich bin dir sehr §dankbar§.",
"das Angebot": "Die Tomaten sind heute im §Angebot§.",
"das Ankommen": "Das §Ankommen§ in einem neuen Land dauert seine Zeit.",
"das Auto": "Am Wochenende fahren wir mit dem §Auto§ zu meiner Familie.",
"das Bad": "Morgens dusche ich schnell im §Bad§ und putze mir die Zähne.",
"das Bargeld": "Der Bäcker nimmt keine Karte, ich brauche §Bargeld§.",
"das Bein": "Nach dem langen Spaziergang ist mein rechtes §Bein§ müde.",
"das Bett": "Um elf Uhr gehe ich ins §Bett§ und schlafe sofort ein.",
"das Fach": "Mein Lieblings §fach§ ist Deutsch.",
"das Fahrrad": "Zum Supermarkt nehme ich lieber das §Fahrrad§ als das Auto.",
"das Fenster": "Durch das große §Fenster§ kommt viel Licht ins Zimmer.",
"das Fernweh": "Wenn ich Fotos vom Meer sehe, bekomme ich §Fernweh§.",
"das Fest": "Jedes Jahr im Sommer feiert unser Dorf ein großes §Fest§.",
"das Festessen": "An Weihnachten gibt es bei uns immer ein großes §Festessen§.",
"das Feuerwerk": "Um Mitternacht leuchtet ein buntes §Feuerwerk§ über der Stadt.",
"das Fieber": "Mir geht es schlecht, ich habe hohes §Fieber§ und liege im Bett.",
"das Fingerspitzengefühl": "Für dieses Gespräch mit dem Chef brauchst du §Fingerspitzengefühl§.",
"das Gehalt": "Mein §Gehalt§ kommt jeden Monat am Ersten aufs Konto.",
"das Geld": "Am Monatsende ist mein §Geld§ oft schon fast weg.",
"das Gepäck": "Mein §Gepäck§ ist schwer, ich habe zwei große Taschen dabei.",
"das Geschenk": "Für Omas Geburtstag habe ich ein kleines §Geschenk§ gekauft.",
"das Gewürz": "Salz und Pfeffer sind die wichtigsten §Gewürze§ in meiner Küche.",
"das Gleis": "Der Zug nach Köln steht heute auf §Gleis§ drei.",
"das Haus": "Meine Eltern wohnen in einem kleinen §Haus§ mit Garten.",
"das Heimweh": "Am Anfang hatte ich starkes §Heimweh§ nach meiner Familie.",
"das Internet": "Ohne §Internet§ kann ich keine Videos schauen und nichts suchen.",
"das Kleingeld": "Für den Einkaufswagen brauchst du einen Euro §Kleingeld§.",
"das Klischee": "Dass alle Deutschen immer pünktlich sind, ist nur ein §Klischee§.",
"das Kopfkino": "Vor jeder Prüfung startet bei mir sofort das §Kopfkino§.",
"das Kostüm": "Im Karneval trage ich ein selbst gemachtes §Kostüm§.",
"das Medikament": "Der Arzt hat mir ein §Medikament§ gegen die Schmerzen verschrieben.",
"das Meer": "Im Urlaub schwimme ich gern im salzigen §Meer§.",
"das Messer": "Mit dem §Messer§ schneide ich das Brot in Scheiben.",
"das Missverständnis": "Das war nur ein §Missverständnis§, wir haben uns falsch verstanden.",
"das Passwort": "Ich habe mein §Passwort§ vergessen und komme nicht ins Konto.",
"das Profilbild": "Für mein §Profilbild§ nehme ich ein freundliches Foto von mir.",
"das Recycling": "Durch §Recycling§ wird aus altem Papier wieder neues Papier.",
"das Rezept": "Bevor ich koche, lese ich das §Rezept§ genau durch.",
"das Schlafzimmer": "Mein §Schlafzimmer§ ist klein, aber ich schlafe dort sehr gut.",
"das Sofa": "Nach der Arbeit falle ich müde aufs §Sofa§.",
"das Studium": "Nach dem Abitur hat er ein §Studium§ an der Universität begonnen.",
"das Ticket": "Kauf dir vorher ein §Ticket§ für die U-Bahn.",
"das Tier": "Im Zoo habe ich viele §Tiere§ gesehen, zum Beispiel Affen.",
"das Vorstellungsgespräch": "Beim §Vorstellungsgespräch§ triffst du den Arbeitgeber persönlich.",
"das Vorurteil": "Ein §Vorurteil§ ist eine feste Meinung ohne echte Erfahrung.",
"das WLAN": "Wie lautet das §WLAN§ -Passwort hier?",
"das Wechselgeld": "Hier ist Ihr §Wechselgeld§, 2 Euro zurück.",
"das Wissen": "Dein §Wissen§ aus dem Kurs hilft dir jeden Tag im Alltag.",
"das Wohnzimmer": "Am Abend sitzen wir im §Wohnzimmer§ und sehen fern.",
"das Zeugnis": "Im §Zeugnis§ stehen alle Noten aus dem ganzen Schuljahr.",
"das soziale Netzwerk": "Instagram ist ein §soziales Netzwerk§, dort teilen Menschen ihre Fotos.",
"dekorieren": "Wir §dekorieren§ das Zimmer mit Luftballons.",
"den Faden verlieren": "Mitten im Gespräch habe ich leider §den Faden verloren§.",
"den Müll trennen": "In Deutschland musst du zu Hause den §Müll trennen§.",
"den Nagel auf den Kopf treffen": "Mit deiner Antwort hast du §den Nagel auf den Kopf getroffen§.",
"der Abschluss": "Nach dem §Abschluss§ möchte ich arbeiten.",
"der Account": "Für die App brauchst du einen §Account§.",
"der Arbeitgeber": "Mein neuer §Arbeitgeber§ bezahlt mir das Ticket für die Bahn.",
"der Arbeitnehmer": "Als §Arbeitnehmer§ hast du in Deutschland mindestens 20 Tage Urlaub.",
"der Arm": "Beim Sturz auf dem Eis habe ich mir den §Arm§ gebrochen.",
"der Arzt": "Wenn du seit Tagen Fieber hast, geh bitte zum §Arzt§.",
"der Bahnhof": "Am §Bahnhof§ warten jeden Morgen viele Menschen auf ihren Zug.",
"der Bahnsteig": "Wir warten auf dem §Bahnsteig§, der Zug kommt gleich.",
"der Balkon": "Im Sommer sitze ich gern auf dem §Balkon§.",
"der Bauch": "Der Arzt drückt auf meinen §Bauch§ und fragt nach Schmerzen.",
"der Baum": "Vor unserem Haus steht ein alter, sehr hoher §Baum§.",
"der Beitrag": "Dein §Beitrag§ auf Instagram hat vielen Leuten gefallen.",
"der Berg": "Von oben auf dem §Berg§ sieht man die ganze Stadt.",
"der Beruf": "Mein §Beruf§ ist Krankenpflegerin, ich arbeite in einem Krankenhaus.",
"der Brauch": "Eier bemalen ist ein alter §Brauch§ an Ostern.",
"der Bus": "Ich fahre jeden Morgen mit dem §Bus§ zur Arbeit.",
"der Chef": "Mein §Chef§ ist sehr nett und hilfsbereit.",
"der Einkaufswagen": "Im Supermarkt lege ich das Gemüse in den §Einkaufswagen§.",
"der Feierabend": "Endlich §Feierabend§, die Arbeit ist geschafft!",
"der Feiertag": "Am 25. Dezember ist ein gesetzlicher §Feiertag§ in Deutschland.",
"der Flug": "Der §Flug§ nach Madrid dauert nur zwei Stunden.",
"der Flughafen": "Vom §Flughafen§ fliegen wir morgen früh nach Istanbul.",
"der Fußgänger": "Bei Rot bleiben die §Fußgänger§ stehen.",
"der Hammer sein": "Das neue Café in unserer Straße §ist der Hammer§.",
"der Hausmeister": "Die Heizung ist kaputt. Ich rufe den §Hausmeister§ an.",
"der Herd": "Ich stelle den Topf auf den §Herd§ und mache ihn heiß.",
"der Jahreswechsel": "An Silvester feiern wir den §Jahreswechsel§ mit Feuerwerk.",
"der Klimawandel": "Durch den §Klimawandel§ werden die Sommer bei uns immer heißer.",
"der Koffer": "Vor der Reise packe ich meinen §Koffer§ ganz in Ruhe.",
"der Kopf": "Mir tut seit heute Morgen der §Kopf§ weh.",
"der Kulturschock": "Anfangs hatte ich einen kleinen §Kulturschock§, weil alles anders war.",
"der Kummerspeck": "Nach der Trennung habe ich viel gegessen, daher der §Kummerspeck§.",
"der Kurs": "Ich besuche abends einen §Kurs§ für Deutsch als Zweitsprache.",
"der Körper": "Beim Schwimmen bewegst du deinen ganzen §Körper§.",
"der Lebenslauf": "Bitte bring deinen §Lebenslauf§ zum Gespräch mit.",
"der Link": "Klick einfach auf den §Link§, dann öffnet sich die Seite.",
"der Lärm": "Der §Lärm§ von der Baustelle weckt mich jeden Morgen.",
"der Löffel": "Die Suppe esse ich mit einem großen §Löffel§.",
"der Müll": "Wir trennen den §Müll§ für das Recycling.",
"der Ohrwurm": "Ich kann den Song nicht mehr loswerden, ein echter §Ohrwurm§.",
"der Perspektivwechsel": "Ein §Perspektivwechsel§ hat mir geholfen, den Streit zu verstehen.",
"der Preis": "Der §Preis§ steht klein auf dem Schild am Regal.",
"der Rabatt": "Mit dem Gutschein bekommst du 10 % §Rabatt§.",
"der Regen": "Bei §Regen§ nehme ich immer einen Schirm mit.",
"der Reisepass": "Vergiss deinen §Reisepass§ nicht – wir fliegen ins Ausland!",
"der Rettungsturm": "Auf dem §Rettungsturm§ wacht ein Rettungsschwimmer.",
"der Rücken": "Vom langen Sitzen im Büro schmerzt mein §Rücken§.",
"der Schimmel": "An der Badezimmerdecke sind schwarze Flecken. Das ist §Schimmel§.",
"der Schnee": "Im Winter liegt überall §Schnee§.",
"der Schrank": "Die Jacken hängen im §Schrank§.",
"der Schüler": "Die §Schüler§ warten vor dem Klassenzimmer auf den Unterricht.",
"der Spam": "In meinem Postfach landet jeden Tag viel §Spam§ mit Werbung.",
"der Stadtplan": "Auf dem §Stadtplan§ finde ich schnell die richtige Straße.",
"der Strandkorb": "Im §Strandkorb§ sitzt man gemütlich am Strand und liest.",
"der Streber": "Die anderen nennen ihn §Streber§, weil er jeden Abend lernt.",
"der Stuhl": "Setz dich bitte auf den §Stuhl§ neben dem Tisch.",
"der Stundenplan": "Im §Stundenplan§ steht, wann welcher Unterricht beginnt.",
"der Teller": "Ich lege das warme Essen auf einen sauberen §Teller§.",
"der Teppich": "Im Wohnzimmer liegt ein weicher §Teppich§ auf dem Boden.",
"der Termin": "Bitte gib mir einen §Termin§ für nächste Woche.",
"der Topf": "Das Nudelwasser kocht im großen §Topf§.",
"der Umzug": "Beim §Umzug§ ziehen bunte Wagen durch die ganze Stadt.",
"der Urlaub": "Im §Urlaub§ arbeite ich nicht und erhole mich richtig.",
"der Vermieter": "Der §Vermieter§ hat uns die Schlüssel für die Wohnung gegeben.",
"der Vertrag": "Vor dem ersten Arbeitstag unterschreibt man den §Vertrag§.",
"der Wald": "Am Sonntag gehen wir im §Wald§ zwischen den Bäumen spazieren.",
"der Weltschmerz": "Wenn ich abends die Nachrichten sehe, packt mich der §Weltschmerz§.",
"der Wind": "Zieh eine Jacke an, draußen weht ein kalter §Wind§.",
"der Zebrastreifen": "Am §Zebrastreifen§ kannst du sicher über die Straße gehen.",
"der Zeitgeist": "Die Musik der Achtziger zeigt gut den §Zeitgeist§ von damals.",
"der innere Schweinehund": "Morgens muss ich meinen §inneren Schweinehund§ überwinden und joggen gehen.",
"die Abfahrt": "Die §Abfahrt§ des Zuges ist um 14 Uhr.",
"die Abteilung": "Ich arbeite in der §Abteilung§ für Kundenservice.",
"die Ampel": "Warte bitte, bis die §Ampel§ grün wird.",
"die Apotheke": "Das Medikament bekommst du in der §Apotheke§.",
"die App": "Auf meinem Handy habe ich eine §App§ zum Deutschlernen.",
"die Bewerbung": "Ich habe meine §Bewerbung§ mit Lebenslauf und Zeugnissen geschickt.",
"die Boje": "Schwimm bitte nicht weiter als bis zur roten §Boje§.",
"die Bordkarte": "Am Flughafen zeigst du deine §Bordkarte§ und deinen Pass.",
"die Düne": "Hinter dem Strand liegt eine hohe §Düne§ aus weichem Sand.",
"die E-Mail": "Ich habe dem Amt gestern eine §E-Mail§ geschrieben.",
"die Ebbe / die Flut": "Bei §Ebbe§ liegt der Strand trocken, bei Flut steht dort Wasser.",
"die Erfahrung": "Ich habe zehn Jahre §Erfahrung§ als Köchin.",
"die Erkältung": "Ich huste und niese, bestimmt ist das eine §Erkältung§.",
"die Feier / das Fest": "Zu meiner §Feier§ am Samstag kommen zwanzig Freunde.",
"die Gabel": "Die Nudeln esse ich mit der §Gabel§, nicht mit den Händen.",
"die Geborgenheit": "In der Küche meiner Mutter spüre ich §Geborgenheit§.",
"die Gemütlichkeit": "Bei Kerzen und Tee herrscht richtige §Gemütlichkeit§.",
"die Haltestelle": "Die Bus §haltestelle§ ist direkt vor dem Supermarkt.",
"die Hausaufgabe": "Mein Sohn macht seine §Hausaufgaben§ jeden Tag nach dem Essen.",
"die Heimat": "Nach zehn Jahren in Berlin ist diese Stadt meine §Heimat§.",
"die Identität": "Meine Sprache und meine Geschichte gehören zu meiner §Identität§.",
"die Integration": "Sprache ist der Schlüssel zur §Integration§ in ein neues Land.",
"die Karte": "Kann ich mit §Karte§ bezahlen?",
"die Kasse": "An der §Kasse§ bezahle ich und bekomme mein Wechselgeld zurück.",
"die Katze aus dem Sack lassen": "Jetzt will ich §die Katze aus dem Sack lassen§: Wir ziehen um!",
"die Kollegin": "Meine §Kollegin§ hilft mir immer, wenn ich etwas nicht verstehe.",
"die Krankmeldung": "Der Arzt schreibt mir eine §Krankmeldung§ für die Arbeit.",
"die Kreuzung": "An der nächsten §Kreuzung§ biegst du links ab.",
"die Küche": "In der §Küche§ koche ich fast jeden Abend frisch.",
"die Kündigung": "Nach der §Kündigung§ suche ich sofort eine neue Stelle.",
"die Lampe": "Mach bitte die §Lampe§ an, es ist dunkel.",
"die Lehrerin": "Unsere §Lehrerin§ erklärt die Grammatik immer ruhig und sehr geduldig.",
"die Mahlzeit": "Zum Frühstück gibt es heute eine besondere §Mahlzeit§.",
"die Mehrsprachigkeit": "Deine §Mehrsprachigkeit§ ist ein großer Vorteil bei der Jobsuche.",
"die Miete": "Die §Miete§ ist diesen Monat schon bezahlt.",
"die Nachfrage": "Nach dem Gespräch hatte ich noch eine kurze §Nachfrage§.",
"die Nachricht": "Ich schreibe dir gleich eine kurze §Nachricht§ per WhatsApp.",
"die Nase voll haben": "Ich §habe die Nase voll§ von den langen Wartezeiten.",
"die Note": "Für meinen Test habe ich die §Note§ Zwei bekommen.",
"die Offenheit": "Jemand, der offen und neugierig für Fremdes ist, zeigt §Offenheit§.",
"die Pfanne": "Das Ei brate ich in einer heißen §Pfanne§.",
"die Pflanze": "Meine §Pflanze§ auf dem Fensterbrett braucht jeden Tag Wasser.",
"die Praxis": "Die §Praxis§ von Doktor Weber ist am Freitag geschlossen.",
"die Prüfung": "Ich muss noch für die §Prüfung§ lernen.",
"die Quittung": "Brauchen Sie eine §Quittung§?",
"die Rechnung": "Nach dem Essen bitte ich um die §Rechnung§.",
"die Reise": "Die §Reise§ nach Hamburg hat nur vier Stunden gedauert.",
"die Richtung": "Entschuldigung, in welche §Richtung§ muss ich zum Bahnhof gehen?",
"die Ruhezeit": "Nach 22 Uhr ist §Ruhezeit§ – dann sollte es leise sein.",
"die Schadenfreude": "Ein bisschen §Schadenfreude§ ist dabei, wenn mein Bruder verliert.",
"die Schmerzen": "Ich habe starke §Schmerzen§ im Kopf.",
"die Schule": "Meine Tochter lernt in der §Schule§ lesen, schreiben und rechnen.",
"die Sehenswürdigkeit": "In Berlin habe ich viele §Sehenswürdigkeiten§ besichtigt, zum Beispiel den Fernsehturm.",
"die Sehnsucht": "Nach zehn Jahren habe ich große §Sehnsucht§ nach meiner Heimat.",
"die Sitte": "Der Maibaum im Dorf ist eine alte §Sitte§ in Bayern.",
"die Sonne": "Heute scheint die §Sonne§ den ganzen Tag.",
"die Stadt": "In meiner §Stadt§ wohnen viele Menschen aus verschiedenen Ländern.",
"die Stelle": "Ich habe mich auf eine neue §Stelle§ beworben.",
"die Stimmung": "Die §Stimmung§ beim Fest ist sehr fröhlich und ausgelassen. Welches Wort passt?",
"die Straße": "Schau nach links und rechts, bevor du über die §Straße§ gehst.",
"die Suchmaschine": "Google ist die bekannteste §Suchmaschine§ im Internet.",
"die Teilzeit": "Sie arbeitet nur 20 Stunden, also in §Teilzeit§.",
"die Temperatur": "Heute liegt die §Temperatur§ bei fünf Grad, zieh dich warm an.",
"die Toleranz": "Im Alltag braucht man §Toleranz§ für andere Meinungen und Bräuche.",
"die Torschlusspanik": "Mit vierzig bekommen viele §Torschlusspanik§ und ändern schnell ihr Leben.",
"die Torte": "Auf dem Tisch steht eine große §Torte§ mit Kerzen.",
"die Tüte": "An der Kasse kaufe ich noch eine §Tüte§ für die Einkäufe.",
"die U-Bahn": "Die §U-Bahn§ fährt unter der Erde und ist meistens schneller.",
"die Umwelt": "Wir sollten die §Umwelt§ schützen.",
"die Universität": "An der §Universität§ studiert meine Schwester seit drei Jahren Medizin.",
"die Unterkunft": "Unsere §Unterkunft§ liegt direkt am Strand.",
"die Verspätung": "Wegen einer §Verspätung§ haben wir den Anschluss verpasst.",
"die Verwandten": "Zu Weihnachten treffen sich alle §Verwandten§ bei den Großeltern.",
"die Vielfalt": "Die §Vielfalt§ macht eine Stadt lebendig und interessant.",
"die Vorfreude": "Die §Vorfreude§ auf das Wochenende ist groß.",
"die Welle": "Am Strand laufen die §Wellen§ ans Ufer und machen meine Füße nass.",
"die Wohnung": "Wir suchen eine größere §Wohnung§ mit Balkon.",
"die Wolke": "Heute sind keine §Wolken§ am Himmel, die Sonne scheint.",
"die Wurzeln": "Ich bin stolz auf meine §Wurzeln§ und meine kulturelle Herkunft.",
"die Zugehörigkeit": "Im Sportverein habe ich zum ersten Mal §Zugehörigkeit§ gespürt.",
"die Zutat": "Wir brauchen noch eine wichtige §Zutat§ : Knoblauch.",
"die Überstunde": "Diese Woche habe ich fünf §Überstunden§ gemacht.",
"differenzieren": "Da muss ich §differenzieren§ : Es kommt auf die Situation an.",
"doch": "Du magst kein Brot? §Doch§, ich esse es sehr gern.",
"ehrgeizig": "Sie will unbedingt erfolgreich sein, sie ist §ehrgeizig§.",
"ehrlich": "Mein Freund ist immer §ehrlich§, auch wenn die Wahrheit wehtut.",
"einladen": "Ich §lade§ dich herzlich zu meinem Geburtstag §ein§.",
"entsetzlich": "Der Zug hatte drei Stunden Verspätung, das war §entsetzlich§.",
"entspannt": "Im Urlaub am Strand bin ich richtig §entspannt§.",
"enttäuscht": "Ich war §enttäuscht§, weil ich die Stelle nicht bekommen habe.",
"erleichtert": "Nach der bestandenen Prüfung war ich richtig §erleichtert§.",
"ersetzen": "Ein Computer kann viele Aufgaben übernehmen, aber keine Kollegen §ersetzen§.",
"fantastisch": "Du hast die Prüfung bestanden, das ist §fantastisch§!",
"faul": "Am Sonntag bin ich §faul§ und bleibe lange im Bett.",
"frustriert": "Der Drucker geht schon wieder nicht, ich bin echt §frustriert§.",
"furchtbar": "Der Stau heute war wirklich §furchtbar§.",
"geduldig": "Hab Geduld mit dem Kind – sei §geduldig§.",
"gelangweilt": "Im Wartezimmer saß ich §gelangweilt§ und schaute auf mein Handy.",
"genial": "Deine Idee mit dem Lernplan ist wirklich §genial§.",
"geradeaus": "Geh immer §geradeaus§, dann siehst du den Bahnhof.",
"gerührt": "Bei der Rede meiner Tochter war ich zu Tränen §gerührt§.",
"gestresst": "Mit Job, Kindern und Deutschkurs bin ich oft §gestresst§.",
"gesund": "Ich esse viel Gemüse und bleibe so §gesund§.",
"glücklich": "Seit dem Umzug in die neue Wohnung bin ich richtig §glücklich§.",
"gratulieren": "Ich §gratuliere§ dir herzlich zur bestandenen Prüfung.",
"großartig": "Das Konzert war einfach §großartig§!",
"großzügig": "Meine Nachbarin ist §großzügig§ und teilt ihr Essen gern mit uns.",
"gut →": "Das Essen bei deiner Familie war einfach §großartig§.",
"günstig": "Bei diesem Discounter ist das Obst besonders §günstig§.",
"halb so wild": "Du kommst zehn Minuten später? §Halb so wild§.",
"herrlich": "Nach der Arbeit ist eine warme Dusche einfach §herrlich§.",
"herunterladen": "Ich muss die neue App noch §herunterladen§.",
"hervorragend": "Dein Deutsch ist inzwischen §hervorragend§.",
"hilfsbereit": "Er hilft jedem gern, er ist sehr §hilfsbereit§.",
"hochladen": "Ich §lade§ die Fotos vom Urlaub §hoch§.",
"humorvoll": "Mein Chef ist §humorvoll§ und bringt uns jeden Morgen zum Lachen.",
"ins kalte Wasser springen": "Am ersten Arbeitstag musst du einfach §ins kalte Wasser springen§.",
"ist mir Wurst": "Ob wir Pizza oder Pasta essen, §ist mir Wurst§.",
"keinen Bock haben": "Ich §habe keinen Bock§, heute noch einkaufen zu gehen.",
"kochen": "Heute §koche§ ich eine warme Suppe für meine Familie.",
"kostenlos": "Der Deutschkurs beim Verein ist für dich §kostenlos§.",
"krank": "Ich bleibe heute zu Hause, ich bin §krank§.",
"kühlen": "Im Sommer §kühle§ ich die Getränke im Kühlschrank.",
"launisch": "Meine Kollegin ist oft §launisch§, ihre Stimmung wechselt sehr schnell.",
"nervös": "Vor dem Vorstellungsgespräch war ich sehr §nervös§.",
"neugierig": "Mein Sohn ist sehr §neugierig§ und fragt den ganzen Tag warum.",
"nuanciert": "Deine Antwort war sehr §nuanciert§, nicht einfach nur gut oder schlecht.",
"nur Bahnhof verstehen": "Der Beamte hat so schnell gesprochen, ich §habe nur Bahnhof verstanden§.",
"ordentlich": "Meine Schwester plant alles genau, sie ist sehr §ordentlich§.",
"passt schon": "Sorry, ich bin zu spät! – §Passt schon§, kein Ding.",
"pauschal": "Man kann das nicht §pauschal§ sagen – jeder Mensch ist anders.",
"pünktlich": "Der Zug war heute §pünktlich§, ich kam rechtzeitig zur Arbeit.",
"ragen": "Vor dem Strand §ragt§ ein großer Felsen aus dem Wasser.",
"reinen Wein einschenken": "Irgendwann musst du deiner Chefin §reinen Wein einschenken§ und alles erklären.",
"relativieren": "Ich möchte meine Aussage §relativieren§ : Es gibt auch andere Sichtweisen.",
"riesig": "Der neue Supermarkt ist §riesig§, ich finde nichts mehr.",
"schlecht →": "Das Wetter war in unserem Urlaub leider §furchtbar§.",
"schmücken": "Wir §schmücken§ den Weihnachtsbaum mit bunten Kugeln.",
"schneiden": "Ich §schneide§ die Zwiebel in ganz kleine Stücke.",
"schrecklich": "Der Streit mit meinem Nachbarn war wirklich §schrecklich§.",
"schön →": "Der Park sieht im Frühling wirklich §wunderschön§ aus.",
"schüchtern": "Trau dich, sag deine Meinung – sei nicht so §schüchtern§.",
"selbstbewusst": "Im Bewerbungsgespräch war sie ruhig und §selbstbewusst§.",
"sich bemühen": "Ich §bemühe§ mich jeden Tag, mehr Deutsch zu sprechen.",
"sich beschweren": "Ich habe mich beim Vermieter über die kaputte Heizung §beschwert§.",
"speichern": "Bitte §speichere§ das Dokument, sonst ist deine Arbeit weg.",
"stolz": "Sie hat den Wettbewerb gewonnen und ist sehr §stolz§.",
"stur": "Mein Vater ist so §stur§, er ändert nie seine Meinung.",
"sympathisch": "Meine neue Kollegin ist sehr §sympathisch§, ich mag sie sofort.",
"teuer": "Die Miete in der Stadt ist sehr §teuer§ geworden.",
"traurig": "Mein Hund ist weggelaufen, ich bin total §traurig§.",
"treiben": "Ein leeres Boot §treibt§ langsam auf dem Wasser.",
"um den heißen Brei reden": "Hör auf, §um den heißen Brei zu reden§, und sag es einfach!",
"umsteigen": "In München müssen wir §umsteigen§.",
"umwerfend": "Auf der Hochzeit sah meine Schwester einfach §umwerfend§ aus.",
"verstehen": "Am Anfang habe ich im Amt fast nichts §verstanden§.",
"winzig": "Meine erste Wohnung war §winzig§, nur achtzehn Quadratmeter.",
"wunderbar": "Wir hatten einen §wunderbaren§ Nachmittag im Garten.",
"würzen": "Vergiss nicht, die Suppe zu §würzen§.",
"wütend": "Als der Zug schon wieder ausfiel, wurde ich richtig §wütend§.",
"zusagen / absagen": "Für die Hochzeit im Juni habe ich schon §zugesagt§.",
"zuverlässig": "Auf meinen Nachbarn kann ich mich immer verlassen, er ist §zuverlässig§.",
"ängstlich": "Vor dem Termin beim Zahnarzt bin ich immer ein bisschen §ängstlich§.",
"üben": "Wenn du jeden Tag zehn Minuten §übst§, wirst du schnell besser.",
"überrascht": "Meine Freunde haben mich vom Bahnhof abgeholt, und ich war total §überrascht§."
};
