# -*- coding: utf-8 -*-
"""Ersetzt die Uebungslisten der drei B1-Lektionen durch gemischte Aufgabenformen."""
import json, sys, os
from collections import Counter

BASIS = sys.argv[1] if len(sys.argv) > 1 else '.'

UEB = {}

UEB['gram-praepositionaladverbien.json'] = [
 {"t":"gap","s":"Ich warte auf den Bus. — Ich warte ___.","r":"darauf","o":["darauf","dafür","davor"],
  "e":"warten auf plus Sache wird darauf. Vor dem Vokal kommt ein r dazwischen."},
 {"t":"hoer","audio":"Worauf wartest du eigentlich noch?","s":"Wonach wird gefragt?",
  "r":"Nach einer Sache.","o":["Nach einer Sache.","Nach einer Person.","Nach einem Ort.","Nach einer Uhrzeit."],
  "e":"worauf fragt nach einer Sache. Bei einer Person hieße es: Auf wen wartest du?"},
 {"t":"bau","s":"Bring die Wörter in die richtige Reihenfolge.","w":["Ich","freue","mich","schon","darauf"],
  "e":"Das da-Wort steht hier am Satzende und zeigt nach vorn auf das, was kommt."},
 {"t":"fehler","s":"Ein Wort ist falsch. Tippe es an.","s2":"Ich freue mich über es.",
  "falsch":"es","richtig":"Ich freue mich darüber.",
  "e":"Nach einer Präposition steht bei Sachen nie es oder das — dort baut man ein da-Wort."},
 {"t":"gap","s":"Er denkt an den Termin. — Er denkt ___.","r":"daran","o":["daran","darauf","davon"],
  "e":"denken an plus Sache wird daran."},
 {"t":"sort","s":"Person oder Sache? Tippe erst einen Satz an, dann das Fach.",
  "kat":["Person → Präposition + Pronomen","Sache → da-Wort"],
  "items":[["Ich warte auf sie.",0],["Ich warte darauf.",1],["Ich denke an ihn.",0],["Ich denke daran.",1],["Wir sprechen über ihn.",0],["Wir sprechen darüber.",1]],
  "e":"Das ist die ganze Regel: Menschen behalten Präposition plus Pronomen, Sachen bekommen ein da-Wort."},
 {"t":"gap","s":"___ hast du das aufgemacht? — Mit dem Messer.","r":"Womit","o":["Womit","Worauf","Wovon"],
  "e":"mit plus Sache in der Frage wird womit. Vor Konsonant ohne r."},
 {"t":"choice","s":"Ich warte auf meine Schwester. Wie geht es weiter: Ich warte …","r":"auf sie",
  "o":["auf sie","darauf","worauf","auf ihr"],
  "e":"Bei Personen bleibt die Präposition und es folgt ein Pronomen. Nur Sachen bekommen ein da-Wort."},
 {"t":"bau","s":"Bring die Wörter in die richtige Reihenfolge.","w":["Damit","bin","ich","einverstanden"],
  "e":"Das da-Wort kann auch auf Platz eins stehen — dann rückt das Verb direkt dahinter."},
 {"t":"hoer","audio":"Daran habe ich überhaupt nicht gedacht.","s":"Was sagt die Person?",
  "r":"Sie hat etwas vergessen.","o":["Sie hat etwas vergessen.","Sie ist verärgert.","Sie stimmt zu.","Sie fragt nach."],
  "e":"Daran habe ich nicht gedacht heißt: Das ist mir nicht eingefallen."},
 {"t":"gap","s":"Ich habe Angst vor großen Hunden. — Ich habe Angst ___.","r":"davor","o":["davor","dafür","darauf"],
  "e":"Angst haben vor plus Sache wird davor. Vor Konsonant ohne r."},
 {"t":"fehler","s":"Ein Wort ist falsch. Tippe es an.","s2":"Ich interessiere mich dafür Geschichte.",
  "falsch":"dafür","richtig":"Ich interessiere mich für Geschichte.",
  "e":"Steht das Nomen noch im Satz, braucht man nur die Präposition. Das da-Wort ersetzt das Nomen."},
 {"t":"choice","s":"Warum heißt es „darauf“ und nicht „daauf“?","r":"Weil vor einem Vokal ein r eingeschoben wird.",
  "o":["Weil vor einem Vokal ein r eingeschoben wird.","Weil auf immer ein r verlangt.","Weil es zwei getrennte Wörter sind.","Weil der Akkusativ ein r braucht."],
  "e":"da + r + auf. Genauso: woran, darüber, worüber. Vor Konsonant ohne r: damit, davor."},
 {"t":"schreib","s":"Eine Kollegin fragt, ob ihr am Freitag später anfangen könnt. Du bist einverstanden und freust dich auf das Wochenende. Antworte in zwei Sätzen mit da-Wörtern.",
  "muster":"Damit bin ich einverstanden, das passt mir sogar besser. Und aufs Wochenende freue ich mich sowieso schon — darauf warte ich die ganze Woche.",
  "e":"damit einverstanden sein, sich auf etwas freuen: Deine Sätze dürfen natürlich anders klingen."},
]

UEB['gram-ndeklination.json'] = [
 {"t":"gap","s":"Ich spreche mit dem ___ aus meinem Kurs.","r":"Studenten","o":["Studenten","Student","Studentes"],
  "e":"Nach mit steht der Dativ. Endung -ent, also Studenten."},
 {"t":"sort","s":"Gehört das Wort zur n-Deklination? Tippe erst ein Wort an, dann das Fach.",
  "kat":["Bekommt ein -n","Bleibt immer gleich"],
  "items":[["der Kollege",0],["der Lehrer",1],["der Praktikant",0],["der Vater",1],["der Nachbar",0],["der Freund",1]],
  "e":"Nur maskuline Nomen auf -e, auf -ent/-ant/-ist/-at und die Einzelgänger wie Herr, Mensch, Nachbar, Bär machen mit."},
 {"t":"hoer","audio":"Ich habe Herrn Meier gestern angerufen.","s":"Wird Herr Meier angesprochen oder erwähnt?",
  "r":"Er wird erwähnt.","o":["Er wird erwähnt.","Er wird angesprochen.","Er ruft selbst an.","Er ist nicht gemeint."],
  "e":"Herrn mit -n heißt: Es wird über ihn gesprochen. Angesprochen hieße es: Guten Tag, Herr Meier."},
 {"t":"bau","s":"Bring die Wörter in die richtige Reihenfolge.","w":["Ich","habe","dem","Studenten","alles","erklärt"],
  "e":"Nach haben steht das Partizip am Ende, dazwischen Dativobjekt und Ergänzung."},
 {"t":"fehler","s":"Ein Wort ist falsch. Tippe es an.","s2":"Ich habe Herr Weber schon informiert.",
  "falsch":"Herr","richtig":"Ich habe Herrn Weber schon informiert.",
  "e":"Außerhalb der direkten Anrede bekommt Herr im Singular ein -n."},
 {"t":"gap","s":"Der ___ hat die Prüfung bestanden.","r":"Student","o":["Student","Studenten","Studentes"],
  "e":"Subjekt im Nominativ — hier bleibt das Wort ohne Endung."},
 {"t":"gap","s":"Kennst du den ___ von nebenan?","r":"Nachbarn","o":["Nachbarn","Nachbar","Nachbars"],
  "e":"Akkusativ. Nachbar gehört zu den Einzelgängern."},
 {"t":"bau","s":"Bring die Wörter in die richtige Reihenfolge.","w":["Wir","haben","den","Polizisten","nach","dem","Weg","gefragt"],
  "e":"Perfekt: haben auf Platz zwei, Partizip ganz am Ende."},
 {"t":"choice","s":"Welches Wort gehört NICHT zur n-Deklination?","r":"der Lehrer",
  "o":["der Lehrer","der Kollege","der Praktikant","der Nachbar"],
  "e":"Lehrer endet nicht auf -e und nicht auf -ent oder -ist. Es bleibt in allen Fällen gleich: den Lehrer, dem Lehrer."},
 {"t":"hoer","audio":"Den Namen des Nachbarn weiß ich leider nicht.","s":"Welche zwei Formen hörst du?",
  "r":"den Namen und des Nachbarn","o":["den Namen und des Nachbarn","der Name und der Nachbar","dem Namen und dem Nachbarn","des Namens und dem Nachbar"],
  "e":"Akkusativ den Namen, Genitiv des Nachbarn. Beide Wörter gehören zur n-Deklination."},
 {"t":"fehler","s":"Ein Wort ist falsch. Tippe es an.","s2":"Im Zoo haben wir einen Bär gesehen.",
  "falsch":"Bär","richtig":"Im Zoo haben wir einen Bären gesehen.",
  "e":"der Bär, den Bären — wie der Mensch, den Menschen."},
 {"t":"gap","s":"Die Bedeutung des ___ kennt hier niemand.","r":"Namens","o":["Namens","Namen","Name"],
  "e":"Name gehört zur kleinen Gruppe mit -ns im Genitiv: des Namens, des Gedankens, des Willens."},
 {"t":"choice","s":"Wie viele verschiedene Formen hat „der Kollege“ im Singular?","r":"Zwei: Kollege und Kollegen.",
  "o":["Zwei: Kollege und Kollegen.","Vier, für jeden Fall eine.","Nur eine, sie ändert sich nie.","Drei, der Genitiv ist noch anders."],
  "e":"Nominativ Kollege, alle anderen Fälle Kollegen. Deshalb ist diese Gruppe leichter, als sie aussieht."},
 {"t":"schreib","s":"Schreib eine kurze E-Mail an eine Kollegin: Du hast Herrn Sommer informiert und mit einem Praktikanten gesprochen. Zwei bis drei Sätze.",
  "muster":"Hallo Marie, ich habe Herrn Sommer heute Morgen informiert — er ist einverstanden. Außerdem habe ich mit dem neuen Praktikanten gesprochen und ihm alles gezeigt.",
  "e":"Achte auf Herrn und auf dem/den Praktikanten. Dein Text darf natürlich anders klingen."},
]

UEB['gram-lassen.json'] = [
 {"t":"gap","s":"Ich ___ mir jeden Monat die Haare schneiden.","r":"lasse","o":["lasse","lässt","lassen"],
  "e":"Erste Person Singular: ich lasse."},
 {"t":"sort","s":"Was bedeutet lassen hier? Tippe erst einen Satz an, dann das Fach.",
  "kat":["Ein anderer macht es","Ich erlaube es","Ich lasse es zurück"],
  "items":[["Ich lasse mein Auto reparieren.",0],["Meine Eltern lassen mich gehen.",1],["Ich habe das Handy im Büro gelassen.",2],["Wir lassen die Wohnung streichen.",0],["Lass ihn noch schlafen.",1],["Ich habe den Schirm im Zug gelassen.",2]],
  "e":"Dieselbe Form, drei Bedeutungen. Die Situation verrät jedes Mal, welche gemeint ist."},
 {"t":"bau","s":"Bring die Wörter in die richtige Reihenfolge.","w":["Ich","habe","mein","Auto","reparieren","lassen"],
  "e":"Perfekt mit zweitem Verb: haben auf Platz zwei, am Ende zwei Infinitive."},
 {"t":"fehler","s":"Ein Wort ist falsch. Tippe es an.","s2":"Ich habe die Haare schneiden gelassen.",
  "falsch":"gelassen","richtig":"Ich habe die Haare schneiden lassen.",
  "e":"Zwei Verben am Ende heißt zweimal Infinitiv — das nennt man Ersatzinfinitiv."},
 {"t":"gap","s":"Er ___ sein Auto in der Werkstatt reparieren.","r":"lässt","o":["lässt","lasst","lasse"],
  "e":"Dritte Person Singular mit Umlaut: er lässt."},
 {"t":"hoer","audio":"Lass uns morgen einfach weitermachen.","s":"Was ist das?",
  "r":"Ein Vorschlag.","o":["Ein Vorschlag.","Ein Befehl an eine fremde Person.","Eine Absage.","Eine Frage."],
  "e":"Lass uns … ist die normale deutsche Art, einen gemeinsamen Vorschlag zu machen."},
 {"t":"gap","s":"Ich habe mein Handy im Büro ___.","r":"gelassen","o":["gelassen","lassen","gelasst"],
  "e":"lassen steht hier allein, deshalb das normale Partizip gelassen."},
 {"t":"bau","s":"Bring die Wörter in die richtige Reihenfolge.","w":["Meine","Eltern","lassen","mich","am","Wochenende","ausgehen"],
  "e":"lassen verhält sich wie ein Modalverb: Platz zwei, zweites Verb ganz ans Ende."},
 {"t":"gap","s":"___ mich bitte ausreden!","r":"Lass","o":["Lass","Lasse","Lässt"],
  "e":"Du-Imperativ ohne Endung: Lass."},
 {"t":"hoer","audio":"Das lasse ich lieber machen.","s":"Was heißt das?",
  "r":"Jemand anders soll es tun.","o":["Jemand anders soll es tun.","Ich mache es selbst.","Ich möchte es nicht.","Ich habe es vergessen."],
  "e":"machen lassen heißt: in Auftrag geben statt selbst tun."},
 {"t":"fehler","s":"Ein Wort ist falsch. Tippe es an.","s2":"Ich lasse mein Auto zu reparieren.",
  "falsch":"zu","richtig":"Ich lasse mein Auto reparieren.",
  "e":"Nach lassen steht der Infinitiv ohne zu — genau wie nach können und müssen."},
 {"t":"choice","s":"Welche Bedeutung hat lassen in „Ich lasse mein Fahrrad reparieren“?","r":"Jemand anders repariert es für mich.",
  "o":["Jemand anders repariert es für mich.","Ich erlaube es jemandem.","Ich lasse das Fahrrad irgendwo stehen.","Ich höre auf zu reparieren."],
  "e":"Das ist die Bedeutung machen lassen: Ich gebe es in Auftrag, ein anderer führt es aus."},
 {"t":"choice","s":"Warum heißt es „Ich habe den Schlüssel gelassen“, aber „Ich habe reparieren lassen“?","r":"Weil bei zwei Verben am Ende der Ersatzinfinitiv steht.",
  "o":["Weil bei zwei Verben am Ende der Ersatzinfinitiv steht.","Weil Schlüssel ein Nomen ist.","Weil man beide Perfektformen frei wählen kann.","Weil der erste Satz im Präsens steht."],
  "e":"Steht lassen allein, heißt das Partizip gelassen. Kommt ein zweites Verb dazu, stehen am Ende zwei Infinitive. Genauso bei sehen und hören: Ich habe ihn kommen sehen."},
 {"t":"schreib","s":"Dein Auto ist kaputt, deine Wohnung müsste gestrichen werden und dein Mantel gereinigt. Erzähl in drei Sätzen, was du diese Woche alles machen lässt.",
  "muster":"Diese Woche lasse ich endlich mein Auto reparieren. Danach lasse ich die Wohnung streichen, das schiebe ich schon lange vor mir her. Und den Mantel lasse ich gleich morgen reinigen.",
  "e":"Dreimal machen lassen. Deine Sätze dürfen natürlich anders klingen."},
]

for datei, liste in UEB.items():
    p = os.path.join(BASIS, datei)
    d = json.load(open(p, encoding='utf-8'))
    d['ueb'] = liste
    json.dump(d, open(p, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    print(datei, '→', dict(Counter(a['t'] for a in liste)))
