#!/usr/bin/env python3
import json, re, sys, os

HIER = os.path.dirname(os.path.abspath(__file__))
CSS = open(os.path.join(HIER, 'vorlage.css'), encoding='utf-8').read()
JS = open(os.path.join(HIER, 'vorlage.js'), encoding='utf-8').read()

def typo(t):
    return re.sub(r'„([^„"“]{1,400})"', lambda m: '„'+m.group(1)+'“', t)

def bau(d):
    o = []
    A = o.append
    A('<!DOCTYPE html><html lang="de"><head>')
    A('<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">')
    A('<title>Sprachspielclub · %s · Spiele-Mix &amp; großes Quiz · ab B1 | deutschoderwas</title>' % d['ort'])
    A('<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>')
    A('<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,wght@0,400;0,600;0,700;0,900;1,400;1,600&family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">')
    A('<style>')
    A(CSS.replace('#DFEDDA', d.get('farbe', '#DFEDDA')))
    A('</style></head>')
    A('<body><div class="wrapper">')
    A('<div class="eyebrow">deutschoderwas · Sprachspielclub · %s · ab B1</div>' % d['datum'])
    A('<h1 class="title">%s <span class="hl">%s</span></h1>' % (d['titel_vor'], d['titel_hl']))
    A('<p class="subtitle">%s</p>' % d['untertitel'])
    A('<div class="hero-tags">')
    for e, n in [('🔍','Suchbild'),('🔤','Wortschatz'),('📍','Wo? &amp; Wohin?'),('🎲','Tabu'),('🗣️','Frei sprechen'),('🏆','Großes Quiz')]:
        A('<span class="hero-tag">%s <b>%s</b></span>' % (e, n))
    A('</div>')
    A('<nav class="tabs">')
    for i, (e, n) in enumerate([('🔍','Das Bild'),('🎁','Rate-Spiel'),('📍','Präpositionen'),('🔤','Tabu'),('🗣️','Sprechen'),('🏆','Großes Quiz')]):
        A('<button class="tab%s" data-tab="%d">%s %s</button>' % (' active' if i == 0 else '', i, e, n))
    A('</nav>')

    A('<section class="section active" data-section="0">')
    A('<h2 class="st">Was gibt es hier <em>alles</em> zu sehen?</h2>')
    A('<p class="ssub">%s</p>' % d['bild_sub'])
    A('<div class="scene-wrap"><img src="bilder/%s" alt="%s" loading="lazy"></div>' % (d['bild'], d['bild_alt']))
    A('<div class="tip">💡 <strong>Erste Runde:</strong> Jede Person sucht sich <u>eine Ecke</u> des Bildes aus und erzählt eine Minute lang, was dort passiert. Die anderen dürfen danach genau <u>zwei Fragen</u> dazu stellen. Wer nichts mehr findet, gibt weiter.</div>')
    A('<h2 class="st">Findet diese <em>Sachen</em></h2>')
    A('<p class="ssub">Tippt ein Wort an, wenn ihr es gefunden <strong>und</strong> die Lage beschrieben habt: %s</p>' % d['find_sub'])
    A('<div class="find-grid" id="findGrid"></div>')
    A('<p class="zaehler" id="findZaehler">0 von %d gefunden</p>' % len(d['finden']))
    A('<h2 class="st">Die <em>Wörter</em> dazu</h2>')
    A('<p class="ssub">Sagt jedes Wort laut — und gleich den ganzen Beispielsatz dazu. Der Artikel gehört immer mit dazu.</p>')
    A('<div style="text-align:center;margin:.4rem 0"><button class="btn ghost" id="verdecken">🙈 Wörter verdecken</button></div>')
    A('<div class="bgrid" id="bgrid"></div>')
    A('<div class="tip">💡 <strong>Spiel dazu:</strong> Verdeckt die Wörter. Eine Person beschreibt eine Karte in drei Sätzen, ohne das Wort zu nennen — die anderen raten. Tippt auf eine Karte, um sie einzeln aufzudecken.</div>')
    A('</section>')

    A('<section class="section" data-section="1">')
    A('<h2 class="st">🎁 „Ich sehe etwas, das …“</h2>')
    A('<p class="ssub">Eine Person zieht ein geheimes Wort aus dem Bild und beschreibt nur mit Präpositionen, <strong>wo</strong> es ist — die anderen raten, was es ist!</p>')
    A('<div class="karte">')
    A('<div class="lbl">🤫 Dein geheimes Wort</div>')
    A('<div class="kwort" id="geheimWort">Bereit?</div>')
    A('<div style="font-size:.92rem;color:var(--ink-soft);">Beschreibe seine <u>Lage</u> — aber sag das Wort nicht!</div>')
    A('</div>')
    A('<div class="controls"><button class="btn" onclick="neuesGeheim()">🎁 Neues Wort</button></div>')
    A('<div class="tip teal">🗣️ <strong>So beschreibst du:</strong> „Es <u>befindet sich</u> …“ · „Es <u>liegt</u> / <u>steht</u> / <u>hängt</u> …“ + Präposition + Dativ.</div>')
    A('<div class="tip">🏆 <strong>Spielregeln:</strong> Nenne mindestens <u>zwei</u> Präpositionen, bevor die anderen raten dürfen. Wer richtig rät, bekommt einen Punkt und ist als Nächstes dran.</div>')
    A('</section>')

    A('<section class="section" data-section="2">')
    A('<div class="gintro">📍 Neun Präpositionen, zwei Fragen. <b>Wo?</b> fragt nach der Lage — dann kommt der <b>Dativ</b>. <b>Wohin?</b> fragt nach der Richtung — dann kommt der <b>Akkusativ</b>. Dieselbe Präposition, zwei Fälle.</div>')
    A('<h2 class="st">Wo? → <em>Dativ</em></h2>')
    A('<p class="ssub">Die Sache ist schon da und bewegt sich nicht. Bildet zu jeder Präposition einen eigenen Satz zum Bild.</p>')
    A('<div class="gkette">')
    for p, s in d['dativ']:
        A('<div class="gstep"><span class="gw">%s</span><div class="gs">„%s“</div></div>' % (p, s))
    A('</div>')
    A('<div class="tip">🧠 <strong>Dativ-Artikel:</strong> der → <u>dem</u> · das → <u>dem</u> · die → <u>der</u> · Plural → <u>den</u> (+n).</div>')
    A('<h2 class="st">Wohin? → <em>Akkusativ</em></h2>')
    A('<p class="ssub">Etwas bewegt sich irgendwohin. Achtet auf das Verb: gehen, legen, stellen, werfen — das sind die Verräter.</p>')
    A('<div class="gkette">')
    for p, s in d['akkusativ']:
        A('<div class="gstep akk"><span class="gw">%s</span><div class="gs">„%s“</div></div>' % (p, s))
    A('</div>')
    A('<div class="tip teal">🧠 <strong>Akkusativ-Artikel:</strong> der → <u>den</u> · das → <u>das</u> · die → <u>die</u> · Plural → <u>die</u>. Merksatz: <strong>Wo? = Dativ</strong> (es ist schon da) · <strong>Wohin? = Akkusativ</strong> (es bewegt sich dorthin).</div>')
    A('<div class="tip">🎲 <strong>Spiel dazu:</strong> Eine Person sagt einen Satz mit <u>Wo?</u>, die nächste macht daraus einen Satz mit <u>Wohin?</u>. Wer den Fall verwechselt, gibt weiter.</div>')
    A('</section>')

    A('<section class="section" data-section="3">')
    A('<h2 class="st">🔤 <em>Tabu</em></h2>')
    A('<p class="ssub">Erkläre das Wort oben — aber <strong>ohne</strong> die verbotenen Wörter zu benutzen! Die anderen raten. Tipp: Fang mit „Das ist ein Ort, an dem …“ oder „Das braucht man, wenn …“ an.</p>')
    A('<div class="karte" id="tabuKarte"></div>')
    A('<div class="controls"><button class="btn" onclick="neuesTabu()">🔤 Neue Karte</button></div>')
    A('<div class="tip">⏱️ <strong>Spielidee:</strong> 60 Sekunden pro Runde. Für jedes erratene Wort gibt es einen Punkt. Benutzt jemand ein verbotenes Wort, ist die Karte futsch. Zwei Teams treten gegeneinander an!</div>')
    A('</section>')

    A('<section class="section" data-section="4">')
    A('<h2 class="st">🗣️ Frei <em>sprechen</em></h2>')
    A('<p class="ssub">Sprecht frei — nutzt den Wortschatz aus dem Bild.</p>')
    A('<div class="debate-grid">')
    for label, frage in d['sprechen']:
        A('<div class="debate"><div class="debate-num">%s</div><div class="debate-q">%s</div></div>' % (label, frage))
    A('</div>')
    A('<div class="tip">🔑 <strong>Redemittel fürs Bild:</strong> „Ganz vorne / hinten sieht man …“ · „Direkt daneben …“ · „Mitten im Bild / in der Ecke …“ · „Links / rechts von … befindet sich …“ · „Im Vordergrund / im Hintergrund …“</div>')
    deb = d['debatte']
    A('<h2 class="st">⚖️ Kleine <em>Debatte</em></h2>')
    A('<p class="ssub">%s</p>' % deb['frage'])
    A('<div class="pcgrid">')
    for seite, cls in (('pro','pro'), ('con','con')):
        s = deb[seite]
        A('<div class="pcol %s"><h4>%s</h4><ul>%s</ul></div>' % (cls, s['titel'], ''.join('<li>%s</li>' % x for x in s['punkte'])))
    A('</div>')
    A('<div class="rmcard"><b>So sagst du deine Meinung</b><div style="margin-top:.4rem">'
      '<span class="rm">Ich finde, …</span><span class="rm">Für mich ist …</span><span class="rm">Das mag sein, aber …</span>'
      '<span class="rm">Da bin ich anderer Meinung, weil …</span><span class="rm">Genau das ist doch das Problem: …</span></div></div>')
    A('<div class="tip">🎲 <strong>So geht es:</strong> Zwei Gruppen. Jede bekommt eine Seite <u>zugelost</u> — auch die, die sie selbst nicht glaubt. Drei Minuten sammeln, dann abwechselnd sprechen, immer ein Satz.</div>')
    A('<h2 class="st">🎬 <em>Rollenspiele</em></h2>')
    A('<p class="ssub">Zieht eine Karte, verteilt die zwei Rollen und spielt die Szene zwei bis drei Minuten. Die Wörter unten dürfen — sollen! — vorkommen.</p>')
    A('<div class="karte" id="sitKarte"></div>')
    A('<div class="controls"><button class="btn" onclick="neueSituation()">🎲 Neue Szene</button><button class="btn ghost" onclick="alleSituationen()">📋 Alle anzeigen</button></div>')
    A('<div id="sitAlle" style="display:none"></div>')
    A('<div class="tip teal">🗣️ <strong>Nach jeder Szene, ein Satz reihum:</strong> „Ich hätte an deiner Stelle gesagt: …“ — so hört ihr drei Varianten für dieselbe Situation statt nur einer.</div>')
    A('</section>')

    A('<section class="section" data-section="5">')
    A('<h2 class="st">🏆 Das <em>große Quiz</em></h2>')
    A('<p class="ssub">%s</p>' % d['quiz_sub'])
    A('<div class="quiz-runden" id="quizRunden"></div>')
    A('<div class="quiz-buehne">')
    A('  <div class="quiz-kopf"><span class="quiz-zaehler" id="quizZaehler">Runde 1 · Frage 1</span><span class="quiz-punkte" id="quizPunkte">0 von 6</span></div>')
    A('  <div class="quiz-balken"><i id="quizBalken" style="width:0%"></i></div>')
    A('  <div id="quizInhalt">')
    A('    <div class="quiz-frage" id="quizFrage"></div>')
    A('    <div class="quiz-opts" id="quizOpts"></div>')
    A('    <div class="quiz-erkl" id="quizErkl"></div>')
    A('    <div class="quiz-fuss"><button class="btn ghost" onclick="quizRundeStart(qRunde)">↺ Runde neu</button><button class="btn" onclick="quizWeiter()">Weiter →</button></div>')
    A('  </div>')
    A('  <div class="quiz-ende" id="quizEnde" style="display:none"></div>')
    A('</div>')
    A('<div class="tip teal">🏅 <strong>Als Wettkampf:</strong> Zwei Teams, abwechselnd. Wer die richtige Antwort hat, muss zusätzlich <u>einen eigenen Satz</u> mit dem Wort bilden — erst dann gibt es den Punkt.</div>')
    A('</section>')

    A('<footer>')
    A('<strong>deutschoderwas</strong> · Sprachspielclub am Samstag · %s · ab B1<br>' % d['datum'])
    A(d['fusszeile'])
    A('</footer>')
    A('</div>')
    A('<script>')
    A(JS)
    A('var FINDEN=' + json.dumps(d['finden'], ensure_ascii=False) + ';')
    A('var WORT=' + json.dumps(d['woerter'], ensure_ascii=False) + ';')
    A('var SIT=' + json.dumps(d['rollenspiele'], ensure_ascii=False) + ';')
    A('var TABU=' + json.dumps(d['tabu'], ensure_ascii=False) + ';')
    A('var QUIZ=' + json.dumps(d['quiz'], ensure_ascii=False) + ';')
    A('start();')
    A('</script>')
    A('</body></html>')
    return typo('\n'.join(o))

if __name__ == '__main__':
    d = json.load(open(sys.argv[1], encoding='utf-8'))
    open(sys.argv[2], 'w', encoding='utf-8').write(bau(d))
    print('geschrieben:', sys.argv[2])
